/*
 * AUTO-GENERATED by scripts/gen_romassets.py (J) -- do not edit.
 *
 * Absolute ROM asset symbols for the PC port. Each symbol is the N64
 * cart address (0x10000000 + rom_offset) of the corresponding asset in
 * scripts/filelist.j.csv, so `&symbol` / romCopy() work exactly as
 * on hardware once romdata.c has mapped the .z64 at 0x10000000.
 * Regenerate: python3 scripts/gen_romassets.py j
 */
.section .data

/* --- assets/obseg (file_resource_table.inc.c order) ------------- */
.global bg_sev_all_p_seg
.set bg_sev_all_p_seg, 0x10439380
.global end_bg_sev_all_p_seg
.set end_bg_sev_all_p_seg, 0x1044A170
.global bg_silo_all_p_seg
.set bg_silo_all_p_seg, 0x1044A170
.global end_bg_silo_all_p_seg
.set end_bg_silo_all_p_seg, 0x1049B0B0
.global bg_stat_all_p_seg
.set bg_stat_all_p_seg, 0x1049B0B0
.global end_bg_stat_all_p_seg
.set end_bg_stat_all_p_seg, 0x104BD180
.global bg_arec_all_p_seg
.set bg_arec_all_p_seg, 0x104BD180
.global end_bg_arec_all_p_seg
.set end_bg_arec_all_p_seg, 0x104EB500
.global bg_arch_all_p_seg
.set bg_arch_all_p_seg, 0x104EB500
.global end_bg_arch_all_p_seg
.set end_bg_arch_all_p_seg, 0x10510FF0
.global bg_tra_all_p_seg
.set bg_tra_all_p_seg, 0x10510FF0
.global end_bg_tra_all_p_seg
.set end_bg_tra_all_p_seg, 0x10531560
.global bg_dest_all_p_seg
.set bg_dest_all_p_seg, 0x10531560
.global end_bg_dest_all_p_seg
.set end_bg_dest_all_p_seg, 0x1055EF20
.global bg_sevb_all_p_seg
.set bg_sevb_all_p_seg, 0x1055EF20
.global end_bg_sevb_all_p_seg
.set end_bg_sevb_all_p_seg, 0x10579CC0
.global bg_azt_all_p_seg
.set bg_azt_all_p_seg, 0x10579CC0
.global end_bg_azt_all_p_seg
.set end_bg_azt_all_p_seg, 0x1059B710
.global bg_pete_all_p_seg
.set bg_pete_all_p_seg, 0x1059B710
.global end_bg_pete_all_p_seg
.set end_bg_pete_all_p_seg, 0x105B5340
.global bg_depo_all_p_seg
.set bg_depo_all_p_seg, 0x105B5340
.global end_bg_depo_all_p_seg
.set end_bg_depo_all_p_seg, 0x105E1CB0
.global bg_ref_all_p_seg
.set bg_ref_all_p_seg, 0x105E1CB0
.global end_bg_ref_all_p_seg
.set end_bg_ref_all_p_seg, 0x105EB2C0
.global bg_cryp_all_p_seg
.set bg_cryp_all_p_seg, 0x105EB2C0
.global end_bg_cryp_all_p_seg
.set end_bg_cryp_all_p_seg, 0x10600970
.global bg_dam_all_p_seg
.set bg_dam_all_p_seg, 0x10600970
.global end_bg_dam_all_p_seg
.set end_bg_dam_all_p_seg, 0x10630B10
.global bg_ark_all_p_seg
.set bg_ark_all_p_seg, 0x10630B10
.global end_bg_ark_all_p_seg
.set end_bg_ark_all_p_seg, 0x10661A90
.global bg_run_all_p_seg
.set bg_run_all_p_seg, 0x10661A90
.global end_bg_run_all_p_seg
.set end_bg_run_all_p_seg, 0x1066BE60
.global bg_sevx_all_p_seg
.set bg_sevx_all_p_seg, 0x1066BE60
.global end_bg_sevx_all_p_seg
.set end_bg_sevx_all_p_seg, 0x10688430
.global bg_jun_all_p_seg
.set bg_jun_all_p_seg, 0x10688430
.global end_bg_jun_all_p_seg
.set end_bg_jun_all_p_seg, 0x1069D580
.global bg_dish_all_p_seg
.set bg_dish_all_p_seg, 0x1069D580
.global end_bg_dish_all_p_seg
.set end_bg_dish_all_p_seg, 0x106A1DF0
.global bg_cave_all_p_seg
.set bg_cave_all_p_seg, 0x106A1DF0
.global end_bg_cave_all_p_seg
.set end_bg_cave_all_p_seg, 0x106C62E0
.global bg_cat_all_p_seg
.set bg_cat_all_p_seg, 0x106C62E0
.global end_bg_cat_all_p_seg
.set end_bg_cat_all_p_seg, 0x106CB810
.global bg_crad_all_p_seg
.set bg_crad_all_p_seg, 0x106CB810
.global end_bg_crad_all_p_seg
.set end_bg_crad_all_p_seg, 0x106DBB60
.global bg_sho_all_p_seg
.set bg_sho_all_p_seg, 0x106DBB60
.global end_bg_sho_all_p_seg
.set end_bg_sho_all_p_seg, 0x106DBB60
.global bg_imp_all_p_seg
.set bg_imp_all_p_seg, 0x106DBB60
.global end_bg_imp_all_p_seg
.set end_bg_imp_all_p_seg, 0x106DBB60
.global bg_rit_all_p_seg
.set bg_rit_all_p_seg, 0x106E5AC0
.global end_bg_rit_all_p_seg
.set end_bg_rit_all_p_seg, 0x106E5AC0
.global bg_oat_all_p_seg
.set bg_oat_all_p_seg, 0x106E5AC0
.global end_bg_oat_all_p_seg
.set end_bg_oat_all_p_seg, 0x106EC910
.global bg_ear_all_p_seg
.set bg_ear_all_p_seg, 0x106EC910
.global end_bg_ear_all_p_seg
.set end_bg_ear_all_p_seg, 0x106EC910
.global bg_lee_all_p_seg
.set bg_lee_all_p_seg, 0x106EC910
.global end_bg_lee_all_p_seg
.set end_bg_lee_all_p_seg, 0x106EC910
.global bg_lip_all_p_seg
.set bg_lip_all_p_seg, 0x106EC910
.global end_bg_lip_all_p_seg
.set end_bg_lip_all_p_seg, 0x106EC910
.global bg_len_all_p_seg
.set bg_len_all_p_seg, 0x106EC910
.global end_bg_len_all_p_seg
.set end_bg_len_all_p_seg, 0x106ED8B0
.global bg_wax_all_p_seg
.set bg_wax_all_p_seg, 0x106ED8B0
.global end_bg_wax_all_p_seg
.set end_bg_wax_all_p_seg, 0x106ED8B0
.global bg_pam_all_p_seg
.set bg_pam_all_p_seg, 0x106ED8B0
.global end_bg_pam_all_p_seg
.set end_bg_pam_all_p_seg, 0x106ED8B0
.global CarmourguardZ
.set CarmourguardZ, 0x106ED8B0
.global end_CarmourguardZ
.set end_CarmourguardZ, 0x106EFD30
.global CbaronsamediZ
.set CbaronsamediZ, 0x106EFD30
.global end_CbaronsamediZ
.set end_CbaronsamediZ, 0x106F3420
.global CbluecamguardZ
.set CbluecamguardZ, 0x106F3420
.global end_CbluecamguardZ
.set end_CbluecamguardZ, 0x106F5B10
.global CbluemanZ
.set CbluemanZ, 0x106F5B10
.global end_CbluemanZ
.set end_CbluemanZ, 0x106F7920
.global CbluewomanZ
.set CbluewomanZ, 0x106F7920
.global end_CbluewomanZ
.set end_CbluewomanZ, 0x106F97E0
.global CboilerbondZ
.set CboilerbondZ, 0x106F97E0
.global end_CboilerbondZ
.set end_CboilerbondZ, 0x106FC3F0
.global CboilertrevZ
.set CboilertrevZ, 0x106FC3F0
.global end_CboilertrevZ
.set end_CboilertrevZ, 0x106FFA70
.global CborisZ
.set CborisZ, 0x106FFA70
.global end_CborisZ
.set end_CborisZ, 0x10702B90
.global CcamguardZ
.set CcamguardZ, 0x10702B90
.global end_CcamguardZ
.set end_CcamguardZ, 0x10705270
.global CcardimanZ
.set CcardimanZ, 0x10705270
.global end_CcardimanZ
.set end_CcardimanZ, 0x10707070
.global CcheckmanZ
.set CcheckmanZ, 0x10707070
.global end_CcheckmanZ
.set end_CcheckmanZ, 0x10708EF0
.global CcommguardZ
.set CcommguardZ, 0x10708EF0
.global end_CcommguardZ
.set end_CcommguardZ, 0x1070B4F0
.global CdjbondZ
.set CdjbondZ, 0x1070B4F0
.global end_CdjbondZ
.set end_CdjbondZ, 0x1070E380
.global CfattechwomanZ
.set CfattechwomanZ, 0x1070E380
.global end_CfattechwomanZ
.set end_CfattechwomanZ, 0x107102A0
.global Cgreatguard2Z
.set Cgreatguard2Z, 0x107102A0
.global end_Cgreatguard2Z
.set end_Cgreatguard2Z, 0x107129C0
.global CgreatguardZ
.set CgreatguardZ, 0x107129C0
.global end_CgreatguardZ
.set end_CgreatguardZ, 0x10715040
.global CgreyguardZ
.set CgreyguardZ, 0x10715040
.global end_CgreyguardZ
.set end_CgreyguardZ, 0x10717710
.global CgreymanZ
.set CgreymanZ, 0x10717710
.global end_CgreymanZ
.set end_CgreymanZ, 0x107194D0
.global CheadalanZ
.set CheadalanZ, 0x107194D0
.global end_CheadalanZ
.set end_CheadalanZ, 0x10719AA0
.global CheadbZ
.set CheadbZ, 0x10719AA0
.global end_CheadbZ
.set end_CheadbZ, 0x1071A010
.global CheadbalaclavaZ
.set CheadbalaclavaZ, 0x1071A010
.global end_CheadbalaclavaZ
.set end_CheadbalaclavaZ, 0x1071A3E0
.global CheadbikeZ
.set CheadbikeZ, 0x1071A3E0
.global end_CheadbikeZ
.set end_CheadbikeZ, 0x1071AA80
.global CheadbrosnanZ
.set CheadbrosnanZ, 0x1071AA80
.global end_CheadbrosnanZ
.set end_CheadbrosnanZ, 0x1071B7D0
.global CheadbrosnanboilerZ
.set CheadbrosnanboilerZ, 0x1071B7D0
.global end_CheadbrosnanboilerZ
.set end_CheadbrosnanboilerZ, 0x1071C370
.global CheadbrosnansnowZ
.set CheadbrosnansnowZ, 0x1071C370
.global end_CheadbrosnansnowZ
.set end_CheadbrosnansnowZ, 0x1071D1F0
.global CheadbrosnansuitZ
.set CheadbrosnansuitZ, 0x1071D1F0
.global end_CheadbrosnansuitZ
.set end_CheadbrosnansuitZ, 0x1071DF70
.global CheadbrosnantimberZ
.set CheadbrosnantimberZ, 0x1071DF70
.global end_CheadbrosnantimberZ
.set end_CheadbrosnantimberZ, 0x1071EB30
.global CheadchrisZ
.set CheadchrisZ, 0x1071EB30
.global end_CheadchrisZ
.set end_CheadchrisZ, 0x1071F070
.global CheaddaveZ
.set CheaddaveZ, 0x1071F070
.global end_CheaddaveZ
.set end_CheaddaveZ, 0x1071F5F0
.global CheaddesZ
.set CheaddesZ, 0x1071F5F0
.global end_CheaddesZ
.set end_CheaddesZ, 0x1071FB20
.global CheadduncanZ
.set CheadduncanZ, 0x1071FB20
.global end_CheadduncanZ
.set end_CheadduncanZ, 0x10720040
.global CheaddwayneZ
.set CheaddwayneZ, 0x10720040
.global end_CheaddwayneZ
.set end_CheaddwayneZ, 0x107205C0
.global CheadgrahamZ
.set CheadgrahamZ, 0x107205C0
.global end_CheadgrahamZ
.set end_CheadgrahamZ, 0x10720B30
.global CheadgrantZ
.set CheadgrantZ, 0x10720B30
.global end_CheadgrantZ
.set end_CheadgrantZ, 0x10721060
.global CheadjimZ
.set CheadjimZ, 0x10721060
.global end_CheadjimZ
.set end_CheadjimZ, 0x10721590
.global Cheadjoe2Z
.set Cheadjoe2Z, 0x10721590
.global end_Cheadjoe2Z
.set end_Cheadjoe2Z, 0x107219B0
.global CheadjoeZ
.set CheadjoeZ, 0x107219B0
.global end_CheadjoeZ
.set end_CheadjoeZ, 0x10721F20
.global CheadjoelZ
.set CheadjoelZ, 0x10721F20
.global end_CheadjoelZ
.set end_CheadjoelZ, 0x10722430
.global CheadkarlZ
.set CheadkarlZ, 0x10722430
.global end_CheadkarlZ
.set end_CheadkarlZ, 0x10722990
.global CheadkenZ
.set CheadkenZ, 0x10722990
.global end_CheadkenZ
.set end_CheadkenZ, 0x10722EE0
.global CheadleeZ
.set CheadleeZ, 0x10722EE0
.global end_CheadleeZ
.set end_CheadleeZ, 0x10723460
.global CheadmandyZ
.set CheadmandyZ, 0x10723460
.global end_CheadmandyZ
.set end_CheadmandyZ, 0x10723850
.global CheadmarionZ
.set CheadmarionZ, 0x10723850
.global end_CheadmarionZ
.set end_CheadmarionZ, 0x10723C60
.global CheadmarkZ
.set CheadmarkZ, 0x10723C60
.global end_CheadmarkZ
.set end_CheadmarkZ, 0x10724190
.global CheadmartinZ
.set CheadmartinZ, 0x10724190
.global end_CheadmartinZ
.set end_CheadmartinZ, 0x107246F0
.global CheadmishkinZ
.set CheadmishkinZ, 0x107246F0
.global end_CheadmishkinZ
.set end_CheadmishkinZ, 0x10724C50
.global CheadneilZ
.set CheadneilZ, 0x10724C50
.global end_CheadneilZ
.set end_CheadneilZ, 0x10725170
.global CheadpeteZ
.set CheadpeteZ, 0x10725170
.global end_CheadpeteZ
.set end_CheadpeteZ, 0x10725700
.global CheadrobinZ
.set CheadrobinZ, 0x10725700
.global end_CheadrobinZ
.set end_CheadrobinZ, 0x10725C10
.global CheadsallyZ
.set CheadsallyZ, 0x10725C10
.global end_CheadsallyZ
.set end_CheadsallyZ, 0x10726010
.global CheadscottZ
.set CheadscottZ, 0x10726010
.global end_CheadscottZ
.set end_CheadscottZ, 0x10726590
.global CheadshaunZ
.set CheadshaunZ, 0x10726590
.global end_CheadshaunZ
.set end_CheadshaunZ, 0x10726B70
.global CheadsteveeZ
.set CheadsteveeZ, 0x10726B70
.global end_CheadsteveeZ
.set end_CheadsteveeZ, 0x107270C0
.global CheadstevehZ
.set CheadstevehZ, 0x107270C0
.global end_CheadstevehZ
.set end_CheadstevehZ, 0x10727610
.global CheadvivienZ
.set CheadvivienZ, 0x10727610
.global end_CheadvivienZ
.set end_CheadvivienZ, 0x10727AA0
.global CjawsZ
.set CjawsZ, 0x10727AA0
.global end_CjawsZ
.set end_CjawsZ, 0x1072A6E0
.global CjeanwomanZ
.set CjeanwomanZ, 0x1072A6E0
.global end_CjeanwomanZ
.set end_CjeanwomanZ, 0x1072C6F0
.global CmaydayZ
.set CmaydayZ, 0x1072C6F0
.global end_CmaydayZ
.set end_CmaydayZ, 0x1072F290
.global CmoonfemaleZ
.set CmoonfemaleZ, 0x1072F290
.global end_CmoonfemaleZ
.set end_CmoonfemaleZ, 0x107313E0
.global CmoonguardZ
.set CmoonguardZ, 0x107313E0
.global end_CmoonguardZ
.set end_CmoonguardZ, 0x107339D0
.global CnatalyaZ
.set CnatalyaZ, 0x107339D0
.global end_CnatalyaZ
.set end_CnatalyaZ, 0x10737290
.global CnavyguardZ
.set CnavyguardZ, 0x10737290
.global end_CnavyguardZ
.set end_CnavyguardZ, 0x10739970
.global CoddjobZ
.set CoddjobZ, 0x10739970
.global end_CoddjobZ
.set end_CoddjobZ, 0x1073CAA0
.global ColiveguardZ
.set ColiveguardZ, 0x1073CAA0
.global end_ColiveguardZ
.set end_ColiveguardZ, 0x1073F0F0
.global CorumovZ
.set CorumovZ, 0x1073F0F0
.global end_CorumovZ
.set end_CorumovZ, 0x10742520
.global CpilotZ
.set CpilotZ, 0x10742520
.global end_CpilotZ
.set end_CpilotZ, 0x107455A0
.global CredmanZ
.set CredmanZ, 0x107455A0
.global end_CredmanZ
.set end_CredmanZ, 0x10747CD0
.global CrusguardZ
.set CrusguardZ, 0x10747CD0
.global end_CrusguardZ
.set end_CrusguardZ, 0x10749900
.global CsnowbondZ
.set CsnowbondZ, 0x10749900
.global end_CsnowbondZ
.set end_CsnowbondZ, 0x1074CC30
.global CsnowguardZ
.set CsnowguardZ, 0x1074CC30
.global end_CsnowguardZ
.set end_CsnowguardZ, 0x1074F8B0
.global CspicebondZ
.set CspicebondZ, 0x1074F8B0
.global end_CspicebondZ
.set end_CspicebondZ, 0x107531D0
.global Csuit_lf_handZ
.set Csuit_lf_handZ, 0x107531D0
.global end_Csuit_lf_handZ
.set end_Csuit_lf_handZ, 0x107563F0
.global CsuitbondZ
.set CsuitbondZ, 0x107563F0
.global end_CsuitbondZ
.set end_CsuitbondZ, 0x10759180
.global CtechmanZ
.set CtechmanZ, 0x10759180
.global end_CtechmanZ
.set end_CtechmanZ, 0x1075B830
.global CtechwomanZ
.set CtechwomanZ, 0x1075B830
.global end_CtechwomanZ
.set end_CtechwomanZ, 0x1075D820
.global CtimberbondZ
.set CtimberbondZ, 0x1075D820
.global end_CtimberbondZ
.set end_CtimberbondZ, 0x10760550
.global CtrevelyanZ
.set CtrevelyanZ, 0x10760550
.global end_CtrevelyanZ
.set end_CtrevelyanZ, 0x10763D20
.global CtrevguardZ
.set CtrevguardZ, 0x10763D20
.global end_CtrevguardZ
.set end_CtrevguardZ, 0x10766330
.global CvalentinZ
.set CvalentinZ, 0x10766330
.global end_CvalentinZ
.set end_CvalentinZ, 0x107692A0
.global CxeniaZ
.set CxeniaZ, 0x107692A0
.global end_CxeniaZ
.set end_CxeniaZ, 0x1076CC90
.global Gak47Z
.set Gak47Z, 0x1076CC90
.global end_Gak47Z
.set end_Gak47Z, 0x1076D6A0
.global GaudiotapeZ
.set GaudiotapeZ, 0x1076D6A0
.global end_GaudiotapeZ
.set end_GaudiotapeZ, 0x1076DA30
.global GautoshotZ
.set GautoshotZ, 0x1076DA30
.global end_GautoshotZ
.set end_GautoshotZ, 0x1076F240
.global GblackboxZ
.set GblackboxZ, 0x1076F240
.global end_GblackboxZ
.set end_GblackboxZ, 0x1076F840
.global GblueprintsZ
.set GblueprintsZ, 0x1076F840
.global end_GblueprintsZ
.set end_GblueprintsZ, 0x1076F940
.global GbombcaseZ
.set GbombcaseZ, 0x1076F940
.global end_GbombcaseZ
.set end_GbombcaseZ, 0x107700D0
.global GbombdefuserZ
.set GbombdefuserZ, 0x107700D0
.global end_GbombdefuserZ
.set end_GbombdefuserZ, 0x107706C0
.global GbriefcaseZ
.set GbriefcaseZ, 0x107706C0
.global end_GbriefcaseZ
.set end_GbriefcaseZ, 0x10770E50
.global GbugZ
.set GbugZ, 0x10770E50
.global end_GbugZ
.set end_GbugZ, 0x107717C0
.global GbugdetectorZ
.set GbugdetectorZ, 0x107717C0
.global end_GbugdetectorZ
.set end_GbugdetectorZ, 0x10771B10
.global GbungeeZ
.set GbungeeZ, 0x10771B10
.global end_GbungeeZ
.set end_GbungeeZ, 0x10771E60
.global GcameraZ
.set GcameraZ, 0x10771E60
.global end_GcameraZ
.set end_GcameraZ, 0x107722E0
.global GcartblueZ
.set GcartblueZ, 0x107722E0
.global end_GcartblueZ
.set end_GcartblueZ, 0x10772540
.global GcartridgeZ
.set GcartridgeZ, 0x10772540
.global end_GcartridgeZ
.set end_GcartridgeZ, 0x10772670
.global GcartrifleZ
.set GcartrifleZ, 0x10772670
.global end_GcartrifleZ
.set end_GcartrifleZ, 0x10772880
.global GcartshellZ
.set GcartshellZ, 0x10772880
.global end_GcartshellZ
.set end_GcartshellZ, 0x10772A80
.global GcircuitboardZ
.set GcircuitboardZ, 0x10772A80
.global end_GcircuitboardZ
.set end_GcircuitboardZ, 0x10772BC0
.global GclipboardZ
.set GclipboardZ, 0x10772BC0
.global end_GclipboardZ
.set end_GclipboardZ, 0x10772DB0
.global GcreditcardZ
.set GcreditcardZ, 0x10772DB0
.global end_GcreditcardZ
.set end_GcreditcardZ, 0x10773100
.global GdarkglassesZ
.set GdarkglassesZ, 0x10773100
.global end_GdarkglassesZ
.set end_GdarkglassesZ, 0x10773450
.global GdatathiefZ
.set GdatathiefZ, 0x10773450
.global end_GdatathiefZ
.set end_GdatathiefZ, 0x10773590
.global GdattapeZ
.set GdattapeZ, 0x10773590
.global end_GdattapeZ
.set end_GdattapeZ, 0x10773700
.global GdoordecoderZ
.set GdoordecoderZ, 0x10773700
.global end_GdoordecoderZ
.set end_GdoordecoderZ, 0x10773C80
.global GdoorexploderZ
.set GdoorexploderZ, 0x10773C80
.global end_GdoorexploderZ
.set end_GdoorexploderZ, 0x10773FD0
.global GdossierredZ
.set GdossierredZ, 0x10773FD0
.global end_GdossierredZ
.set end_GdossierredZ, 0x10774330
.global GdynamiteZ
.set GdynamiteZ, 0x10774330
.global end_GdynamiteZ
.set end_GdynamiteZ, 0x10774680
.global GexplosivefloppyZ
.set GexplosivefloppyZ, 0x10774680
.global end_GexplosivefloppyZ
.set end_GexplosivefloppyZ, 0x107748D0
.global GexplosivepenZ
.set GexplosivepenZ, 0x107748D0
.global end_GexplosivepenZ
.set end_GexplosivepenZ, 0x10774C20
.global GextinguisherZ
.set GextinguisherZ, 0x10774C20
.global end_GextinguisherZ
.set end_GextinguisherZ, 0x10775410
.global GfingergunZ
.set GfingergunZ, 0x10775410
.global end_GfingergunZ
.set end_GfingergunZ, 0x10775760
.global GfistZ
.set GfistZ, 0x10775760
.global end_GfistZ
.set end_GfistZ, 0x10776E60
.global GflarepistolZ
.set GflarepistolZ, 0x10776E60
.global end_GflarepistolZ
.set end_GflarepistolZ, 0x107771B0
.global Gfnp90Z
.set Gfnp90Z, 0x107771B0
.global end_Gfnp90Z
.set end_Gfnp90Z, 0x10777E50
.global GgaskeyringZ
.set GgaskeyringZ, 0x10777E50
.global end_GgaskeyringZ
.set end_GgaskeyringZ, 0x10778880
.global GgoldbarZ
.set GgoldbarZ, 0x10778880
.global end_GgoldbarZ
.set end_GgoldbarZ, 0x10778BD0
.global GgoldeneyekeyZ
.set GgoldeneyekeyZ, 0x10778BD0
.global end_GgoldeneyekeyZ
.set end_GgoldeneyekeyZ, 0x10779580
.global GgoldengunZ
.set GgoldengunZ, 0x10779580
.global end_GgoldengunZ
.set end_GgoldengunZ, 0x1077AD60
.global GgoldwppkZ
.set GgoldwppkZ, 0x1077AD60
.global end_GgoldwppkZ
.set end_GgoldwppkZ, 0x1077C6C0
.global GgrenadeZ
.set GgrenadeZ, 0x1077C6C0
.global end_GgrenadeZ
.set end_GgrenadeZ, 0x1077D0F0
.global GgrenadelaunchZ
.set GgrenadelaunchZ, 0x1077D0F0
.global end_GgrenadelaunchZ
.set end_GgrenadelaunchZ, 0x1077E170
.global GheroinZ
.set GheroinZ, 0x1077E170
.global end_GheroinZ
.set end_GheroinZ, 0x1077E4C0
.global GjoypadZ
.set GjoypadZ, 0x1077E4C0
.global end_GjoypadZ
.set end_GjoypadZ, 0x10780370
.global GkeyanalysercaseZ
.set GkeyanalysercaseZ, 0x10780370
.global end_GkeyanalysercaseZ
.set end_GkeyanalysercaseZ, 0x10780B00
.global GkeyboltZ
.set GkeyboltZ, 0x10780B00
.global end_GkeyboltZ
.set end_GkeyboltZ, 0x107814F0
.global GkeycardZ
.set GkeycardZ, 0x107814F0
.global end_GkeycardZ
.set end_GkeycardZ, 0x10781620
.global GkeyyaleZ
.set GkeyyaleZ, 0x10781620
.global end_GkeyyaleZ
.set end_GkeyyaleZ, 0x10782370
.global GknifeZ
.set GknifeZ, 0x10782370
.global end_GknifeZ
.set end_GknifeZ, 0x10783E40
.global GlaserZ
.set GlaserZ, 0x10783E40
.global end_GlaserZ
.set end_GlaserZ, 0x10784C30
.global GlectreZ
.set GlectreZ, 0x10784C30
.global end_GlectreZ
.set end_GlectreZ, 0x10784F80
.global GlockexploderZ
.set GlockexploderZ, 0x10784F80
.global end_GlockexploderZ
.set end_GlockexploderZ, 0x107852D0
.global Gm16Z
.set Gm16Z, 0x107852D0
.global end_Gm16Z
.set end_Gm16Z, 0x10785CF0
.global GmapZ
.set GmapZ, 0x10785CF0
.global end_GmapZ
.set end_GmapZ, 0x10785DE0
.global GmicrocameraZ
.set GmicrocameraZ, 0x10785DE0
.global end_GmicrocameraZ
.set end_GmicrocameraZ, 0x10786420
.global GmicrocodeZ
.set GmicrocodeZ, 0x10786420
.global end_GmicrocodeZ
.set end_GmicrocodeZ, 0x10786770
.global GmicrofilmZ
.set GmicrofilmZ, 0x10786770
.global end_GmicrofilmZ
.set end_GmicrofilmZ, 0x10786AC0
.global GmoneyZ
.set GmoneyZ, 0x10786AC0
.global end_GmoneyZ
.set end_GmoneyZ, 0x10786E10
.global Gmp5kZ
.set Gmp5kZ, 0x10786E10
.global end_Gmp5kZ
.set end_Gmp5kZ, 0x107879F0
.global Gmp5ksilZ
.set Gmp5ksilZ, 0x107879F0
.global end_Gmp5ksilZ
.set end_Gmp5ksilZ, 0x107886F0
.global GpitongunZ
.set GpitongunZ, 0x107886F0
.global end_GpitongunZ
.set end_GpitongunZ, 0x10788A40
.global GplansZ
.set GplansZ, 0x10788A40
.global end_GplansZ
.set end_GplansZ, 0x10788C10
.global GplastiqueZ
.set GplastiqueZ, 0x10788C10
.global end_GplastiqueZ
.set end_GplastiqueZ, 0x10788F60
.global GpolarizedglassesZ
.set GpolarizedglassesZ, 0x10788F60
.global end_GpolarizedglassesZ
.set end_GpolarizedglassesZ, 0x107894C0
.global GproximitymineZ
.set GproximitymineZ, 0x107894C0
.global end_GproximitymineZ
.set end_GproximitymineZ, 0x10789CB0
.global GremotemineZ
.set GremotemineZ, 0x10789CB0
.global end_GremotemineZ
.set end_GremotemineZ, 0x1078A670
.global GrocketlaunchZ
.set GrocketlaunchZ, 0x1078A670
.global end_GrocketlaunchZ
.set end_GrocketlaunchZ, 0x1078B890
.global GrugerZ
.set GrugerZ, 0x1078B890
.global end_GrugerZ
.set end_GrugerZ, 0x1078D620
.global GsafecrackercaseZ
.set GsafecrackercaseZ, 0x1078D620
.global end_GsafecrackercaseZ
.set end_GsafecrackercaseZ, 0x1078DDB0
.global GshotgunZ
.set GshotgunZ, 0x1078DDB0
.global end_GshotgunZ
.set end_GshotgunZ, 0x1078EC90
.global GsilverwppkZ
.set GsilverwppkZ, 0x1078EC90
.global end_GsilverwppkZ
.set end_GsilverwppkZ, 0x107905F0
.global GskorpionZ
.set GskorpionZ, 0x107905F0
.global end_GskorpionZ
.set end_GskorpionZ, 0x107917F0
.global GsniperrifleZ
.set GsniperrifleZ, 0x107917F0
.global end_GsniperrifleZ
.set end_GsniperrifleZ, 0x10792860
.global GspectreZ
.set GspectreZ, 0x10792860
.global end_GspectreZ
.set end_GspectreZ, 0x107934E0
.global GspooltapeZ
.set GspooltapeZ, 0x107934E0
.global end_GspooltapeZ
.set end_GspooltapeZ, 0x10793830
.global GspyfileZ
.set GspyfileZ, 0x10793830
.global end_GspyfileZ
.set end_GspyfileZ, 0x10793B80
.global GstafflistZ
.set GstafflistZ, 0x10793B80
.global end_GstafflistZ
.set end_GstafflistZ, 0x10793D20
.global GtaserZ
.set GtaserZ, 0x10793D20
.global end_GtaserZ
.set end_GtaserZ, 0x10795B80
.global GthrowknifeZ
.set GthrowknifeZ, 0x10795B80
.global end_GthrowknifeZ
.set end_GthrowknifeZ, 0x10797670
.global GtimedmineZ
.set GtimedmineZ, 0x10797670
.global end_GtimedmineZ
.set end_GtimedmineZ, 0x10798130
.global GtriggerZ
.set GtriggerZ, 0x10798130
.global end_GtriggerZ
.set end_GtriggerZ, 0x1079B530
.global Gtt33Z
.set Gtt33Z, 0x1079B530
.global end_Gtt33Z
.set end_Gtt33Z, 0x1079D050
.global GuziZ
.set GuziZ, 0x1079D050
.global end_GuziZ
.set end_GuziZ, 0x1079D960
.global GvideotapeZ
.set GvideotapeZ, 0x1079D960
.global end_GvideotapeZ
.set end_GvideotapeZ, 0x1079DB70
.global GwatchcommunicatorZ
.set GwatchcommunicatorZ, 0x1079DB70
.global end_GwatchcommunicatorZ
.set end_GwatchcommunicatorZ, 0x1079EFD0
.global GwatchgeigercounterZ
.set GwatchgeigercounterZ, 0x1079EFD0
.global end_GwatchgeigercounterZ
.set end_GwatchgeigercounterZ, 0x107A0430
.global GwatchidentifierZ
.set GwatchidentifierZ, 0x107A0430
.global end_GwatchidentifierZ
.set end_GwatchidentifierZ, 0x107A1890
.global GwatchlaserZ
.set GwatchlaserZ, 0x107A1890
.global end_GwatchlaserZ
.set end_GwatchlaserZ, 0x107A4C90
.global GwatchmagnetattractZ
.set GwatchmagnetattractZ, 0x107A4C90
.global end_GwatchmagnetattractZ
.set end_GwatchmagnetattractZ, 0x107A60E0
.global GwatchmagnetrepelZ
.set GwatchmagnetrepelZ, 0x107A60E0
.global end_GwatchmagnetrepelZ
.set end_GwatchmagnetrepelZ, 0x107A7540
.global GweaponcaseZ
.set GweaponcaseZ, 0x107A7540
.global end_GweaponcaseZ
.set end_GweaponcaseZ, 0x107A7CD0
.global GwppkZ
.set GwppkZ, 0x107A7CD0
.global end_GwppkZ
.set end_GwppkZ, 0x107A9960
.global GwppksilZ
.set GwppksilZ, 0x107A9960
.global end_GwppksilZ
.set end_GwppksilZ, 0x107AB6A0
.global GwristdartZ
.set GwristdartZ, 0x107AB6A0
.global end_GwristdartZ
.set end_GwristdartZ, 0x107AB9F0
.global PICBMZ
.set PICBMZ, 0x107AB9F0
.global end_PICBMZ
.set end_PICBMZ, 0x107ADF70
.global PICBM_noseZ
.set PICBM_noseZ, 0x107ADF70
.global end_PICBM_noseZ
.set end_PICBM_noseZ, 0x107AE720
.global Pak47magZ
.set Pak47magZ, 0x107AE720
.global end_Pak47magZ
.set end_Pak47magZ, 0x107AE900
.global Palarm1Z
.set Palarm1Z, 0x107AE900
.global end_Palarm1Z
.set end_Palarm1Z, 0x107AEA60
.global Palarm2Z
.set Palarm2Z, 0x107AEA60
.global end_Palarm2Z
.set end_Palarm2Z, 0x107AEC00
.global Pammo_crate1Z
.set Pammo_crate1Z, 0x107AEC00
.global end_Pammo_crate1Z
.set end_Pammo_crate1Z, 0x107AEE40
.global Pammo_crate2Z
.set Pammo_crate2Z, 0x107AEE40
.global end_Pammo_crate2Z
.set end_Pammo_crate2Z, 0x107AF080
.global Pammo_crate3Z
.set Pammo_crate3Z, 0x107AF080
.global end_Pammo_crate3Z
.set end_Pammo_crate3Z, 0x107AF2D0
.global Pammo_crate4Z
.set Pammo_crate4Z, 0x107AF2D0
.global end_Pammo_crate4Z
.set end_Pammo_crate4Z, 0x107AF540
.global Pammo_crate5Z
.set Pammo_crate5Z, 0x107AF540
.global end_Pammo_crate5Z
.set end_Pammo_crate5Z, 0x107AF800
.global PapcZ
.set PapcZ, 0x107AF800
.global end_PapcZ
.set end_PapcZ, 0x107B1460
.global Parchsecdoor1Z
.set Parchsecdoor1Z, 0x107B1460
.global end_Parchsecdoor1Z
.set end_Parchsecdoor1Z, 0x107B1640
.global Parchsecdoor2Z
.set Parchsecdoor2Z, 0x107B1640
.global end_Parchsecdoor2Z
.set end_Parchsecdoor2Z, 0x107B1810
.global ParticZ
.set ParticZ, 0x107B1810
.global end_ParticZ
.set end_ParticZ, 0x107B2610
.global PartictrailerZ
.set PartictrailerZ, 0x107B2610
.global end_PartictrailerZ
.set end_PartictrailerZ, 0x107B2F20
.global PbarricadeZ
.set PbarricadeZ, 0x107B2F20
.global end_PbarricadeZ
.set end_PbarricadeZ, 0x107B3160
.global Pbin1Z
.set Pbin1Z, 0x107B3160
.global end_Pbin1Z
.set end_Pbin1Z, 0x107B34B0
.global Pblotter1Z
.set Pblotter1Z, 0x107B34B0
.global end_Pblotter1Z
.set end_Pblotter1Z, 0x107B3590
.global PbodyarmourZ
.set PbodyarmourZ, 0x107B3590
.global end_PbodyarmourZ
.set end_PbodyarmourZ, 0x107B3A30
.global PbodyarmourvestZ
.set PbodyarmourvestZ, 0x107B3A30
.global end_PbodyarmourvestZ
.set end_PbodyarmourvestZ, 0x107B3E50
.global PbollardZ
.set PbollardZ, 0x107B3E50
.global end_PbollardZ
.set end_PbollardZ, 0x107B4050
.global PbombZ
.set PbombZ, 0x107B4050
.global end_PbombZ
.set end_PbombZ, 0x107B41C0
.global Pbook1Z
.set Pbook1Z, 0x107B41C0
.global end_Pbook1Z
.set end_Pbook1Z, 0x107B4350
.global Pbookshelf1Z
.set Pbookshelf1Z, 0x107B4350
.global end_Pbookshelf1Z
.set end_Pbookshelf1Z, 0x107B4A40
.global Pborg_crateZ
.set Pborg_crateZ, 0x107B4A40
.global end_Pborg_crateZ
.set end_Pborg_crateZ, 0x107B4BB0
.global PboxcartridgesZ
.set PboxcartridgesZ, 0x107B4BB0
.global end_PboxcartridgesZ
.set end_PboxcartridgesZ, 0x107B4DB0
.global Pboxes2x4Z
.set Pboxes2x4Z, 0x107B4DB0
.global end_Pboxes2x4Z
.set end_Pboxes2x4Z, 0x107B51E0
.global Pboxes3x4Z
.set Pboxes3x4Z, 0x107B51E0
.global end_Pboxes3x4Z
.set end_Pboxes3x4Z, 0x107B5620
.global Pboxes4x4Z
.set Pboxes4x4Z, 0x107B5620
.global end_Pboxes4x4Z
.set end_Pboxes4x4Z, 0x107B5C80
.global PbrakeunitZ
.set PbrakeunitZ, 0x107B5C80
.global end_PbrakeunitZ
.set end_PbrakeunitZ, 0x107B5FF0
.global Pbridge_console1aZ
.set Pbridge_console1aZ, 0x107B5FF0
.global end_Pbridge_console1aZ
.set end_Pbridge_console1aZ, 0x107B6570
.global Pbridge_console1bZ
.set Pbridge_console1bZ, 0x107B6570
.global end_Pbridge_console1bZ
.set end_Pbridge_console1bZ, 0x107B6AD0
.global Pbridge_console2aZ
.set Pbridge_console2aZ, 0x107B6AD0
.global end_Pbridge_console2aZ
.set end_Pbridge_console2aZ, 0x107B7050
.global Pbridge_console2bZ
.set Pbridge_console2bZ, 0x107B7050
.global end_Pbridge_console2bZ
.set end_Pbridge_console2bZ, 0x107B7540
.global Pbridge_console3aZ
.set Pbridge_console3aZ, 0x107B7540
.global end_Pbridge_console3aZ
.set end_Pbridge_console3aZ, 0x107B7A90
.global Pbridge_console3bZ
.set Pbridge_console3bZ, 0x107B7A90
.global end_Pbridge_console3bZ
.set end_Pbridge_console3bZ, 0x107B8020
.global PcarbmwZ
.set PcarbmwZ, 0x107B8020
.global end_PcarbmwZ
.set end_PcarbmwZ, 0x107B8D00
.global Pcard_box1Z
.set Pcard_box1Z, 0x107B8D00
.global end_Pcard_box1Z
.set end_Pcard_box1Z, 0x107B8F00
.global Pcard_box2Z
.set Pcard_box2Z, 0x107B8F00
.global end_Pcard_box2Z
.set end_Pcard_box2Z, 0x107B9140
.global Pcard_box3Z
.set Pcard_box3Z, 0x107B9140
.global end_Pcard_box3Z
.set end_Pcard_box3Z, 0x107B9330
.global Pcard_box4_lgZ
.set Pcard_box4_lgZ, 0x107B9330
.global end_Pcard_box4_lgZ
.set end_Pcard_box4_lgZ, 0x107B94E0
.global Pcard_box5_lgZ
.set Pcard_box5_lgZ, 0x107B94E0
.global end_Pcard_box5_lgZ
.set end_Pcard_box5_lgZ, 0x107B96E0
.global Pcard_box6_lgZ
.set Pcard_box6_lgZ, 0x107B96E0
.global end_Pcard_box6_lgZ
.set end_Pcard_box6_lgZ, 0x107B98D0
.global PcarescortZ
.set PcarescortZ, 0x107B98D0
.global end_PcarescortZ
.set end_PcarescortZ, 0x107BA4D0
.global PcargolfZ
.set PcargolfZ, 0x107BA4D0
.global end_PcargolfZ
.set end_PcargolfZ, 0x107BB100
.global PcarweirdZ
.set PcarweirdZ, 0x107BB100
.global end_PcarweirdZ
.set end_PcarweirdZ, 0x107BC240
.global PcarzilZ
.set PcarzilZ, 0x107BC240
.global end_PcarzilZ
.set end_PcarzilZ, 0x107BD840
.global PcctvZ
.set PcctvZ, 0x107BD840
.global end_PcctvZ
.set end_PcctvZ, 0x107BDBC0
.global PchraudiotapeZ
.set PchraudiotapeZ, 0x107BDBC0
.global end_PchraudiotapeZ
.set end_PchraudiotapeZ, 0x107BE120
.global PchrautoshotZ
.set PchrautoshotZ, 0x107BE120
.global end_PchrautoshotZ
.set end_PchrautoshotZ, 0x107BE480
.global PchrblackboxZ
.set PchrblackboxZ, 0x107BE480
.global end_PchrblackboxZ
.set end_PchrblackboxZ, 0x107BED00
.global PchrblueprintsZ
.set PchrblueprintsZ, 0x107BED00
.global end_PchrblueprintsZ
.set end_PchrblueprintsZ, 0x107BEE50
.global PchrbombcaseZ
.set PchrbombcaseZ, 0x107BEE50
.global end_PchrbombcaseZ
.set end_PchrbombcaseZ, 0x107BF040
.global PchrbombdefuserZ
.set PchrbombdefuserZ, 0x107BF040
.global end_PchrbombdefuserZ
.set end_PchrbombdefuserZ, 0x107BF920
.global PchrbriefcaseZ
.set PchrbriefcaseZ, 0x107BF920
.global end_PchrbriefcaseZ
.set end_PchrbriefcaseZ, 0x107BFAB0
.global PchrbugZ
.set PchrbugZ, 0x107BFAB0
.global end_PchrbugZ
.set end_PchrbugZ, 0x107C0860
.global PchrbugdetectorZ
.set PchrbugdetectorZ, 0x107C0860
.global end_PchrbugdetectorZ
.set end_PchrbugdetectorZ, 0x107C09D0
.global PchrbungeeZ
.set PchrbungeeZ, 0x107C09D0
.global end_PchrbungeeZ
.set end_PchrbungeeZ, 0x107C0B40
.global PchrcameraZ
.set PchrcameraZ, 0x107C0B40
.global end_PchrcameraZ
.set end_PchrcameraZ, 0x107C11D0
.global PchrcircuitboardZ
.set PchrcircuitboardZ, 0x107C11D0
.global end_PchrcircuitboardZ
.set end_PchrcircuitboardZ, 0x107C1370
.global PchrclipboardZ
.set PchrclipboardZ, 0x107C1370
.global end_PchrclipboardZ
.set end_PchrclipboardZ, 0x107C15F0
.global PchrcreditcardZ
.set PchrcreditcardZ, 0x107C15F0
.global end_PchrcreditcardZ
.set end_PchrcreditcardZ, 0x107C1760
.global PchrdarkglassesZ
.set PchrdarkglassesZ, 0x107C1760
.global end_PchrdarkglassesZ
.set end_PchrdarkglassesZ, 0x107C18D0
.global PchrdatathiefZ
.set PchrdatathiefZ, 0x107C18D0
.global end_PchrdatathiefZ
.set end_PchrdatathiefZ, 0x107C1A70
.global PchrdattapeZ
.set PchrdattapeZ, 0x107C1A70
.global end_PchrdattapeZ
.set end_PchrdattapeZ, 0x107C1C60
.global PchrdoordecoderZ
.set PchrdoordecoderZ, 0x107C1C60
.global end_PchrdoordecoderZ
.set end_PchrdoordecoderZ, 0x107C24C0
.global PchrdoorexploderZ
.set PchrdoorexploderZ, 0x107C24C0
.global end_PchrdoorexploderZ
.set end_PchrdoorexploderZ, 0x107C2630
.global PchrdossierredZ
.set PchrdossierredZ, 0x107C2630
.global end_PchrdossierredZ
.set end_PchrdossierredZ, 0x107C2B00
.global PchrdynamiteZ
.set PchrdynamiteZ, 0x107C2B00
.global end_PchrdynamiteZ
.set end_PchrdynamiteZ, 0x107C2C70
.global PchrexplosivepenZ
.set PchrexplosivepenZ, 0x107C2C70
.global end_PchrexplosivepenZ
.set end_PchrexplosivepenZ, 0x107C2DE0
.global PchrextinguisherZ
.set PchrextinguisherZ, 0x107C2DE0
.global end_PchrextinguisherZ
.set end_PchrextinguisherZ, 0x107C32E0
.global PchrfingergunZ
.set PchrfingergunZ, 0x107C32E0
.global end_PchrfingergunZ
.set end_PchrfingergunZ, 0x107C3450
.global PchrflarepistolZ
.set PchrflarepistolZ, 0x107C3450
.global end_PchrflarepistolZ
.set end_PchrflarepistolZ, 0x107C35C0
.global Pchrfnp90Z
.set Pchrfnp90Z, 0x107C35C0
.global end_Pchrfnp90Z
.set end_Pchrfnp90Z, 0x107C3A20
.global PchrgaskeyringZ
.set PchrgaskeyringZ, 0x107C3A20
.global end_PchrgaskeyringZ
.set end_PchrgaskeyringZ, 0x107C4930
.global PchrgoldbarZ
.set PchrgoldbarZ, 0x107C4930
.global end_PchrgoldbarZ
.set end_PchrgoldbarZ, 0x107C4AA0
.global PchrgoldenZ
.set PchrgoldenZ, 0x107C4AA0
.global end_PchrgoldenZ
.set end_PchrgoldenZ, 0x107C4D10
.global PchrgoldeneyekeyZ
.set PchrgoldeneyekeyZ, 0x107C4D10
.global end_PchrgoldeneyekeyZ
.set end_PchrgoldeneyekeyZ, 0x107C5BB0
.global PchrgoldwppkZ
.set PchrgoldwppkZ, 0x107C5BB0
.global end_PchrgoldwppkZ
.set end_PchrgoldwppkZ, 0x107C5D20
.global PchrgrenadeZ
.set PchrgrenadeZ, 0x107C5D20
.global end_PchrgrenadeZ
.set end_PchrgrenadeZ, 0x107C6090
.global PchrgrenadelaunchZ
.set PchrgrenadelaunchZ, 0x107C6090
.global end_PchrgrenadelaunchZ
.set end_PchrgrenadelaunchZ, 0x107C6420
.global PchrgrenaderoundZ
.set PchrgrenaderoundZ, 0x107C6420
.global end_PchrgrenaderoundZ
.set end_PchrgrenaderoundZ, 0x107C6690
.global PchrheroinZ
.set PchrheroinZ, 0x107C6690
.global end_PchrheroinZ
.set end_PchrheroinZ, 0x107C6800
.global PchrkalashZ
.set PchrkalashZ, 0x107C6800
.global end_PchrkalashZ
.set end_PchrkalashZ, 0x107C6BF0
.global PchrkeyanalysercaseZ
.set PchrkeyanalysercaseZ, 0x107C6BF0
.global end_PchrkeyanalysercaseZ
.set end_PchrkeyanalysercaseZ, 0x107C6DE0
.global PchrkeyboltZ
.set PchrkeyboltZ, 0x107C6DE0
.global end_PchrkeyboltZ
.set end_PchrkeyboltZ, 0x107C7C80
.global PchrkeyyaleZ
.set PchrkeyyaleZ, 0x107C7C80
.global end_PchrkeyyaleZ
.set end_PchrkeyyaleZ, 0x107C90E0
.global PchrknifeZ
.set PchrknifeZ, 0x107C90E0
.global end_PchrknifeZ
.set end_PchrknifeZ, 0x107C92E0
.global PchrlaserZ
.set PchrlaserZ, 0x107C92E0
.global end_PchrlaserZ
.set end_PchrlaserZ, 0x107C96A0
.global PchrlectreZ
.set PchrlectreZ, 0x107C96A0
.global end_PchrlectreZ
.set end_PchrlectreZ, 0x107C9810
.global PchrlockexploderZ
.set PchrlockexploderZ, 0x107C9810
.global end_PchrlockexploderZ
.set end_PchrlockexploderZ, 0x107C9980
.global Pchrm16Z
.set Pchrm16Z, 0x107C9980
.global end_Pchrm16Z
.set end_Pchrm16Z, 0x107C9D50
.global PchrmapZ
.set PchrmapZ, 0x107C9D50
.global end_PchrmapZ
.set end_PchrmapZ, 0x107C9EA0
.global PchrmicrocameraZ
.set PchrmicrocameraZ, 0x107C9EA0
.global end_PchrmicrocameraZ
.set end_PchrmicrocameraZ, 0x107CA790
.global PchrmicrocodeZ
.set PchrmicrocodeZ, 0x107CA790
.global end_PchrmicrocodeZ
.set end_PchrmicrocodeZ, 0x107CA900
.global PchrmicrofilmZ
.set PchrmicrofilmZ, 0x107CA900
.global end_PchrmicrofilmZ
.set end_PchrmicrofilmZ, 0x107CAA70
.global PchrmoneyZ
.set PchrmoneyZ, 0x107CAA70
.global end_PchrmoneyZ
.set end_PchrmoneyZ, 0x107CABE0
.global Pchrmp5kZ
.set Pchrmp5kZ, 0x107CABE0
.global end_Pchrmp5kZ
.set end_Pchrmp5kZ, 0x107CAF60
.global Pchrmp5ksilZ
.set Pchrmp5ksilZ, 0x107CAF60
.global end_Pchrmp5ksilZ
.set end_Pchrmp5ksilZ, 0x107CB370
.global PchrpitongunZ
.set PchrpitongunZ, 0x107CB370
.global end_PchrpitongunZ
.set end_PchrpitongunZ, 0x107CB4E0
.global PchrplansZ
.set PchrplansZ, 0x107CB4E0
.global end_PchrplansZ
.set end_PchrplansZ, 0x107CB770
.global PchrplastiqueZ
.set PchrplastiqueZ, 0x107CB770
.global end_PchrplastiqueZ
.set end_PchrplastiqueZ, 0x107CBBD0
.global PchrpolarizedglassesZ
.set PchrpolarizedglassesZ, 0x107CBBD0
.global end_PchrpolarizedglassesZ
.set end_PchrpolarizedglassesZ, 0x107CC490
.global PchrproximitymineZ
.set PchrproximitymineZ, 0x107CC490
.global end_PchrproximitymineZ
.set end_PchrproximitymineZ, 0x107CC8F0
.global PchrremotemineZ
.set PchrremotemineZ, 0x107CC8F0
.global end_PchrremotemineZ
.set end_PchrremotemineZ, 0x107CCD50
.global PchrrocketZ
.set PchrrocketZ, 0x107CCD50
.global end_PchrrocketZ
.set end_PchrrocketZ, 0x107CD300
.global PchrrocketlaunchZ
.set PchrrocketlaunchZ, 0x107CD300
.global end_PchrrocketlaunchZ
.set end_PchrrocketlaunchZ, 0x107CD6E0
.global PchrrugerZ
.set PchrrugerZ, 0x107CD6E0
.global end_PchrrugerZ
.set end_PchrrugerZ, 0x107CDAC0
.global PchrsafecrackercaseZ
.set PchrsafecrackercaseZ, 0x107CDAC0
.global end_PchrsafecrackercaseZ
.set end_PchrsafecrackercaseZ, 0x107CDCB0
.global PchrshotgunZ
.set PchrshotgunZ, 0x107CDCB0
.global end_PchrshotgunZ
.set end_PchrshotgunZ, 0x107CE000
.global PchrsilverwppkZ
.set PchrsilverwppkZ, 0x107CE000
.global end_PchrsilverwppkZ
.set end_PchrsilverwppkZ, 0x107CE170
.global PchrskorpionZ
.set PchrskorpionZ, 0x107CE170
.global end_PchrskorpionZ
.set end_PchrskorpionZ, 0x107CE4F0
.global PchrsniperrifleZ
.set PchrsniperrifleZ, 0x107CE4F0
.global end_PchrsniperrifleZ
.set end_PchrsniperrifleZ, 0x107CE880
.global PchrspectreZ
.set PchrspectreZ, 0x107CE880
.global end_PchrspectreZ
.set end_PchrspectreZ, 0x107CEBF0
.global PchrspooltapeZ
.set PchrspooltapeZ, 0x107CEBF0
.global end_PchrspooltapeZ
.set end_PchrspooltapeZ, 0x107CED60
.global PchrspyfileZ
.set PchrspyfileZ, 0x107CED60
.global end_PchrspyfileZ
.set end_PchrspyfileZ, 0x107CEED0
.global PchrstafflistZ
.set PchrstafflistZ, 0x107CEED0
.global end_PchrstafflistZ
.set end_PchrstafflistZ, 0x107CF0F0
.global PchrtesttubeZ
.set PchrtesttubeZ, 0x107CF0F0
.global end_PchrtesttubeZ
.set end_PchrtesttubeZ, 0x107CF2B0
.global PchrthrowknifeZ
.set PchrthrowknifeZ, 0x107CF2B0
.global end_PchrthrowknifeZ
.set end_PchrthrowknifeZ, 0x107CF4D0
.global PchrtimedmineZ
.set PchrtimedmineZ, 0x107CF4D0
.global end_PchrtimedmineZ
.set end_PchrtimedmineZ, 0x107CFA00
.global Pchrtt33Z
.set Pchrtt33Z, 0x107CFA00
.global end_Pchrtt33Z
.set end_Pchrtt33Z, 0x107CFC90
.global PchruziZ
.set PchruziZ, 0x107CFC90
.global end_PchruziZ
.set end_PchruziZ, 0x107CFF60
.global PchrvideotapeZ
.set PchrvideotapeZ, 0x107CFF60
.global end_PchrvideotapeZ
.set end_PchrvideotapeZ, 0x107D0230
.global PchrweaponcaseZ
.set PchrweaponcaseZ, 0x107D0230
.global end_PchrweaponcaseZ
.set end_PchrweaponcaseZ, 0x107D0430
.global PchrwppkZ
.set PchrwppkZ, 0x107D0430
.global end_PchrwppkZ
.set end_PchrwppkZ, 0x107D0670
.global PchrwppksilZ
.set PchrwppksilZ, 0x107D0670
.global end_PchrwppksilZ
.set end_PchrwppksilZ, 0x107D0950
.global PchrwristdartZ
.set PchrwristdartZ, 0x107D0950
.global end_PchrwristdartZ
.set end_PchrwristdartZ, 0x107D0AC0
.global Pconsole1Z
.set Pconsole1Z, 0x107D0AC0
.global end_Pconsole1Z
.set end_Pconsole1Z, 0x107D1140
.global Pconsole2Z
.set Pconsole2Z, 0x107D1140
.global end_Pconsole2Z
.set end_Pconsole2Z, 0x107D17C0
.global Pconsole3Z
.set Pconsole3Z, 0x107D17C0
.global end_Pconsole3Z
.set end_Pconsole3Z, 0x107D1E50
.global Pconsole_sev2aZ
.set Pconsole_sev2aZ, 0x107D1E50
.global end_Pconsole_sev2aZ
.set end_Pconsole_sev2aZ, 0x107D2270
.global Pconsole_sev2bZ
.set Pconsole_sev2bZ, 0x107D2270
.global end_Pconsole_sev2bZ
.set end_Pconsole_sev2bZ, 0x107D2730
.global Pconsole_sev2cZ
.set Pconsole_sev2cZ, 0x107D2730
.global end_Pconsole_sev2cZ
.set end_Pconsole_sev2cZ, 0x107D2B70
.global Pconsole_sev2dZ
.set Pconsole_sev2dZ, 0x107D2B70
.global end_Pconsole_sev2dZ
.set end_Pconsole_sev2dZ, 0x107D2FA0
.global Pconsole_sev_GEaZ
.set Pconsole_sev_GEaZ, 0x107D2FA0
.global end_Pconsole_sev_GEaZ
.set end_Pconsole_sev_GEaZ, 0x107D33D0
.global Pconsole_sev_GEbZ
.set Pconsole_sev_GEbZ, 0x107D33D0
.global end_Pconsole_sev_GEbZ
.set end_Pconsole_sev_GEbZ, 0x107D3800
.global Pconsole_sevaZ
.set Pconsole_sevaZ, 0x107D3800
.global end_Pconsole_sevaZ
.set end_Pconsole_sevaZ, 0x107D3C80
.global Pconsole_sevbZ
.set Pconsole_sevbZ, 0x107D3C80
.global end_Pconsole_sevbZ
.set end_Pconsole_sevbZ, 0x107D40F0
.global Pconsole_sevcZ
.set Pconsole_sevcZ, 0x107D40F0
.global end_Pconsole_sevcZ
.set end_Pconsole_sevcZ, 0x107D4520
.global Pconsole_sevdZ
.set Pconsole_sevdZ, 0x107D4520
.global end_Pconsole_sevdZ
.set end_Pconsole_sevdZ, 0x107D4950
.global Pcryptdoor1aZ
.set Pcryptdoor1aZ, 0x107D4950
.global end_Pcryptdoor1aZ
.set end_Pcryptdoor1aZ, 0x107D4AE0
.global Pcryptdoor1bZ
.set Pcryptdoor1bZ, 0x107D4AE0
.global end_Pcryptdoor1bZ
.set end_Pcryptdoor1bZ, 0x107D4C70
.global Pcryptdoor2aZ
.set Pcryptdoor2aZ, 0x107D4C70
.global end_Pcryptdoor2aZ
.set end_Pcryptdoor2aZ, 0x107D4E00
.global Pcryptdoor2bZ
.set Pcryptdoor2bZ, 0x107D4E00
.global end_Pcryptdoor2bZ
.set end_Pcryptdoor2bZ, 0x107D4F90
.global Pcryptdoor3Z
.set Pcryptdoor3Z, 0x107D4F90
.global end_Pcryptdoor3Z
.set end_Pcryptdoor3Z, 0x107D5200
.global Pcryptdoor4Z
.set Pcryptdoor4Z, 0x107D5200
.global end_Pcryptdoor4Z
.set end_Pcryptdoor4Z, 0x107D5380
.global PdamchaindoorZ
.set PdamchaindoorZ, 0x107D5380
.global end_PdamchaindoorZ
.set end_PdamchaindoorZ, 0x107D5600
.global PdamgatedoorZ
.set PdamgatedoorZ, 0x107D5600
.global end_PdamgatedoorZ
.set end_PdamgatedoorZ, 0x107D5820
.global PdamtundoorZ
.set PdamtundoorZ, 0x107D5820
.global end_PdamtundoorZ
.set end_PdamtundoorZ, 0x107D5B90
.global Pdepot_door_steelZ
.set Pdepot_door_steelZ, 0x107D5B90
.global end_Pdepot_door_steelZ
.set end_Pdepot_door_steelZ, 0x107D5D30
.global Pdepot_gate_entryZ
.set Pdepot_gate_entryZ, 0x107D5D30
.global end_Pdepot_gate_entryZ
.set end_Pdepot_gate_entryZ, 0x107D5F70
.global Pdesk1Z
.set Pdesk1Z, 0x107D5F70
.global end_Pdesk1Z
.set end_Pdesk1Z, 0x107D60F0
.global Pdesk2Z
.set Pdesk2Z, 0x107D60F0
.global end_Pdesk2Z
.set end_Pdesk2Z, 0x107D6270
.global Pdesk_arecibo1Z
.set Pdesk_arecibo1Z, 0x107D6270
.global end_Pdesk_arecibo1Z
.set end_Pdesk_arecibo1Z, 0x107D64B0
.global Pdesk_lamp2Z
.set Pdesk_lamp2Z, 0x107D64B0
.global end_Pdesk_lamp2Z
.set end_Pdesk_lamp2Z, 0x107D67B0
.global Pdest_engineZ
.set Pdest_engineZ, 0x107D67B0
.global end_Pdest_engineZ
.set end_Pdest_engineZ, 0x107D80A0
.global Pdest_exocetZ
.set Pdest_exocetZ, 0x107D80A0
.global end_Pdest_exocetZ
.set end_Pdest_exocetZ, 0x107D8700
.global Pdest_gunZ
.set Pdest_gunZ, 0x107D8700
.global end_Pdest_gunZ
.set end_Pdest_gunZ, 0x107D8D70
.global Pdest_harpoonZ
.set Pdest_harpoonZ, 0x107D8D70
.global end_Pdest_harpoonZ
.set end_Pdest_harpoonZ, 0x107D9610
.global Pdest_seawolfZ
.set Pdest_seawolfZ, 0x107D9610
.global end_Pdest_seawolfZ
.set end_Pdest_seawolfZ, 0x107DA5C0
.global Pdisc_readerZ
.set Pdisc_readerZ, 0x107DA5C0
.global end_Pdisc_readerZ
.set end_Pdisc_readerZ, 0x107DA780
.global Pdisk_drive1Z
.set Pdisk_drive1Z, 0x107DA780
.global end_Pdisk_drive1Z
.set end_Pdisk_drive1Z, 0x107DA910
.global Pdoor_azt_chairZ
.set Pdoor_azt_chairZ, 0x107DA910
.global end_Pdoor_azt_chairZ
.set end_Pdoor_azt_chairZ, 0x107DAA90
.global Pdoor_azt_deskZ
.set Pdoor_azt_deskZ, 0x107DAA90
.global end_Pdoor_azt_deskZ
.set end_Pdoor_azt_deskZ, 0x107DAED0
.global Pdoor_azt_desk_topZ
.set Pdoor_azt_desk_topZ, 0x107DAED0
.global end_Pdoor_azt_desk_topZ
.set end_Pdoor_azt_desk_topZ, 0x107DB260
.global Pdoor_aztecZ
.set Pdoor_aztecZ, 0x107DB260
.global end_Pdoor_aztecZ
.set end_Pdoor_aztecZ, 0x107DB490
.global Pdoor_dest1Z
.set Pdoor_dest1Z, 0x107DB490
.global end_Pdoor_dest1Z
.set end_Pdoor_dest1Z, 0x107DB790
.global Pdoor_dest2Z
.set Pdoor_dest2Z, 0x107DB790
.global end_Pdoor_dest2Z
.set end_Pdoor_dest2Z, 0x107DBB50
.global Pdoor_eyelidZ
.set Pdoor_eyelidZ, 0x107DBB50
.global end_Pdoor_eyelidZ
.set end_Pdoor_eyelidZ, 0x107DC0B0
.global Pdoor_irisZ
.set Pdoor_irisZ, 0x107DC0B0
.global end_Pdoor_irisZ
.set end_Pdoor_irisZ, 0x107DCB00
.global Pdoor_mfZ
.set Pdoor_mfZ, 0x107DCB00
.global end_Pdoor_mfZ
.set end_Pdoor_mfZ, 0x107DCDF0
.global Pdoor_roller1Z
.set Pdoor_roller1Z, 0x107DCDF0
.global end_Pdoor_roller1Z
.set end_Pdoor_roller1Z, 0x107DD160
.global Pdoor_roller2Z
.set Pdoor_roller2Z, 0x107DD160
.global end_Pdoor_roller2Z
.set end_Pdoor_roller2Z, 0x107DD3A0
.global Pdoor_roller3Z
.set Pdoor_roller3Z, 0x107DD3A0
.global end_Pdoor_roller3Z
.set end_Pdoor_roller3Z, 0x107DD5E0
.global Pdoor_roller4Z
.set Pdoor_roller4Z, 0x107DD5E0
.global end_Pdoor_roller4Z
.set end_Pdoor_roller4Z, 0x107DD840
.global Pdoor_rollertrainZ
.set Pdoor_rollertrainZ, 0x107DD840
.global end_Pdoor_rollertrainZ
.set end_Pdoor_rollertrainZ, 0x107DD970
.global Pdoor_st_arec1Z
.set Pdoor_st_arec1Z, 0x107DD970
.global end_Pdoor_st_arec1Z
.set end_Pdoor_st_arec1Z, 0x107DDBD0
.global Pdoor_st_arec2Z
.set Pdoor_st_arec2Z, 0x107DDBD0
.global end_Pdoor_st_arec2Z
.set end_Pdoor_st_arec2Z, 0x107DDEB0
.global Pdoor_winZ
.set Pdoor_winZ, 0x107DDEB0
.global end_Pdoor_winZ
.set end_Pdoor_winZ, 0x107DE050
.global PdoorconsoleZ
.set PdoorconsoleZ, 0x107DE050
.global end_PdoorconsoleZ
.set end_PdoorconsoleZ, 0x107DE4C0
.global PdoorpanelZ
.set PdoorpanelZ, 0x107DE4C0
.global end_PdoorpanelZ
.set end_PdoorpanelZ, 0x107DE830
.global Pdoorprison1Z
.set Pdoorprison1Z, 0x107DE830
.global end_Pdoorprison1Z
.set end_Pdoorprison1Z, 0x107DE980
.global PdoorstatgateZ
.set PdoorstatgateZ, 0x107DE980
.global end_PdoorstatgateZ
.set end_PdoorstatgateZ, 0x107DEB80
.global PexplosionbitZ
.set PexplosionbitZ, 0x107DEB80
.global end_PexplosionbitZ
.set end_PexplosionbitZ, 0x107DECA0
.global Pfiling_cabinet1Z
.set Pfiling_cabinet1Z, 0x107DECA0
.global end_Pfiling_cabinet1Z
.set end_Pfiling_cabinet1Z, 0x107DEE20
.global PflagZ
.set PflagZ, 0x107DEE20
.global end_PflagZ
.set end_PflagZ, 0x107DEF50
.global PfloppyZ
.set PfloppyZ, 0x107DEF50
.global end_PfloppyZ
.set end_PfloppyZ, 0x107DF270
.global Pfnp90magZ
.set Pfnp90magZ, 0x107DF270
.global end_Pfnp90magZ
.set end_Pfnp90magZ, 0x107DF410
.global Pgas_plant_met1_do1Z
.set Pgas_plant_met1_do1Z, 0x107DF410
.global end_Pgas_plant_met1_do1Z
.set end_Pgas_plant_met1_do1Z, 0x107DF790
.global Pgas_plant_sw2_do1Z
.set Pgas_plant_sw2_do1Z, 0x107DF790
.global end_Pgas_plant_sw2_do1Z
.set end_Pgas_plant_sw2_do1Z, 0x107DF970
.global Pgas_plant_sw3_do1Z
.set Pgas_plant_sw3_do1Z, 0x107DF970
.global end_Pgas_plant_sw3_do1Z
.set end_Pgas_plant_sw3_do1Z, 0x107DFB70
.global Pgas_plant_sw4_do1Z
.set Pgas_plant_sw4_do1Z, 0x107DFB70
.global end_Pgas_plant_sw4_do1Z
.set end_Pgas_plant_sw4_do1Z, 0x107DFCD0
.global Pgas_plant_sw_do1Z
.set Pgas_plant_sw_do1Z, 0x107DFCD0
.global end_Pgas_plant_sw_do1Z
.set end_Pgas_plant_sw_do1Z, 0x107DFF60
.global Pgas_plant_wc_cub1Z
.set Pgas_plant_wc_cub1Z, 0x107DFF60
.global end_Pgas_plant_wc_cub1Z
.set end_Pgas_plant_wc_cub1Z, 0x107E0170
.global PgasbarrelZ
.set PgasbarrelZ, 0x107E0170
.global end_PgasbarrelZ
.set end_PgasbarrelZ, 0x107E0380
.global PgasbarrelsZ
.set PgasbarrelsZ, 0x107E0380
.global end_PgasbarrelsZ
.set end_PgasbarrelsZ, 0x107E08C0
.global Pgasplant_clear_doorZ
.set Pgasplant_clear_doorZ, 0x107E08C0
.global end_Pgasplant_clear_doorZ
.set end_Pgasplant_clear_doorZ, 0x107E0E20
.global PgastankZ
.set PgastankZ, 0x107E0E20
.global end_PgastankZ
.set end_PgastankZ, 0x107E13D0
.global Pglassware1Z
.set Pglassware1Z, 0x107E13D0
.global end_Pglassware1Z
.set end_Pglassware1Z, 0x107E1530
.global Pglassware2Z
.set Pglassware2Z, 0x107E1530
.global end_Pglassware2Z
.set end_Pglassware2Z, 0x107E17C0
.global Pglassware3Z
.set Pglassware3Z, 0x107E17C0
.global end_Pglassware3Z
.set end_Pglassware3Z, 0x107E19D0
.global Pglassware4Z
.set Pglassware4Z, 0x107E19D0
.global end_Pglassware4Z
.set end_Pglassware4Z, 0x107E1F50
.global PgoldeneyelogoZ
.set PgoldeneyelogoZ, 0x107E1F50
.global end_PgoldeneyelogoZ
.set end_PgoldeneyelogoZ, 0x107E2E00
.global PgoldenshellsZ
.set PgoldenshellsZ, 0x107E2E00
.global end_PgoldenshellsZ
.set end_PgoldenshellsZ, 0x107E3000
.global PgroundgunZ
.set PgroundgunZ, 0x107E3000
.global end_PgroundgunZ
.set end_PgroundgunZ, 0x107E37D0
.global Pgun_runway1Z
.set Pgun_runway1Z, 0x107E37D0
.global end_Pgun_runway1Z
.set end_Pgun_runway1Z, 0x107E3F10
.global PhatberetZ
.set PhatberetZ, 0x107E3F10
.global end_PhatberetZ
.set end_PhatberetZ, 0x107E41B0
.global PhatberetblueZ
.set PhatberetblueZ, 0x107E41B0
.global end_PhatberetblueZ
.set end_PhatberetblueZ, 0x107E4480
.global PhatberetredZ
.set PhatberetredZ, 0x107E4480
.global end_PhatberetredZ
.set end_PhatberetredZ, 0x107E4760
.global PhatchboltZ
.set PhatchboltZ, 0x107E4760
.global end_PhatchboltZ
.set end_PhatchboltZ, 0x107E4830
.global PhatchdoorZ
.set PhatchdoorZ, 0x107E4830
.global end_PhatchdoorZ
.set end_PhatchdoorZ, 0x107E4A50
.global PhatchsevxZ
.set PhatchsevxZ, 0x107E4A50
.global end_PhatchsevxZ
.set end_PhatchsevxZ, 0x107E4BC0
.global PhatfurryZ
.set PhatfurryZ, 0x107E4BC0
.global end_PhatfurryZ
.set end_PhatfurryZ, 0x107E4DF0
.global PhatfurryblackZ
.set PhatfurryblackZ, 0x107E4DF0
.global end_PhatfurryblackZ
.set end_PhatfurryblackZ, 0x107E5010
.global PhatfurrybrownZ
.set PhatfurrybrownZ, 0x107E5010
.global end_PhatfurrybrownZ
.set end_PhatfurrybrownZ, 0x107E5220
.global PhathelmetZ
.set PhathelmetZ, 0x107E5220
.global end_PhathelmetZ
.set end_PhathelmetZ, 0x107E5450
.global PhathelmetgreyZ
.set PhathelmetgreyZ, 0x107E5450
.global end_PhathelmetgreyZ
.set end_PhathelmetgreyZ, 0x107E5680
.global PhatmoonZ
.set PhatmoonZ, 0x107E5680
.global end_PhatmoonZ
.set end_PhatmoonZ, 0x107E5A60
.global PhatpeakedZ
.set PhatpeakedZ, 0x107E5A60
.global end_PhatpeakedZ
.set end_PhatpeakedZ, 0x107E5D70
.global PhattbirdZ
.set PhattbirdZ, 0x107E5D70
.global end_PhattbirdZ
.set end_PhattbirdZ, 0x107E5FC0
.global PhattbirdbrownZ
.set PhattbirdbrownZ, 0x107E5FC0
.global end_PhattbirdbrownZ
.set end_PhattbirdbrownZ, 0x107E6230
.global PhelicopterZ
.set PhelicopterZ, 0x107E6230
.global end_PhelicopterZ
.set end_PhelicopterZ, 0x107EA450
.global PhindZ
.set PhindZ, 0x107EA450
.global end_PhindZ
.set end_PhindZ, 0x107EBBC0
.global PjeepZ
.set PjeepZ, 0x107EBBC0
.global end_PjeepZ
.set end_PjeepZ, 0x107ECD20
.global Pjerry_can1Z
.set Pjerry_can1Z, 0x107ECD20
.global end_Pjerry_can1Z
.set end_Pjerry_can1Z, 0x107ECF80
.global Pjungle3_treeZ
.set Pjungle3_treeZ, 0x107ECF80
.global end_Pjungle3_treeZ
.set end_Pjungle3_treeZ, 0x107ED700
.global Pjungle5_treeZ
.set Pjungle5_treeZ, 0x107ED700
.global end_Pjungle5_treeZ
.set end_Pjungle5_treeZ, 0x107EDC30
.global Pkey_holderZ
.set Pkey_holderZ, 0x107EDC30
.global end_Pkey_holderZ
.set end_Pkey_holderZ, 0x107EDF80
.global Pkeyboard1Z
.set Pkeyboard1Z, 0x107EDF80
.global end_Pkeyboard1Z
.set end_Pkeyboard1Z, 0x107EE0F0
.global Pkit_units1Z
.set Pkit_units1Z, 0x107EE0F0
.global end_Pkit_units1Z
.set end_Pkit_units1Z, 0x107EE390
.global PlabbenchZ
.set PlabbenchZ, 0x107EE390
.global end_PlabbenchZ
.set end_PlabbenchZ, 0x107EE760
.global PlandmineZ
.set PlandmineZ, 0x107EE760
.global end_PlandmineZ
.set end_PlandmineZ, 0x107EE9D0
.global PlegalpageZ
.set PlegalpageZ, 0x107EE9D0
.global end_PlegalpageZ
.set end_PlegalpageZ, 0x107EF990
.global Pletter_tray1Z
.set Pletter_tray1Z, 0x107EF990
.global end_Pletter_tray1Z
.set end_Pletter_tray1Z, 0x107EFAF0
.global Plocker3Z
.set Plocker3Z, 0x107EFAF0
.global end_Plocker3Z
.set end_Plocker3Z, 0x107EFC80
.global Plocker4Z
.set Plocker4Z, 0x107EFC80
.global end_Plocker4Z
.set end_Plocker4Z, 0x107EFE10
.global Pm16magZ
.set Pm16magZ, 0x107EFE10
.global end_Pm16magZ
.set end_Pm16magZ, 0x107EFF50
.global PmagnumshellsZ
.set PmagnumshellsZ, 0x107EFF50
.global end_PmagnumshellsZ
.set end_PmagnumshellsZ, 0x107F0150
.global Pmainframe1Z
.set Pmainframe1Z, 0x107F0150
.global end_Pmainframe1Z
.set end_Pmainframe1Z, 0x107F0450
.global Pmainframe2Z
.set Pmainframe2Z, 0x107F0450
.global end_Pmainframe2Z
.set end_Pmainframe2Z, 0x107F0720
.global Pmetal_chair1Z
.set Pmetal_chair1Z, 0x107F0720
.global end_Pmetal_chair1Z
.set end_Pmetal_chair1Z, 0x107F0A60
.global Pmetal_crate1Z
.set Pmetal_crate1Z, 0x107F0A60
.global end_Pmetal_crate1Z
.set end_Pmetal_crate1Z, 0x107F0C20
.global Pmetal_crate2Z
.set Pmetal_crate2Z, 0x107F0C20
.global end_Pmetal_crate2Z
.set end_Pmetal_crate2Z, 0x107F0DE0
.global Pmetal_crate3Z
.set Pmetal_crate3Z, 0x107F0DE0
.global end_Pmetal_crate3Z
.set end_Pmetal_crate3Z, 0x107F0FA0
.global Pmetal_crate4Z
.set Pmetal_crate4Z, 0x107F0FA0
.global end_Pmetal_crate4Z
.set end_Pmetal_crate4Z, 0x107F1160
.global PmilcopterZ
.set PmilcopterZ, 0x107F1160
.global end_PmilcopterZ
.set end_PmilcopterZ, 0x107F2A40
.global PmiltruckZ
.set PmiltruckZ, 0x107F2A40
.global end_PmiltruckZ
.set end_PmiltruckZ, 0x107F4D40
.global Pmissile_rack2Z
.set Pmissile_rack2Z, 0x107F4D40
.global end_Pmissile_rack2Z
.set end_Pmissile_rack2Z, 0x107F5750
.global Pmissile_rackZ
.set Pmissile_rackZ, 0x107F5750
.global end_Pmissile_rackZ
.set end_Pmissile_rackZ, 0x107F5B30
.global PmodemboxZ
.set PmodemboxZ, 0x107F5B30
.global end_PmodemboxZ
.set end_PmodemboxZ, 0x107F5E70
.global PmotorbikeZ
.set PmotorbikeZ, 0x107F5E70
.global end_PmotorbikeZ
.set end_PmotorbikeZ, 0x107F6D30
.global Pmp5kmagZ
.set Pmp5kmagZ, 0x107F6D30
.global end_Pmp5kmagZ
.set end_Pmp5kmagZ, 0x107F6E80
.global PnintendologoZ
.set PnintendologoZ, 0x107F6E80
.global end_PnintendologoZ
.set end_PnintendologoZ, 0x107F9960
.global Poil_drum1Z
.set Poil_drum1Z, 0x107F9960
.global end_Poil_drum1Z
.set end_Poil_drum1Z, 0x107F9BD0
.global Poil_drum2Z
.set Poil_drum2Z, 0x107F9BD0
.global end_Poil_drum2Z
.set end_Poil_drum2Z, 0x107F9EC0
.global Poil_drum3Z
.set Poil_drum3Z, 0x107F9EC0
.global end_Poil_drum3Z
.set end_Poil_drum3Z, 0x107FA1B0
.global Poil_drum5Z
.set Poil_drum5Z, 0x107FA1B0
.global end_Poil_drum5Z
.set end_Poil_drum5Z, 0x107FA4A0
.global Poil_drum6Z
.set Poil_drum6Z, 0x107FA4A0
.global end_Poil_drum6Z
.set end_Poil_drum6Z, 0x107FA7B0
.global Poil_drum7Z
.set Poil_drum7Z, 0x107FA7B0
.global end_Poil_drum7Z
.set end_Poil_drum7Z, 0x107FAAB0
.global PpadlockZ
.set PpadlockZ, 0x107FAAB0
.global end_PpadlockZ
.set end_PpadlockZ, 0x107FB500
.global PpalmZ
.set PpalmZ, 0x107FB500
.global end_PpalmZ
.set end_PpalmZ, 0x107FB950
.global PpalmtreeZ
.set PpalmtreeZ, 0x107FB950
.global end_PpalmtreeZ
.set end_PpalmtreeZ, 0x107FBE20
.global Pphone1Z
.set Pphone1Z, 0x107FBE20
.global end_Pphone1Z
.set end_Pphone1Z, 0x107FBF60
.global PplaneZ
.set PplaneZ, 0x107FBF60
.global end_PplaneZ
.set end_PplaneZ, 0x107FE540
.global Pplant11Z
.set Pplant11Z, 0x107FE540
.global end_Pplant11Z
.set end_Pplant11Z, 0x107FE900
.global Pplant1Z
.set Pplant1Z, 0x107FE900
.global end_Pplant1Z
.set end_Pplant1Z, 0x107FEC90
.global Pplant2Z
.set Pplant2Z, 0x107FEC90
.global end_Pplant2Z
.set end_Pplant2Z, 0x107FEFF0
.global Pplant2bZ
.set Pplant2bZ, 0x107FEFF0
.global end_Pplant2bZ
.set end_Pplant2bZ, 0x107FF400
.global Pplant3Z
.set Pplant3Z, 0x107FF400
.global end_Pplant3Z
.set end_Pplant3Z, 0x107FF850
.global Pradio_unit1Z
.set Pradio_unit1Z, 0x107FF850
.global end_Pradio_unit1Z
.set end_Pradio_unit1Z, 0x107FFA00
.global Pradio_unit2Z
.set Pradio_unit2Z, 0x107FFA00
.global end_Pradio_unit2Z
.set end_Pradio_unit2Z, 0x107FFBC0
.global Pradio_unit3Z
.set Pradio_unit3Z, 0x107FFBC0
.global end_Pradio_unit3Z
.set end_Pradio_unit3Z, 0x107FFD80
.global Pradio_unit4Z
.set Pradio_unit4Z, 0x107FFD80
.global end_Pradio_unit4Z
.set end_Pradio_unit4Z, 0x107FFF40
.global ProofgunZ
.set ProofgunZ, 0x107FFF40
.global end_ProofgunZ
.set end_ProofgunZ, 0x108005A0
.global PsafeZ
.set PsafeZ, 0x108005A0
.global end_PsafeZ
.set end_PsafeZ, 0x108008F0
.global PsafedoorZ
.set PsafedoorZ, 0x108008F0
.global end_PsafedoorZ
.set end_PsafedoorZ, 0x10800DE0
.global Psat1_reflectZ
.set Psat1_reflectZ, 0x10800DE0
.global end_Psat1_reflectZ
.set end_Psat1_reflectZ, 0x10802350
.global PsatboxZ
.set PsatboxZ, 0x10802350
.global end_PsatboxZ
.set end_PsatboxZ, 0x10802470
.global PsatdishZ
.set PsatdishZ, 0x10802470
.global end_PsatdishZ
.set end_PsatdishZ, 0x108028D0
.global Psec_panelZ
.set Psec_panelZ, 0x108028D0
.global end_Psec_panelZ
.set end_Psec_panelZ, 0x10802A70
.global Psev_door3Z
.set Psev_door3Z, 0x10802A70
.global end_Psev_door3Z
.set end_Psev_door3Z, 0x10802D00
.global Psev_door3_windZ
.set Psev_door3_windZ, 0x10802D00
.global end_Psev_door3_windZ
.set end_Psev_door3_windZ, 0x10803090
.global Psev_door4_windZ
.set Psev_door4_windZ, 0x10803090
.global end_Psev_door4_windZ
.set end_Psev_door4_windZ, 0x10803470
.global Psev_doorZ
.set Psev_doorZ, 0x10803470
.global end_Psev_doorZ
.set end_Psev_doorZ, 0x108037C0
.global Psev_door_v1Z
.set Psev_door_v1Z, 0x108037C0
.global end_Psev_door_v1Z
.set end_Psev_door_v1Z, 0x10803AF0
.global Psev_trislideZ
.set Psev_trislideZ, 0x10803AF0
.global end_Psev_trislideZ
.set end_Psev_trislideZ, 0x10803EA0
.global PsevdishZ
.set PsevdishZ, 0x10803EA0
.global end_PsevdishZ
.set end_PsevdishZ, 0x10804DC0
.global PsevdoormetslideZ
.set PsevdoormetslideZ, 0x10804DC0
.global end_PsevdoormetslideZ
.set end_PsevdoormetslideZ, 0x108050A0
.global PsevdoornowindZ
.set PsevdoornowindZ, 0x108050A0
.global end_PsevdoornowindZ
.set end_PsevdoornowindZ, 0x10805210
.global PsevdoorwindZ
.set PsevdoorwindZ, 0x10805210
.global end_PsevdoorwindZ
.set end_PsevdoorwindZ, 0x10805640
.global PsevdoorwoodZ
.set PsevdoorwoodZ, 0x10805640
.global end_PsevdoorwoodZ
.set end_PsevdoorwoodZ, 0x108059F0
.global PshuttleZ
.set PshuttleZ, 0x108059F0
.global end_PshuttleZ
.set end_PshuttleZ, 0x108083F0
.global Pshuttle_door_lZ
.set Pshuttle_door_lZ, 0x108083F0
.global end_Pshuttle_door_lZ
.set end_Pshuttle_door_lZ, 0x10809020
.global Pshuttle_door_rZ
.set Pshuttle_door_rZ, 0x10809020
.global end_Pshuttle_door_rZ
.set end_Pshuttle_door_rZ, 0x10809D20
.global PsilencerZ
.set PsilencerZ, 0x10809D20
.global end_PsilencerZ
.set end_PsilencerZ, 0x10809EC0
.global Psilo_lift_doorZ
.set Psilo_lift_doorZ, 0x10809EC0
.global end_Psilo_lift_doorZ
.set end_Psilo_lift_doorZ, 0x1080A100
.global PsilotopdoorZ
.set PsilotopdoorZ, 0x1080A100
.global end_PsilotopdoorZ
.set end_PsilotopdoorZ, 0x1080A3F0
.global PskorpionmagZ
.set PskorpionmagZ, 0x1080A3F0
.global end_PskorpionmagZ
.set end_PskorpionmagZ, 0x1080A550
.global PspectremagZ
.set PspectremagZ, 0x1080A550
.global end_PspectremagZ
.set end_PspectremagZ, 0x1080A6C0
.global PspeedboatZ
.set PspeedboatZ, 0x1080A6C0
.global end_PspeedboatZ
.set end_PspeedboatZ, 0x1080B400
.global Pst_pete_room_1iZ
.set Pst_pete_room_1iZ, 0x1080B400
.global end_Pst_pete_room_1iZ
.set end_Pst_pete_room_1iZ, 0x1080E540
.global Pst_pete_room_2iZ
.set Pst_pete_room_2iZ, 0x1080E540
.global end_Pst_pete_room_2iZ
.set end_Pst_pete_room_2iZ, 0x10811720
.global Pst_pete_room_3tZ
.set Pst_pete_room_3tZ, 0x10811720
.global end_Pst_pete_room_3tZ
.set end_Pst_pete_room_3tZ, 0x10814660
.global Pst_pete_room_5cZ
.set Pst_pete_room_5cZ, 0x10814660
.global end_Pst_pete_room_5cZ
.set end_Pst_pete_room_5cZ, 0x10817BF0
.global Pst_pete_room_6cZ
.set Pst_pete_room_6cZ, 0x10817BF0
.global end_Pst_pete_room_6cZ
.set end_Pst_pete_room_6cZ, 0x1081B000
.global Psteel_door1Z
.set Psteel_door1Z, 0x1081B000
.global end_Psteel_door1Z
.set end_Psteel_door1Z, 0x1081B270
.global Psteel_door2Z
.set Psteel_door2Z, 0x1081B270
.global end_Psteel_door2Z
.set end_Psteel_door2Z, 0x1081B520
.global Psteel_door2bZ
.set Psteel_door2bZ, 0x1081B520
.global end_Psteel_door2bZ
.set end_Psteel_door2bZ, 0x1081B7F0
.global Psteel_door3Z
.set Psteel_door3Z, 0x1081B7F0
.global end_Psteel_door3Z
.set end_Psteel_door3Z, 0x1081BAC0
.global Pstool1Z
.set Pstool1Z, 0x1081BAC0
.global end_Pstool1Z
.set end_Pstool1Z, 0x1081BD80
.global Pswipe_card2Z
.set Pswipe_card2Z, 0x1081BD80
.global end_Pswipe_card2Z
.set end_Pswipe_card2Z, 0x1081BF10
.global Pswivel_chair1Z
.set Pswivel_chair1Z, 0x1081BF10
.global end_Pswivel_chair1Z
.set end_Pswivel_chair1Z, 0x1081C1A0
.global PtankZ
.set PtankZ, 0x1081C1A0
.global end_PtankZ
.set end_PtankZ, 0x1081DC40
.global PtigerZ
.set PtigerZ, 0x1081DC40
.global end_PtigerZ
.set end_PtigerZ, 0x1081FAD0
.global Ptorpedo_rackZ
.set Ptorpedo_rackZ, 0x1081FAD0
.global end_Ptorpedo_rackZ
.set end_Ptorpedo_rackZ, 0x10820350
.global Ptrain_door2Z
.set Ptrain_door2Z, 0x10820350
.global end_Ptrain_door2Z
.set end_Ptrain_door2Z, 0x10820720
.global Ptrain_door3Z
.set Ptrain_door3Z, 0x10820720
.global end_Ptrain_door3Z
.set end_Ptrain_door3Z, 0x10820B40
.global Ptrain_doorZ
.set Ptrain_doorZ, 0x10820B40
.global end_Ptrain_doorZ
.set end_Ptrain_doorZ, 0x10820DB0
.global PtrainextdoorZ
.set PtrainextdoorZ, 0x10820DB0
.global end_PtrainextdoorZ
.set end_PtrainextdoorZ, 0x108210F0
.global Ptt33magZ
.set Ptt33magZ, 0x108210F0
.global end_Ptt33magZ
.set end_Ptt33magZ, 0x10821230
.global Ptuning_console1Z
.set Ptuning_console1Z, 0x10821230
.global end_Ptuning_console1Z
.set end_Ptuning_console1Z, 0x10821750
.global Ptv1Z
.set Ptv1Z, 0x10821750
.global end_Ptv1Z
.set end_Ptv1Z, 0x10821920
.global Ptv4screenZ
.set Ptv4screenZ, 0x10821920
.global end_Ptv4screenZ
.set end_Ptv4screenZ, 0x10821AC0
.global Ptv_holderZ
.set Ptv_holderZ, 0x10821AC0
.global end_Ptv_holderZ
.set end_Ptv_holderZ, 0x10822190
.global PtvscreenZ
.set PtvscreenZ, 0x10822190
.global end_PtvscreenZ
.set end_PtvscreenZ, 0x10822260
.global PuzimagZ
.set PuzimagZ, 0x10822260
.global end_PuzimagZ
.set end_PuzimagZ, 0x108223A0
.global PvertdoorZ
.set PvertdoorZ, 0x108223A0
.global end_PvertdoorZ
.set end_PvertdoorZ, 0x108229B0
.global PwalletbondZ
.set PwalletbondZ, 0x108229B0
.global end_PwalletbondZ
.set end_PwalletbondZ, 0x10823F60
.global PwindowZ
.set PwindowZ, 0x10823F60
.global end_PwindowZ
.set end_PwindowZ, 0x10824050
.global Pwindow_cor11Z
.set Pwindow_cor11Z, 0x10824050
.global end_Pwindow_cor11Z
.set end_Pwindow_cor11Z, 0x10824130
.global Pwindow_lib_lg1Z
.set Pwindow_lib_lg1Z, 0x10824130
.global end_Pwindow_lib_lg1Z
.set end_Pwindow_lib_lg1Z, 0x10824210
.global Pwindow_lib_sm1Z
.set Pwindow_lib_sm1Z, 0x10824210
.global end_Pwindow_lib_sm1Z
.set end_Pwindow_lib_sm1Z, 0x10824300
.global Pwood_lg_crate1Z
.set Pwood_lg_crate1Z, 0x10824300
.global end_Pwood_lg_crate1Z
.set end_Pwood_lg_crate1Z, 0x10824580
.global Pwood_lg_crate2Z
.set Pwood_lg_crate2Z, 0x10824580
.global end_Pwood_lg_crate2Z
.set end_Pwood_lg_crate2Z, 0x108247A0
.global Pwood_md_crate3Z
.set Pwood_md_crate3Z, 0x108247A0
.global end_Pwood_md_crate3Z
.set end_Pwood_md_crate3Z, 0x108249C0
.global Pwood_sm_crate4Z
.set Pwood_sm_crate4Z, 0x108249C0
.global end_Pwood_sm_crate4Z
.set end_Pwood_sm_crate4Z, 0x10824C20
.global Pwood_sm_crate5Z
.set Pwood_sm_crate5Z, 0x10824C20
.global end_Pwood_sm_crate5Z
.set end_Pwood_sm_crate5Z, 0x10824E80
.global Pwood_sm_crate6Z
.set Pwood_sm_crate6Z, 0x10824E80
.global end_Pwood_sm_crate6Z
.set end_Pwood_sm_crate6Z, 0x108250A0
.global Pwooden_table1Z
.set Pwooden_table1Z, 0x108250A0
.global end_Pwooden_table1Z
.set end_Pwooden_table1Z, 0x10825410
.global PwppkmagZ
.set PwppkmagZ, 0x10825410
.global end_PwppkmagZ
.set end_PwppkmagZ, 0x10825550
.global Tbg_ame_all_p_stanZ
.set Tbg_ame_all_p_stanZ, 0x10825550
.global end_Tbg_ame_all_p_stanZ
.set end_Tbg_ame_all_p_stanZ, 0x10826E80
.global Tbg_arch_all_p_stanZ
.set Tbg_arch_all_p_stanZ, 0x10826E80
.global end_Tbg_arch_all_p_stanZ
.set end_Tbg_arch_all_p_stanZ, 0x1082CB70
.global Tbg_arec_all_p_stanZ
.set Tbg_arec_all_p_stanZ, 0x1082CB70
.global end_Tbg_arec_all_p_stanZ
.set end_Tbg_arec_all_p_stanZ, 0x10834EC0
.global Tbg_ark_all_p_stanZ
.set Tbg_ark_all_p_stanZ, 0x10834EC0
.global end_Tbg_ark_all_p_stanZ
.set end_Tbg_ark_all_p_stanZ, 0x1083DE80
.global Tbg_ash_all_p_stanZ
.set Tbg_ash_all_p_stanZ, 0x1083DE80
.global end_Tbg_ash_all_p_stanZ
.set end_Tbg_ash_all_p_stanZ, 0x1083F7B0
.global Tbg_azt_all_p_stanZ
.set Tbg_azt_all_p_stanZ, 0x1083F7B0
.global end_Tbg_azt_all_p_stanZ
.set end_Tbg_azt_all_p_stanZ, 0x10844D30
.global Tbg_cat_all_p_stanZ
.set Tbg_cat_all_p_stanZ, 0x10844D30
.global end_Tbg_cat_all_p_stanZ
.set end_Tbg_cat_all_p_stanZ, 0x10847460
.global Tbg_cave_all_p_stanZ
.set Tbg_cave_all_p_stanZ, 0x10847460
.global end_Tbg_cave_all_p_stanZ
.set end_Tbg_cave_all_p_stanZ, 0x1084C350
.global Tbg_crad_all_p_stanZ
.set Tbg_crad_all_p_stanZ, 0x1084C350
.global end_Tbg_crad_all_p_stanZ
.set end_Tbg_crad_all_p_stanZ, 0x1084EC60
.global Tbg_cryp_all_p_stanZ
.set Tbg_cryp_all_p_stanZ, 0x1084EC60
.global end_Tbg_cryp_all_p_stanZ
.set end_Tbg_cryp_all_p_stanZ, 0x10851CD0
.global Tbg_dam_all_p_stanZ
.set Tbg_dam_all_p_stanZ, 0x10851CD0
.global end_Tbg_dam_all_p_stanZ
.set end_Tbg_dam_all_p_stanZ, 0x1085C0B0
.global Tbg_depo_all_p_stanZ
.set Tbg_depo_all_p_stanZ, 0x1085C0B0
.global end_Tbg_depo_all_p_stanZ
.set end_Tbg_depo_all_p_stanZ, 0x10862FF0
.global Tbg_dest_all_p_stanZ
.set Tbg_dest_all_p_stanZ, 0x10862FF0
.global end_Tbg_dest_all_p_stanZ
.set end_Tbg_dest_all_p_stanZ, 0x108698E0
.global Tbg_dish_all_p_stanZ
.set Tbg_dish_all_p_stanZ, 0x108698E0
.global end_Tbg_dish_all_p_stanZ
.set end_Tbg_dish_all_p_stanZ, 0x1086A3F0
.global Tbg_imp_all_p_stanZ
.set Tbg_imp_all_p_stanZ, 0x1086A3F0
.global end_Tbg_imp_all_p_stanZ
.set end_Tbg_imp_all_p_stanZ, 0x1086BD20
.global Tbg_jun_all_p_stanZ
.set Tbg_jun_all_p_stanZ, 0x1086BD20
.global end_Tbg_jun_all_p_stanZ
.set end_Tbg_jun_all_p_stanZ, 0x10872E70
.global Tbg_len_all_p_stanZ
.set Tbg_len_all_p_stanZ, 0x10872E70
.global end_Tbg_len_all_p_stanZ
.set end_Tbg_len_all_p_stanZ, 0x10873930
.global Tbg_oat_all_p_stanZ
.set Tbg_oat_all_p_stanZ, 0x10873930
.global end_Tbg_oat_all_p_stanZ
.set end_Tbg_oat_all_p_stanZ, 0x10875230
.global Tbg_pete_all_p_stanZ
.set Tbg_pete_all_p_stanZ, 0x10875230
.global end_Tbg_pete_all_p_stanZ
.set end_Tbg_pete_all_p_stanZ, 0x108798C0
.global Tbg_ref_all_p_stanZ
.set Tbg_ref_all_p_stanZ, 0x108798C0
.global end_Tbg_ref_all_p_stanZ
.set end_Tbg_ref_all_p_stanZ, 0x1087B690
.global Tbg_run_all_p_stanZ
.set Tbg_run_all_p_stanZ, 0x1087B690
.global end_Tbg_run_all_p_stanZ
.set end_Tbg_run_all_p_stanZ, 0x1087D110
.global Tbg_sev_all_p_stanZ
.set Tbg_sev_all_p_stanZ, 0x1087D110
.global end_Tbg_sev_all_p_stanZ
.set end_Tbg_sev_all_p_stanZ, 0x10880EE0
.global Tbg_sevb_all_p_stanZ
.set Tbg_sevb_all_p_stanZ, 0x10880EE0
.global end_Tbg_sevb_all_p_stanZ
.set end_Tbg_sevb_all_p_stanZ, 0x10885E20
.global Tbg_sevx_all_p_stanZ
.set Tbg_sevx_all_p_stanZ, 0x10885E20
.global end_Tbg_sevx_all_p_stanZ
.set end_Tbg_sevx_all_p_stanZ, 0x1088F150
.global Tbg_silo_all_p_stanZ
.set Tbg_silo_all_p_stanZ, 0x1088F150
.global end_Tbg_silo_all_p_stanZ
.set end_Tbg_silo_all_p_stanZ, 0x108981F0
.global Tbg_stat_all_p_stanZ
.set Tbg_stat_all_p_stanZ, 0x108981F0
.global end_Tbg_stat_all_p_stanZ
.set end_Tbg_stat_all_p_stanZ, 0x1089D0B0
.global Tbg_tra_all_p_stanZ
.set Tbg_tra_all_p_stanZ, 0x1089D0B0
.global end_Tbg_tra_all_p_stanZ
.set end_Tbg_tra_all_p_stanZ, 0x1089F480
.global UbriefarchZ
.set UbriefarchZ, 0x1089F480
.global end_UbriefarchZ
.set end_UbriefarchZ, 0x1089F4A0
.global UbriefarkZ
.set UbriefarkZ, 0x1089F4A0
.global end_UbriefarkZ
.set end_UbriefarkZ, 0x1089F4C0
.global UbriefaztZ
.set UbriefaztZ, 0x1089F4C0
.global end_UbriefaztZ
.set end_UbriefaztZ, 0x1089F4E0
.global UbriefcaveZ
.set UbriefcaveZ, 0x1089F4E0
.global end_UbriefcaveZ
.set end_UbriefcaveZ, 0x1089F500
.global UbriefcontrolZ
.set UbriefcontrolZ, 0x1089F500
.global end_UbriefcontrolZ
.set end_UbriefcontrolZ, 0x1089F520
.global UbriefcradZ
.set UbriefcradZ, 0x1089F520
.global end_UbriefcradZ
.set end_UbriefcradZ, 0x1089F540
.global UbriefcrypZ
.set UbriefcrypZ, 0x1089F540
.global end_UbriefcrypZ
.set end_UbriefcrypZ, 0x1089F560
.global UbriefdamZ
.set UbriefdamZ, 0x1089F560
.global end_UbriefdamZ
.set end_UbriefdamZ, 0x1089F580
.global UbriefdepoZ
.set UbriefdepoZ, 0x1089F580
.global end_UbriefdepoZ
.set end_UbriefdepoZ, 0x1089F5A0
.global UbriefdestZ
.set UbriefdestZ, 0x1089F5A0
.global end_UbriefdestZ
.set end_UbriefdestZ, 0x1089F5C0
.global UbriefjunZ
.set UbriefjunZ, 0x1089F5C0
.global end_UbriefjunZ
.set end_UbriefjunZ, 0x1089F5E0
.global UbriefpeteZ
.set UbriefpeteZ, 0x1089F5E0
.global end_UbriefpeteZ
.set end_UbriefpeteZ, 0x1089F600
.global UbriefrunZ
.set UbriefrunZ, 0x1089F600
.global end_UbriefrunZ
.set end_UbriefrunZ, 0x1089F620
.global UbriefsevbZ
.set UbriefsevbZ, 0x1089F620
.global end_UbriefsevbZ
.set end_UbriefsevbZ, 0x1089F640
.global UbriefsevbunkerZ
.set UbriefsevbunkerZ, 0x1089F640
.global end_UbriefsevbunkerZ
.set end_UbriefsevbunkerZ, 0x1089F660
.global UbriefsevxZ
.set UbriefsevxZ, 0x1089F660
.global end_UbriefsevxZ
.set end_UbriefsevxZ, 0x1089F680
.global UbriefsevxbZ
.set UbriefsevxbZ, 0x1089F680
.global end_UbriefsevxbZ
.set end_UbriefsevxbZ, 0x1089F6A0
.global UbriefsiloZ
.set UbriefsiloZ, 0x1089F6A0
.global end_UbriefsiloZ
.set end_UbriefsiloZ, 0x1089F6C0
.global UbriefstatueZ
.set UbriefstatueZ, 0x1089F6C0
.global end_UbriefstatueZ
.set end_UbriefstatueZ, 0x1089F6E0
.global UbrieftraZ
.set UbrieftraZ, 0x1089F6E0
.global end_UbrieftraZ
.set end_UbrieftraZ, 0x1089F700
.global Ump_setupameZ
.set Ump_setupameZ, 0x1089F700
.global end_Ump_setupameZ
.set end_Ump_setupameZ, 0x1089FE20
.global Ump_setuparchZ
.set Ump_setuparchZ, 0x1089FE20
.global end_Ump_setuparchZ
.set end_Ump_setuparchZ, 0x108A2BC0
.global Ump_setuparkZ
.set Ump_setuparkZ, 0x108A2BC0
.global end_Ump_setuparkZ
.set end_Ump_setuparkZ, 0x108A4900
.global Ump_setupashZ
.set Ump_setupashZ, 0x108A4900
.global end_Ump_setupashZ
.set end_Ump_setupashZ, 0x108A4FF0
.global Ump_setupcaveZ
.set Ump_setupcaveZ, 0x108A4FF0
.global end_Ump_setupcaveZ
.set end_Ump_setupcaveZ, 0x108A7550
.global Ump_setupcradZ
.set Ump_setupcradZ, 0x108A7550
.global end_Ump_setupcradZ
.set end_Ump_setupcradZ, 0x108A7EB0
.global Ump_setupcrypZ
.set Ump_setupcrypZ, 0x108A7EB0
.global end_Ump_setupcrypZ
.set end_Ump_setupcrypZ, 0x108A8C10
.global Ump_setupdishZ
.set Ump_setupdishZ, 0x108A8C10
.global end_Ump_setupdishZ
.set end_Ump_setupdishZ, 0x108A9000
.global Ump_setupimpZ
.set Ump_setupimpZ, 0x108A9000
.global end_Ump_setupimpZ
.set end_Ump_setupimpZ, 0x108A9640
.global Ump_setupoatZ
.set Ump_setupoatZ, 0x108A9640
.global end_Ump_setupoatZ
.set end_Ump_setupoatZ, 0x108A9990
.global Ump_setuprefZ
.set Ump_setuprefZ, 0x108A9990
.global end_Ump_setuprefZ
.set end_Ump_setuprefZ, 0x108A9DA0
.global Ump_setupsevbZ
.set Ump_setupsevbZ, 0x108A9DA0
.global end_Ump_setupsevbZ
.set end_Ump_setupsevbZ, 0x108AB0B0
.global Ump_setupstatueZ
.set Ump_setupstatueZ, 0x108AB0B0
.global end_Ump_setupstatueZ
.set end_Ump_setupstatueZ, 0x108ABF30
.global UsetuparchZ
.set UsetuparchZ, 0x108ABF30
.global end_UsetuparchZ
.set end_UsetuparchZ, 0x108B0540
.global UsetuparkZ
.set UsetuparkZ, 0x108B0540
.global end_UsetuparkZ
.set end_UsetuparkZ, 0x108B40D0
.global UsetupaztZ
.set UsetupaztZ, 0x108B40D0
.global end_UsetupaztZ
.set end_UsetupaztZ, 0x108B69D0
.global UsetupcaveZ
.set UsetupcaveZ, 0x108B69D0
.global end_UsetupcaveZ
.set end_UsetupcaveZ, 0x108BA830
.global UsetupcontrolZ
.set UsetupcontrolZ, 0x108BA830
.global end_UsetupcontrolZ
.set end_UsetupcontrolZ, 0x108BE330
.global UsetupcradZ
.set UsetupcradZ, 0x108BE330
.global end_UsetupcradZ
.set end_UsetupcradZ, 0x108BFF60
.global UsetupcrypZ
.set UsetupcrypZ, 0x108BFF60
.global end_UsetupcrypZ
.set end_UsetupcrypZ, 0x108C1DF0
.global UsetupdamZ
.set UsetupdamZ, 0x108C1DF0
.global end_UsetupdamZ
.set end_UsetupdamZ, 0x108C60C0
.global UsetupdepoZ
.set UsetupdepoZ, 0x108C60C0
.global end_UsetupdepoZ
.set end_UsetupdepoZ, 0x108C9050
.global UsetupdestZ
.set UsetupdestZ, 0x108C9050
.global end_UsetupdestZ
.set end_UsetupdestZ, 0x108CB3A0
.global UsetupjunZ
.set UsetupjunZ, 0x108CB3A0
.global end_UsetupjunZ
.set end_UsetupjunZ, 0x108CEAB0
.global UsetuplenZ
.set UsetuplenZ, 0x108CEAB0
.global end_UsetuplenZ
.set end_UsetuplenZ, 0x108CF0A0
.global UsetuppeteZ
.set UsetuppeteZ, 0x108CF0A0
.global end_UsetuppeteZ
.set end_UsetuppeteZ, 0x108D2020
.global UsetuprunZ
.set UsetuprunZ, 0x108D2020
.global end_UsetuprunZ
.set end_UsetuprunZ, 0x108D3880
.global UsetupsevbZ
.set UsetupsevbZ, 0x108D3880
.global end_UsetupsevbZ
.set end_UsetupsevbZ, 0x108D5EE0
.global UsetupsevbunkerZ
.set UsetupsevbunkerZ, 0x108D5EE0
.global end_UsetupsevbunkerZ
.set end_UsetupsevbunkerZ, 0x108D7910
.global UsetupsevxZ
.set UsetupsevxZ, 0x108D7910
.global end_UsetupsevxZ
.set end_UsetupsevxZ, 0x108DBC20
.global UsetupsevxbZ
.set UsetupsevxbZ, 0x108DBC20
.global end_UsetupsevxbZ
.set end_UsetupsevxbZ, 0x108DFD10
.global UsetupsiloZ
.set UsetupsiloZ, 0x108DFD10
.global end_UsetupsiloZ
.set end_UsetupsiloZ, 0x108E27D0
.global UsetupstatueZ
.set UsetupstatueZ, 0x108E27D0
.global end_UsetupstatueZ
.set end_UsetupstatueZ, 0x108E4FA0
.global UsetuptraZ
.set UsetuptraZ, 0x108E4FA0
.global end_UsetuptraZ
.set end_UsetuptraZ, 0x108E81E0
.global LameE
.set LameE, 0x108E81E0
.global end_LameE
.set end_LameE, 0x108E81F0
.global LameJ
.set LameJ, 0x108E81F0
.global end_LameJ
.set end_LameJ, 0x108E8200
.global LarchE
.set LarchE, 0x108E8200
.global end_LarchE
.set end_LarchE, 0x108E8830
.global LarchJ
.set LarchJ, 0x108E8830
.global end_LarchJ
.set end_LarchJ, 0x108E8E90
.global LarecE
.set LarecE, 0x108E8E90
.global end_LarecE
.set end_LarecE, 0x108E9460
.global LarecJ
.set LarecJ, 0x108E9460
.global end_LarecJ
.set end_LarecJ, 0x108E9A00
.global LarkE
.set LarkE, 0x108E9A00
.global end_LarkE
.set end_LarkE, 0x108EA0A0
.global LarkJ
.set LarkJ, 0x108EA0A0
.global end_LarkJ
.set end_LarkJ, 0x108EA730
.global LashE
.set LashE, 0x108EA730
.global end_LashE
.set end_LashE, 0x108EA740
.global LashJ
.set LashJ, 0x108EA740
.global end_LashJ
.set end_LashJ, 0x108EA750
.global LaztE
.set LaztE, 0x108EA750
.global end_LaztE
.set end_LaztE, 0x108EAB90
.global LaztJ
.set LaztJ, 0x108EAB90
.global end_LaztJ
.set end_LaztJ, 0x108EAFE0
.global LcatE
.set LcatE, 0x108EAFE0
.global end_LcatE
.set end_LcatE, 0x108EAFF0
.global LcatJ
.set LcatJ, 0x108EAFF0
.global end_LcatJ
.set end_LcatJ, 0x108EB000
.global LcaveE
.set LcaveE, 0x108EB000
.global end_LcaveE
.set end_LcaveE, 0x108EB400
.global LcaveJ
.set LcaveJ, 0x108EB400
.global end_LcaveJ
.set end_LcaveJ, 0x108EB860
.global LcradE
.set LcradE, 0x108EB860
.global end_LcradE
.set end_LcradE, 0x108EBD30
.global LcradJ
.set LcradJ, 0x108EBD30
.global end_LcradJ
.set end_LcradJ, 0x108EC1D0
.global LcrypE
.set LcrypE, 0x108EC1D0
.global end_LcrypE
.set end_LcrypE, 0x108EC420
.global LcrypJ
.set LcrypJ, 0x108EC420
.global end_LcrypJ
.set end_LcrypJ, 0x108EC6C0
.global LdamE
.set LdamE, 0x108EC6C0
.global end_LdamE
.set end_LdamE, 0x108ECB10
.global LdamJ
.set LdamJ, 0x108ECB10
.global end_LdamJ
.set end_LdamJ, 0x108ECF60
.global LdepoE
.set LdepoE, 0x108ECF60
.global end_LdepoE
.set end_LdepoE, 0x108ED2D0
.global LdepoJ
.set LdepoJ, 0x108ED2D0
.global end_LdepoJ
.set end_LdepoJ, 0x108ED600
.global LdestE
.set LdestE, 0x108ED600
.global end_LdestE
.set end_LdestE, 0x108EDA90
.global LdestJ
.set LdestJ, 0x108EDA90
.global end_LdestJ
.set end_LdestJ, 0x108EDEF0
.global LdishE
.set LdishE, 0x108EDEF0
.global end_LdishE
.set end_LdishE, 0x108EDF00
.global LdishJ
.set LdishJ, 0x108EDF00
.global end_LdishJ
.set end_LdishJ, 0x108EDF10
.global LearE
.set LearE, 0x108EDF10
.global end_LearE
.set end_LearE, 0x108EDF20
.global LearJ
.set LearJ, 0x108EDF20
.global end_LearJ
.set end_LearJ, 0x108EDF30
.global LeldE
.set LeldE, 0x108EDF30
.global end_LeldE
.set end_LeldE, 0x108EDF40
.global LeldJ
.set LeldJ, 0x108EDF40
.global end_LeldJ
.set end_LeldJ, 0x108EDF50
.global LgunE
.set LgunE, 0x108EDF50
.global end_LgunE
.set end_LgunE, 0x108EE670
.global LgunJ
.set LgunJ, 0x108EE670
.global end_LgunJ
.set end_LgunJ, 0x108EEDB0
.global LimpE
.set LimpE, 0x108EEDB0
.global end_LimpE
.set end_LimpE, 0x108EEDC0
.global LimpJ
.set LimpJ, 0x108EEDC0
.global end_LimpJ
.set end_LimpJ, 0x108EEDD0
.global LjunE
.set LjunE, 0x108EEDD0
.global end_LjunE
.set end_LjunE, 0x108EF2F0
.global LjunJ
.set LjunJ, 0x108EF2F0
.global end_LjunJ
.set end_LjunJ, 0x108EF820
.global LleeE
.set LleeE, 0x108EF820
.global end_LleeE
.set end_LleeE, 0x108EF830
.global LleeJ
.set LleeJ, 0x108EF830
.global end_LleeJ
.set end_LleeJ, 0x108EF840
.global LlenE
.set LlenE, 0x108EF840
.global end_LlenE
.set end_LlenE, 0x108EFEF0
.global LlenJ
.set LlenJ, 0x108EFEF0
.global end_LlenJ
.set end_LlenJ, 0x108F0610
.global LlipE
.set LlipE, 0x108F0610
.global end_LlipE
.set end_LlipE, 0x108F0620
.global LlipJ
.set LlipJ, 0x108F0620
.global end_LlipJ
.set end_LlipJ, 0x108F0630
.global LlueE
.set LlueE, 0x108F0630
.global end_LlueE
.set end_LlueE, 0x108F0640
.global LlueJ
.set LlueJ, 0x108F0640
.global end_LlueJ
.set end_LlueJ, 0x108F0650
.global LmiscE
.set LmiscE, 0x108F0650
.global end_LmiscE
.set end_LmiscE, 0x108F0900
.global LmiscJ
.set LmiscJ, 0x108F0900
.global end_LmiscJ
.set end_LmiscJ, 0x108F0BC0
.global LmpmenuE
.set LmpmenuE, 0x108F0BC0
.global end_LmpmenuE
.set end_LmpmenuE, 0x108F0D60
.global LmpmenuJ
.set LmpmenuJ, 0x108F0D60
.global end_LmpmenuJ
.set end_LmpmenuJ, 0x108F0F00
.global LmpweaponsE
.set LmpweaponsE, 0x108F0F00
.global end_LmpweaponsE
.set end_LmpweaponsE, 0x108F0FC0
.global LmpweaponsJ
.set LmpweaponsJ, 0x108F0FC0
.global end_LmpweaponsJ
.set end_LmpweaponsJ, 0x108F1090
.global LoatE
.set LoatE, 0x108F1090
.global end_LoatE
.set end_LoatE, 0x108F10A0
.global LoatJ
.set LoatJ, 0x108F10A0
.global end_LoatJ
.set end_LoatJ, 0x108F10B0
.global LoptionsE
.set LoptionsE, 0x108F10B0
.global end_LoptionsE
.set end_LoptionsE, 0x108F12E0
.global LoptionsJ
.set LoptionsJ, 0x108F12E0
.global end_LoptionsJ
.set end_LoptionsJ, 0x108F1520
.global LpamE
.set LpamE, 0x108F1520
.global end_LpamE
.set end_LpamE, 0x108F1530
.global LpamJ
.set LpamJ, 0x108F1530
.global end_LpamJ
.set end_LpamJ, 0x108F1540
.global LpeteE
.set LpeteE, 0x108F1540
.global end_LpeteE
.set end_LpeteE, 0x108F19C0
.global LpeteJ
.set LpeteJ, 0x108F19C0
.global end_LpeteJ
.set end_LpeteJ, 0x108F1E30
.global LpropobjE
.set LpropobjE, 0x108F1E30
.global end_LpropobjE
.set end_LpropobjE, 0x108F20D0
.global LpropobjJ
.set LpropobjJ, 0x108F20D0
.global end_LpropobjJ
.set end_LpropobjJ, 0x108F2370
.global LrefE
.set LrefE, 0x108F2370
.global end_LrefE
.set end_LrefE, 0x108F2380
.global LrefJ
.set LrefJ, 0x108F2380
.global end_LrefJ
.set end_LrefJ, 0x108F2390
.global LritE
.set LritE, 0x108F2390
.global end_LritE
.set end_LritE, 0x108F23A0
.global LritJ
.set LritJ, 0x108F23A0
.global end_LritJ
.set end_LritJ, 0x108F23B0
.global LrunE
.set LrunE, 0x108F23B0
.global end_LrunE
.set end_LrunE, 0x108F2620
.global LrunJ
.set LrunJ, 0x108F2620
.global end_LrunJ
.set end_LrunJ, 0x108F28B0
.global LsevE
.set LsevE, 0x108F28B0
.global end_LsevE
.set end_LsevE, 0x108F2E10
.global LsevJ
.set LsevJ, 0x108F2E10
.global end_LsevJ
.set end_LsevJ, 0x108F3320
.global LsevbE
.set LsevbE, 0x108F3320
.global end_LsevbE
.set end_LsevbE, 0x108F3A70
.global LsevbJ
.set LsevbJ, 0x108F3A70
.global end_LsevbJ
.set end_LsevbJ, 0x108F4260
.global LsevxE
.set LsevxE, 0x108F4260
.global end_LsevxE
.set end_LsevxE, 0x108F46C0
.global LsevxJ
.set LsevxJ, 0x108F46C0
.global end_LsevxJ
.set end_LsevxJ, 0x108F4A90
.global LsevxbE
.set LsevxbE, 0x108F4A90
.global end_LsevxbE
.set end_LsevxbE, 0x108F4F20
.global LsevxbJ
.set LsevxbJ, 0x108F4F20
.global end_LsevxbJ
.set end_LsevxbJ, 0x108F5370
.global LshoE
.set LshoE, 0x108F5370
.global end_LshoE
.set end_LshoE, 0x108F5380
.global LshoJ
.set LshoJ, 0x108F5380
.global end_LshoJ
.set end_LshoJ, 0x108F5390
.global LsiloE
.set LsiloE, 0x108F5390
.global end_LsiloE
.set end_LsiloE, 0x108F5940
.global LsiloJ
.set LsiloJ, 0x108F5940
.global end_LsiloJ
.set end_LsiloJ, 0x108F5F30
.global LstatE
.set LstatE, 0x108F5F30
.global end_LstatE
.set end_LstatE, 0x108F6850
.global LstatJ
.set LstatJ, 0x108F6850
.global end_LstatJ
.set end_LstatJ, 0x108F70A0
.global LtitleE
.set LtitleE, 0x108F70A0
.global end_LtitleE
.set end_LtitleE, 0x108F7BB0
.global LtitleJ
.set LtitleJ, 0x108F7BB0
.global end_LtitleJ
.set end_LtitleJ, 0x108F87A0
.global LtraE
.set LtraE, 0x108F87A0
.global end_LtraE
.set end_LtraE, 0x108F8BD0
.global LtraJ
.set LtraJ, 0x108F8BD0
.global end_LtraJ
.set end_LtraJ, 0x108F9020
.global LwaxE
.set LwaxE, 0x108F9020
.global end_LwaxE
.set end_LwaxE, 0x108F9030
.global LwaxJ
.set LwaxJ, 0x108F9030
.global end_LwaxJ
.set end_LwaxJ, 0x108F9040
.global ob__ob_end_seg
.set ob__ob_end_seg, 0x108F9040
.global end_ob__ob_end_seg
.set end_ob__ob_end_seg, 0x108F9050

/* --- assets/ramrom (demo replays) ---------------------------- */
.global ramrom_Dam_1
.set ramrom_Dam_1, 0x102BFFF0
.global ramrom_Dam_1_end
.set ramrom_Dam_1_end, 0x102C51F0
.global ramrom_Dam_2
.set ramrom_Dam_2, 0x102C51F0
.global ramrom_Dam_2_end
.set ramrom_Dam_2_end, 0x102C71C0
.global ramrom_Facility_1
.set ramrom_Facility_1, 0x102C71C0
.global ramrom_Facility_1_end
.set ramrom_Facility_1_end, 0x102C8C70
.global ramrom_Facility_2
.set ramrom_Facility_2, 0x102C8C70
.global ramrom_Facility_2_end
.set ramrom_Facility_2_end, 0x102CB050
.global ramrom_Facility_3
.set ramrom_Facility_3, 0x102CB050
.global ramrom_Facility_3_end
.set ramrom_Facility_3_end, 0x102CCCC0
.global ramrom_Runway_1
.set ramrom_Runway_1, 0x102CCCC0
.global ramrom_Runway_1_end
.set ramrom_Runway_1_end, 0x102CF410
.global ramrom_Runway_2
.set ramrom_Runway_2, 0x102CF410
.global ramrom_Runway_2_end
.set ramrom_Runway_2_end, 0x102D1D20
.global ramrom_BunkerI_1
.set ramrom_BunkerI_1, 0x102D1D20
.global ramrom_BunkerI_1_end
.set ramrom_BunkerI_1_end, 0x102D50B0
.global ramrom_BunkerI_2
.set ramrom_BunkerI_2, 0x102D50B0
.global ramrom_BunkerI_2_end
.set ramrom_BunkerI_2_end, 0x102DA330
.global ramrom_Silo_1
.set ramrom_Silo_1, 0x102DA330
.global ramrom_Silo_1_end
.set ramrom_Silo_1_end, 0x102DC4C0
.global ramrom_Silo_2
.set ramrom_Silo_2, 0x102DC4C0
.global ramrom_Silo_2_end
.set ramrom_Silo_2_end, 0x102DE490
.global ramrom_Frigate_1
.set ramrom_Frigate_1, 0x102DE490
.global ramrom_Frigate_1_end
.set ramrom_Frigate_1_end, 0x102DFE40
.global ramrom_Frigate_2
.set ramrom_Frigate_2, 0x102DFE40
.global ramrom_Frigate_2_end
.set ramrom_Frigate_2_end, 0x102E3320
.global ramrom_Train
.set ramrom_Train, 0x102E3320
.global ramrom_Train_end
.set ramrom_Train_end, 0x102E7110
.global _ramromDam1SegmentRomStart
.set _ramromDam1SegmentRomStart, 0x102BFFF0

/* --- assets/music ------------------------------------------------ */
.global _musicsampletblSegmentRomStart
.set _musicsampletblSegmentRomStart, 0x1041A4B0
.global number_music_samples
.set number_music_samples, 0x1041A4B0
.global number_music_samples_end
.set number_music_samples_end, 0x1041A4B4
.global table_music_data
.set table_music_data, 0x1041A4B4
.global _musicsampletblSegmentRomEnd
.set _musicsampletblSegmentRomEnd, 0x1041A6AC
.global table_music_data_end
.set table_music_data_end, 0x1041A6AC
.global _sfxctlSegmentRomStart
.set _sfxctlSegmentRomStart, 0x102ECB00
.global _sfxctlSegmentRomEnd
.set _sfxctlSegmentRomEnd, 0x102F26C0
.global _sfxtblSegmentRomStart
.set _sfxtblSegmentRomStart, 0x102F26C0
.global _sfxtblSegmentRomEnd
.set _sfxtblSegmentRomEnd, 0x103B5170
.global _instrumentsctlSegmentRomStart
.set _instrumentsctlSegmentRomStart, 0x103B5170
.global _instrumentsctlSegmentRomEnd
.set _instrumentsctlSegmentRomEnd, 0x103B9510
.global _instrumentstblSegmentRomStart
.set _instrumentstblSegmentRomStart, 0x103B9510
.global _instrumentstblSegmentRomEnd
.set _instrumentstblSegmentRomEnd, 0x1041A4B0
.global Mno_music
.set Mno_music, 0x1041A6AC
.global end_Mno_music
.set end_Mno_music, 0x1041A6D6
.global Msolo_death_abrev
.set Msolo_death_abrev, 0x1041A6D6
.global end_Msolo_death_abrev
.set end_Msolo_death_abrev, 0x1041A8AC
.global Mintro_eye
.set Mintro_eye, 0x1041A8AC
.global end_Mintro_eye
.set end_Mintro_eye, 0x1041B15A
.global Mtrain
.set Mtrain, 0x1041B15A
.global end_Mtrain
.set end_Mtrain, 0x1041BD44
.global Mdepot
.set Mdepot, 0x1041BD44
.global end_Mdepot
.set end_Mdepot, 0x1041CAE4
.global Mjungle_unused
.set Mjungle_unused, 0x1041CAE4
.global end_Mjungle_unused
.set end_Mjungle_unused, 0x1041D87C
.global Mcitadel
.set Mcitadel, 0x1041D87C
.global end_Mcitadel
.set end_Mcitadel, 0x1041E63C
.global Mfacility
.set Mfacility, 0x1041E63C
.global end_Mfacility
.set end_Mfacility, 0x1041F10A
.global Mcontrol
.set Mcontrol, 0x1041F10A
.global end_Mcontrol
.set end_Mcontrol, 0x1041FC68
.global Mdam
.set Mdam, 0x1041FC68
.global end_Mdam
.set end_Mdam, 0x10420A6C
.global Mfrigate
.set Mfrigate, 0x10420A6C
.global end_Mfrigate
.set end_Mfrigate, 0x1042184C
.global Marchives
.set Marchives, 0x1042184C
.global end_Marchives
.set end_Marchives, 0x104221A0
.global Msilo
.set Msilo, 0x104221A0
.global end_Msilo
.set end_Msilo, 0x10423010
.global Mjungle_perimeter_unused
.set Mjungle_perimeter_unused, 0x10423010
.global end_Mjungle_perimeter_unused
.set end_Mjungle_perimeter_unused, 0x10423F7C
.global Mstreets
.set Mstreets, 0x10423F7C
.global end_Mstreets
.set end_Mstreets, 0x10424C7E
.global Mbunker1
.set Mbunker1, 0x10424C7E
.global end_Mbunker1
.set end_Mbunker1, 0x104252F0
.global Mbunker2
.set Mbunker2, 0x104252F0
.global end_Mbunker2
.set end_Mbunker2, 0x10425970
.global Mstatue
.set Mstatue, 0x10425970
.global end_Mstatue
.set end_Mstatue, 0x10426308
.global Melevator_control
.set Melevator_control, 0x10426308
.global end_Melevator_control
.set end_Melevator_control, 0x10426CE2
.global Mcradle
.set Mcradle, 0x10426CE2
.global end_Mcradle
.set end_Mcradle, 0x10427A42
.global Mnull1
.set Mnull1, 0x10427A42
.global end_Mnull1
.set end_Mnull1, 0x10427A6C
.global Melevator_wc
.set Melevator_wc, 0x10427A6C
.global end_Melevator_wc
.set end_Melevator_wc, 0x104280B2
.global Megyptian
.set Megyptian, 0x104280B2
.global end_Megyptian
.set end_Megyptian, 0x10428E4C
.global Mfolders
.set Mfolders, 0x10428E4C
.global end_Mfolders
.set end_Mfolders, 0x1042922E
.global Mwatchmusic
.set Mwatchmusic, 0x1042922E
.global end_Mwatchmusic
.set end_Mwatchmusic, 0x10429420
.global Maztec
.set Maztec, 0x10429420
.global end_Maztec
.set end_Maztec, 0x1042A092
.global Mwatercaverns
.set Mwatercaverns, 0x1042A092
.global end_Mwatercaverns
.set end_Mwatercaverns, 0x1042AEBE
.global Mdeathsolo
.set Mdeathsolo, 0x1042AEBE
.global end_Mdeathsolo
.set end_Mdeathsolo, 0x1042B224
.global Msurface2
.set Msurface2, 0x1042B224
.global end_Msurface2
.set end_Msurface2, 0x1042BFDA
.global Mtrainx
.set Mtrainx, 0x1042BFDA
.global end_Mtrainx
.set end_Mtrainx, 0x1042C87A
.global Mnull2
.set Mnull2, 0x1042C87A
.global end_Mnull2
.set end_Mnull2, 0x1042C8A4
.global Mfacilityx
.set Mfacilityx, 0x1042C8A4
.global end_Mfacilityx
.set end_Mfacilityx, 0x1042D1FC
.global Mdepotx
.set Mdepotx, 0x1042D1FC
.global end_Mdepotx
.set end_Mdepotx, 0x1042D9B8
.global Mcontrolx
.set Mcontrolx, 0x1042D9B8
.global end_Mcontrolx
.set end_Mcontrolx, 0x1042DF00
.global Mwatercavernsx
.set Mwatercavernsx, 0x1042DF00
.global end_Mwatercavernsx
.set end_Mwatercavernsx, 0x1042E654
.global Mdamx
.set Mdamx, 0x1042E654
.global end_Mdamx
.set end_Mdamx, 0x1042EB74
.global Mfrigatex
.set Mfrigatex, 0x1042EB74
.global end_Mfrigatex
.set end_Mfrigatex, 0x1042F136
.global Marchivesx
.set Marchivesx, 0x1042F136
.global end_Marchivesx
.set end_Marchivesx, 0x1042F85A
.global Msilox
.set Msilox, 0x1042F85A
.global end_Msilox
.set end_Msilox, 0x1043014E
.global Mnull3
.set Mnull3, 0x1043014E
.global end_Mnull3
.set end_Mnull3, 0x10430178
.global Mstreetsx
.set Mstreetsx, 0x10430178
.global end_Mstreetsx
.set end_Mstreetsx, 0x104307E4
.global Mbunker1x
.set Mbunker1x, 0x104307E4
.global end_Mbunker1x
.set end_Mbunker1x, 0x10430F8A
.global Mbunker2x
.set Mbunker2x, 0x10430F8A
.global end_Mbunker2x
.set end_Mbunker2x, 0x104315D8
.global Mjunglex
.set Mjunglex, 0x104315D8
.global end_Mjunglex
.set end_Mjunglex, 0x10431DEE
.global Mnint_rare_logo
.set Mnint_rare_logo, 0x10431DEE
.global end_Mnint_rare_logo
.set end_Mnint_rare_logo, 0x10432220
.global Mstatuex
.set Mstatuex, 0x10432220
.global end_Mstatuex
.set end_Mstatuex, 0x104328D8
.global Maztecx
.set Maztecx, 0x104328D8
.global end_Maztecx
.set end_Maztecx, 0x104331AE
.global Megyptianx
.set Megyptianx, 0x104331AE
.global end_Megyptianx
.set end_Megyptianx, 0x10433A5E
.global Mcradlex
.set Mcradlex, 0x10433A5E
.global end_Mcradlex
.set end_Mcradlex, 0x10434128
.global Mcuba
.set Mcuba, 0x10434128
.global end_Mcuba
.set end_Mcuba, 0x10434972
.global Mrunway
.set Mrunway, 0x10434972
.global end_Mrunway
.set end_Mrunway, 0x10435690
.global Mrunway_plane
.set Mrunway_plane, 0x10435690
.global end_Mrunway_plane
.set end_Mrunway_plane, 0x1043596A
.global Msurface2x
.set Msurface2x, 0x1043596A
.global end_Msurface2x
.set end_Msurface2x, 0x10436092
.global Mwindblowing
.set Mwindblowing, 0x10436092
.global end_Mwindblowing
.set end_Mwindblowing, 0x104365B4
.global Mmultideath_alt
.set Mmultideath_alt, 0x104365B4
.global end_Mmultideath_alt
.set end_Mmultideath_alt, 0x104367C0
.global Mjungle
.set Mjungle, 0x104367C0
.global end_Mjungle
.set end_Mjungle, 0x10436F48
.global Mrunwayx
.set Mrunwayx, 0x10436F48
.global end_Mrunwayx
.set end_Mrunwayx, 0x1043756A
.global Msurface1
.set Msurface1, 0x1043756A
.global end_Msurface1
.set end_Msurface1, 0x104382D2
.global Mmultiplayerdeath
.set Mmultiplayerdeath, 0x104382D2
.global end_Mmultiplayerdeath
.set end_Mmultiplayerdeath, 0x1043859A
.global Msurface1x
.set Msurface1x, 0x1043859A
.global end_Msurface1x
.set end_Msurface1x, 0x10438CC2
.global Msurface2_ending
.set Msurface2_ending, 0x10438CC2
.global end_Msurface2_ending
.set end_Msurface2_ending, 0x10438F5E
.global Mstatue_ending
.set Mstatue_ending, 0x10438F5E
.global end_Mstatue_ending
.set end_Mstatue_ending, 0x104390C4
.global Mfrigate_outro
.set Mfrigate_outro, 0x104390C4
.global end_Mfrigate_outro
.set end_Mfrigate_outro, 0x10439380

/* --- assets/romfiles2.s -------------------------------------- */
.global unknown2
.set unknown2, 0x102A5A70
.global unknown2_end
.set unknown2_end, 0x102BFFF0

/* --- ge007.ld segment markers ------------------------------------ */
/* RomStart/RomEnd are exact for asset segments; Start/End mirror them
/* (game code only ever uses End-Start size differences for these).
/* Code segments are approximate (see generator header comment). */
.global _headerSegmentRomStart
.set _headerSegmentRomStart, 0x10000000
.global _headerSegmentRomEnd
.set _headerSegmentRomEnd, 0x10000040
.global _headerSegmentStart
.set _headerSegmentStart, 0x10000000
.global _headerSegmentEnd
.set _headerSegmentEnd, 0x10000040  /* approximate */
.global _bootSegmentRomStart
.set _bootSegmentRomStart, 0x10000040
.global _bootSegmentRomEnd
.set _bootSegmentRomEnd, 0x10001000
.global _bootSegmentStart
.set _bootSegmentStart, 0x10000040
.global _bootSegmentEnd
.set _bootSegmentEnd, 0x10001000  /* approximate */
.global _startSegmentRomStart
.set _startSegmentRomStart, 0x10001000
.global _startSegmentRomEnd
.set _startSegmentRomEnd, 0x10001050
.global _startSegmentStart
.set _startSegmentStart, 0x10001000
.global _startSegmentEnd
.set _startSegmentEnd, 0x10001050  /* approximate */
.global _codeSegmentRomStart
.set _codeSegmentRomStart, 0x10001050
.global _codeSegmentRomEnd
.set _codeSegmentRomEnd, 0x10021990
.global _codeSegmentStart
.set _codeSegmentStart, 0x10001050
.global _codeSegmentEnd
.set _codeSegmentEnd, 0x10021990  /* approximate */
.global _cdataSegmentRomStart
.set _cdataSegmentRomStart, 0x10021990
.global _cdataSegmentRomEnd
.set _cdataSegmentRomEnd, 0x10032E92
.global _cdataSegmentStart
.set _cdataSegmentStart, 0x10021990
.global _cdataSegmentEnd
.set _cdataSegmentEnd, 0x10032E92  /* approximate */
.global _inflateSegmentRomStart
.set _inflateSegmentRomStart, 0x10032E92
.global _inflateSegmentRomEnd
.set _inflateSegmentRomEnd, 0x1003584F
.global _inflateSegmentStart
.set _inflateSegmentStart, 0x10032E92
.global _inflateSegmentEnd
.set _inflateSegmentEnd, 0x1003584F  /* approximate */
.global _gameSegmentRomStart
.set _gameSegmentRomStart, 0x1003584F
.global _gameSegmentRomEnd
.set _gameSegmentRomEnd, 0x101185A0
.global _gameSegmentStart
.set _gameSegmentStart, 0x1003584F
.global _gameSegmentEnd
.set _gameSegmentEnd, 0x101185A0  /* approximate */
.global _fontdlSegmentRomStart
.set _fontdlSegmentRomStart, 0x101185A0
.global _fontdlSegmentRomEnd
.set _fontdlSegmentRomEnd, 0x10118660
.global _fontdlSegmentStart
.set _fontdlSegmentStart, 0x101185A0
.global _fontdlSegmentEnd
.set _fontdlSegmentEnd, 0x10118660
.global _jfontchardataSegmentRomStart
.set _jfontchardataSegmentRomStart, 0x10118660
.global _jfontchardataSegmentRomEnd
.set _jfontchardataSegmentRomEnd, 0x10123D60
.global _jfontchardataSegmentStart
.set _jfontchardataSegmentStart, 0x10118660
.global _jfontchardataSegmentEnd
.set _jfontchardataSegmentEnd, 0x10123D60
.global _efontchardataSegmentRomStart
.set _efontchardataSegmentRomStart, 0x10123D60
.global _efontchardataSegmentRomEnd
.set _efontchardataSegmentRomEnd, 0x101257E0
.global _efontchardataSegmentStart
.set _efontchardataSegmentStart, 0x10123D60
.global _efontchardataSegmentEnd
.set _efontchardataSegmentEnd, 0x101257E0
.global _animation_entriesSegmentRomStart
.set _animation_entriesSegmentRomStart, 0x101257E0
.global _animation_entriesSegmentRomEnd
.set _animation_entriesSegmentRomEnd, 0x1028F6A0
.global _animation_entriesSegmentStart
.set _animation_entriesSegmentStart, 0x101257E0
.global _animation_entriesSegmentEnd
.set _animation_entriesSegmentEnd, 0x1028F6A0
.global _animation_dataSegmentRomStart
.set _animation_dataSegmentRomStart, 0x1028F6A0
.global _animation_dataSegmentRomEnd
.set _animation_dataSegmentRomEnd, 0x1029DE80
.global _animation_dataSegmentStart
.set _animation_dataSegmentStart, 0x1028F6A0
.global _animation_dataSegmentEnd
.set _animation_dataSegmentEnd, 0x1029DE80
.global _GlobalimagetableSegmentRomStart
.set _GlobalimagetableSegmentRomStart, 0x1029DE80
.global _GlobalimagetableSegmentRomEnd
.set _GlobalimagetableSegmentRomEnd, 0x1029F278
.global _GlobalimagetableSegmentStart
.set _GlobalimagetableSegmentStart, 0x1029DE80
.global _GlobalimagetableSegmentEnd
.set _GlobalimagetableSegmentEnd, 0x1029F278
.global _rarewarelogoSegmentRomStart
.set _rarewarelogoSegmentRomStart, 0x1029F280
.global _rarewarelogoSegmentRomEnd
.set _rarewarelogoSegmentRomEnd, 0x102A5A70
.global _rarewarelogoSegmentStart
.set _rarewarelogoSegmentStart, 0x1029F280
.global _rarewarelogoSegmentEnd
.set _rarewarelogoSegmentEnd, 0x102A5A70
.global _romfiles2SegmentRomStart
.set _romfiles2SegmentRomStart, 0x102A5A70
.global _romfiles2SegmentRomEnd
.set _romfiles2SegmentRomEnd, 0x102BFFF0
.global _romfiles2SegmentStart
.set _romfiles2SegmentStart, 0x102A5A70
.global _romfiles2SegmentEnd
.set _romfiles2SegmentEnd, 0x102BFFF0
.global _ramromfilesSegmentRomStart
.set _ramromfilesSegmentRomStart, 0x102BFFF0
.global _ramromfilesSegmentRomEnd
.set _ramromfilesSegmentRomEnd, 0x102E7110
.global _ramromfilesSegmentStart
.set _ramromfilesSegmentStart, 0x102BFFF0
.global _ramromfilesSegmentEnd
.set _ramromfilesSegmentEnd, 0x102E7110
.global _fontbankgothicSegmentRomStart
.set _fontbankgothicSegmentRomStart, 0x102E7110
.global _fontbankgothicSegmentRomEnd
.set _fontbankgothicSegmentRomEnd, 0x102E95C0
.global _fontbankgothicSegmentStart
.set _fontbankgothicSegmentStart, 0x102E7110
.global _fontbankgothicSegmentEnd
.set _fontbankgothicSegmentEnd, 0x102E95C0
.global _fontzurichboldSegmentRomStart
.set _fontzurichboldSegmentRomStart, 0x102E95C0
.global _fontzurichboldSegmentRomEnd
.set _fontzurichboldSegmentRomEnd, 0x102ECB00
.global _fontzurichboldSegmentStart
.set _fontzurichboldSegmentStart, 0x102E95C0
.global _fontzurichboldSegmentEnd
.set _fontzurichboldSegmentEnd, 0x102ECB00
.global _musicfilesSegmentRomStart
.set _musicfilesSegmentRomStart, 0x102ECB00
.global _musicfilesSegmentRomEnd
.set _musicfilesSegmentRomEnd, 0x10439380
.global _musicfilesSegmentStart
.set _musicfilesSegmentStart, 0x102ECB00
.global _musicfilesSegmentEnd
.set _musicfilesSegmentEnd, 0x10439380
.global _obsegSegmentRomStart
.set _obsegSegmentRomStart, 0x10439380
.global _obsegSegmentRomEnd
.set _obsegSegmentRomEnd, 0x108F9050
.global _obsegSegmentStart
.set _obsegSegmentStart, 0x10439380
.global _obsegSegmentEnd
.set _obsegSegmentEnd, 0x108F9050
.global _imagesSegmentRomStart
.set _imagesSegmentRomStart, 0x108F9050
.global _imagesSegmentRomEnd
.set _imagesSegmentRomEnd, 0x108F9050
.global _imagesSegmentStart
.set _imagesSegmentStart, 0x108F9050
.global _imagesSegmentEnd
.set _imagesSegmentEnd, 0x108F9050
.global _alt_startSegmentRomStart
.set _alt_startSegmentRomStart, 0x10101000
.global _alt_startSegmentStart
.set _alt_startSegmentStart, 0x10101000
