/*
 * AUTO-GENERATED by scripts/gen_romassets.py (U) -- do not edit.
 *
 * Absolute ROM asset symbols for the PC port. Each symbol is the N64
 * cart address (0x10000000 + rom_offset) of the corresponding asset in
 * scripts/filelist.u.csv, so `&symbol` / romCopy() work exactly as
 * on hardware once romdata.c has mapped the .z64 at 0x10000000.
 * Regenerate: python3 scripts/gen_romassets.py u
 */
.section .data

/* --- assets/obseg (file_resource_table.inc.c order) ------------- */
.global bg_sev_all_p_seg
.set bg_sev_all_p_seg, 0x10438660
.global end_bg_sev_all_p_seg
.set end_bg_sev_all_p_seg, 0x10449450
.global bg_silo_all_p_seg
.set bg_silo_all_p_seg, 0x10449450
.global end_bg_silo_all_p_seg
.set end_bg_silo_all_p_seg, 0x1049A390
.global bg_stat_all_p_seg
.set bg_stat_all_p_seg, 0x1049A390
.global end_bg_stat_all_p_seg
.set end_bg_stat_all_p_seg, 0x104BC460
.global bg_arec_all_p_seg
.set bg_arec_all_p_seg, 0x104BC460
.global end_bg_arec_all_p_seg
.set end_bg_arec_all_p_seg, 0x104EA7E0
.global bg_arch_all_p_seg
.set bg_arch_all_p_seg, 0x104EA7E0
.global end_bg_arch_all_p_seg
.set end_bg_arch_all_p_seg, 0x105102D0
.global bg_tra_all_p_seg
.set bg_tra_all_p_seg, 0x105102D0
.global end_bg_tra_all_p_seg
.set end_bg_tra_all_p_seg, 0x10530840
.global bg_dest_all_p_seg
.set bg_dest_all_p_seg, 0x10530840
.global end_bg_dest_all_p_seg
.set end_bg_dest_all_p_seg, 0x1055E200
.global bg_sevb_all_p_seg
.set bg_sevb_all_p_seg, 0x1055E200
.global end_bg_sevb_all_p_seg
.set end_bg_sevb_all_p_seg, 0x10578FA0
.global bg_azt_all_p_seg
.set bg_azt_all_p_seg, 0x10578FA0
.global end_bg_azt_all_p_seg
.set end_bg_azt_all_p_seg, 0x1059A9F0
.global bg_pete_all_p_seg
.set bg_pete_all_p_seg, 0x1059A9F0
.global end_bg_pete_all_p_seg
.set end_bg_pete_all_p_seg, 0x105B4620
.global bg_depo_all_p_seg
.set bg_depo_all_p_seg, 0x105B4620
.global end_bg_depo_all_p_seg
.set end_bg_depo_all_p_seg, 0x105E0F90
.global bg_ref_all_p_seg
.set bg_ref_all_p_seg, 0x105E0F90
.global end_bg_ref_all_p_seg
.set end_bg_ref_all_p_seg, 0x105EA5A0
.global bg_cryp_all_p_seg
.set bg_cryp_all_p_seg, 0x105EA5A0
.global end_bg_cryp_all_p_seg
.set end_bg_cryp_all_p_seg, 0x105FFC50
.global bg_dam_all_p_seg
.set bg_dam_all_p_seg, 0x105FFC50
.global end_bg_dam_all_p_seg
.set end_bg_dam_all_p_seg, 0x1062FDF0
.global bg_ark_all_p_seg
.set bg_ark_all_p_seg, 0x1062FDF0
.global end_bg_ark_all_p_seg
.set end_bg_ark_all_p_seg, 0x10660D70
.global bg_run_all_p_seg
.set bg_run_all_p_seg, 0x10660D70
.global end_bg_run_all_p_seg
.set end_bg_run_all_p_seg, 0x1066B140
.global bg_sevx_all_p_seg
.set bg_sevx_all_p_seg, 0x1066B140
.global end_bg_sevx_all_p_seg
.set end_bg_sevx_all_p_seg, 0x10687710
.global bg_jun_all_p_seg
.set bg_jun_all_p_seg, 0x10687710
.global end_bg_jun_all_p_seg
.set end_bg_jun_all_p_seg, 0x1069C860
.global bg_dish_all_p_seg
.set bg_dish_all_p_seg, 0x1069C860
.global end_bg_dish_all_p_seg
.set end_bg_dish_all_p_seg, 0x106A10D0
.global bg_cave_all_p_seg
.set bg_cave_all_p_seg, 0x106A10D0
.global end_bg_cave_all_p_seg
.set end_bg_cave_all_p_seg, 0x106C55C0
.global bg_cat_all_p_seg
.set bg_cat_all_p_seg, 0x106C55C0
.global end_bg_cat_all_p_seg
.set end_bg_cat_all_p_seg, 0x106CAAF0
.global bg_crad_all_p_seg
.set bg_crad_all_p_seg, 0x106CAAF0
.global end_bg_crad_all_p_seg
.set end_bg_crad_all_p_seg, 0x106DAE40
.global bg_sho_all_p_seg
.set bg_sho_all_p_seg, 0x106DAE40
.global end_bg_sho_all_p_seg
.set end_bg_sho_all_p_seg, 0x106DAE40
.global bg_imp_all_p_seg
.set bg_imp_all_p_seg, 0x106DAE40
.global end_bg_imp_all_p_seg
.set end_bg_imp_all_p_seg, 0x106DAE40
.global bg_rit_all_p_seg
.set bg_rit_all_p_seg, 0x106E4DA0
.global end_bg_rit_all_p_seg
.set end_bg_rit_all_p_seg, 0x106E4DA0
.global bg_oat_all_p_seg
.set bg_oat_all_p_seg, 0x106E4DA0
.global end_bg_oat_all_p_seg
.set end_bg_oat_all_p_seg, 0x106EBBF0
.global bg_ear_all_p_seg
.set bg_ear_all_p_seg, 0x106EBBF0
.global end_bg_ear_all_p_seg
.set end_bg_ear_all_p_seg, 0x106EBBF0
.global bg_lee_all_p_seg
.set bg_lee_all_p_seg, 0x106EBBF0
.global end_bg_lee_all_p_seg
.set end_bg_lee_all_p_seg, 0x106EBBF0
.global bg_lip_all_p_seg
.set bg_lip_all_p_seg, 0x106EBBF0
.global end_bg_lip_all_p_seg
.set end_bg_lip_all_p_seg, 0x106EBBF0
.global bg_len_all_p_seg
.set bg_len_all_p_seg, 0x106EBBF0
.global end_bg_len_all_p_seg
.set end_bg_len_all_p_seg, 0x106ECB90
.global bg_wax_all_p_seg
.set bg_wax_all_p_seg, 0x106ECB90
.global end_bg_wax_all_p_seg
.set end_bg_wax_all_p_seg, 0x106ECB90
.global bg_pam_all_p_seg
.set bg_pam_all_p_seg, 0x106ECB90
.global end_bg_pam_all_p_seg
.set end_bg_pam_all_p_seg, 0x106ECB90
.global CarmourguardZ
.set CarmourguardZ, 0x106ECB90
.global end_CarmourguardZ
.set end_CarmourguardZ, 0x106EF010
.global CbaronsamediZ
.set CbaronsamediZ, 0x106EF010
.global end_CbaronsamediZ
.set end_CbaronsamediZ, 0x106F2700
.global CbluecamguardZ
.set CbluecamguardZ, 0x106F2700
.global end_CbluecamguardZ
.set end_CbluecamguardZ, 0x106F4DF0
.global CbluemanZ
.set CbluemanZ, 0x106F4DF0
.global end_CbluemanZ
.set end_CbluemanZ, 0x106F6C00
.global CbluewomanZ
.set CbluewomanZ, 0x106F6C00
.global end_CbluewomanZ
.set end_CbluewomanZ, 0x106F8AC0
.global CboilerbondZ
.set CboilerbondZ, 0x106F8AC0
.global end_CboilerbondZ
.set end_CboilerbondZ, 0x106FB6D0
.global CboilertrevZ
.set CboilertrevZ, 0x106FB6D0
.global end_CboilertrevZ
.set end_CboilertrevZ, 0x106FED50
.global CborisZ
.set CborisZ, 0x106FED50
.global end_CborisZ
.set end_CborisZ, 0x10701E70
.global CcamguardZ
.set CcamguardZ, 0x10701E70
.global end_CcamguardZ
.set end_CcamguardZ, 0x10704550
.global CcardimanZ
.set CcardimanZ, 0x10704550
.global end_CcardimanZ
.set end_CcardimanZ, 0x10706350
.global CcheckmanZ
.set CcheckmanZ, 0x10706350
.global end_CcheckmanZ
.set end_CcheckmanZ, 0x107081D0
.global CcommguardZ
.set CcommguardZ, 0x107081D0
.global end_CcommguardZ
.set end_CcommguardZ, 0x1070A7D0
.global CdjbondZ
.set CdjbondZ, 0x1070A7D0
.global end_CdjbondZ
.set end_CdjbondZ, 0x1070D660
.global CfattechwomanZ
.set CfattechwomanZ, 0x1070D660
.global end_CfattechwomanZ
.set end_CfattechwomanZ, 0x1070F580
.global Cgreatguard2Z
.set Cgreatguard2Z, 0x1070F580
.global end_Cgreatguard2Z
.set end_Cgreatguard2Z, 0x10711CA0
.global CgreatguardZ
.set CgreatguardZ, 0x10711CA0
.global end_CgreatguardZ
.set end_CgreatguardZ, 0x10714320
.global CgreyguardZ
.set CgreyguardZ, 0x10714320
.global end_CgreyguardZ
.set end_CgreyguardZ, 0x107169F0
.global CgreymanZ
.set CgreymanZ, 0x107169F0
.global end_CgreymanZ
.set end_CgreymanZ, 0x107187B0
.global CheadalanZ
.set CheadalanZ, 0x107187B0
.global end_CheadalanZ
.set end_CheadalanZ, 0x10718D80
.global CheadbZ
.set CheadbZ, 0x10718D80
.global end_CheadbZ
.set end_CheadbZ, 0x107192F0
.global CheadbalaclavaZ
.set CheadbalaclavaZ, 0x107192F0
.global end_CheadbalaclavaZ
.set end_CheadbalaclavaZ, 0x107196C0
.global CheadbikeZ
.set CheadbikeZ, 0x107196C0
.global end_CheadbikeZ
.set end_CheadbikeZ, 0x10719D60
.global CheadbrosnanZ
.set CheadbrosnanZ, 0x10719D60
.global end_CheadbrosnanZ
.set end_CheadbrosnanZ, 0x1071AAB0
.global CheadbrosnanboilerZ
.set CheadbrosnanboilerZ, 0x1071AAB0
.global end_CheadbrosnanboilerZ
.set end_CheadbrosnanboilerZ, 0x1071B650
.global CheadbrosnansnowZ
.set CheadbrosnansnowZ, 0x1071B650
.global end_CheadbrosnansnowZ
.set end_CheadbrosnansnowZ, 0x1071C4D0
.global CheadbrosnansuitZ
.set CheadbrosnansuitZ, 0x1071C4D0
.global end_CheadbrosnansuitZ
.set end_CheadbrosnansuitZ, 0x1071D250
.global CheadbrosnantimberZ
.set CheadbrosnantimberZ, 0x1071D250
.global end_CheadbrosnantimberZ
.set end_CheadbrosnantimberZ, 0x1071DE10
.global CheadchrisZ
.set CheadchrisZ, 0x1071DE10
.global end_CheadchrisZ
.set end_CheadchrisZ, 0x1071E350
.global CheaddaveZ
.set CheaddaveZ, 0x1071E350
.global end_CheaddaveZ
.set end_CheaddaveZ, 0x1071E8D0
.global CheaddesZ
.set CheaddesZ, 0x1071E8D0
.global end_CheaddesZ
.set end_CheaddesZ, 0x1071EE00
.global CheadduncanZ
.set CheadduncanZ, 0x1071EE00
.global end_CheadduncanZ
.set end_CheadduncanZ, 0x1071F320
.global CheaddwayneZ
.set CheaddwayneZ, 0x1071F320
.global end_CheaddwayneZ
.set end_CheaddwayneZ, 0x1071F8A0
.global CheadgrahamZ
.set CheadgrahamZ, 0x1071F8A0
.global end_CheadgrahamZ
.set end_CheadgrahamZ, 0x1071FE10
.global CheadgrantZ
.set CheadgrantZ, 0x1071FE10
.global end_CheadgrantZ
.set end_CheadgrantZ, 0x10720340
.global CheadjimZ
.set CheadjimZ, 0x10720340
.global end_CheadjimZ
.set end_CheadjimZ, 0x10720870
.global Cheadjoe2Z
.set Cheadjoe2Z, 0x10720870
.global end_Cheadjoe2Z
.set end_Cheadjoe2Z, 0x10720C90
.global CheadjoeZ
.set CheadjoeZ, 0x10720C90
.global end_CheadjoeZ
.set end_CheadjoeZ, 0x10721200
.global CheadjoelZ
.set CheadjoelZ, 0x10721200
.global end_CheadjoelZ
.set end_CheadjoelZ, 0x10721710
.global CheadkarlZ
.set CheadkarlZ, 0x10721710
.global end_CheadkarlZ
.set end_CheadkarlZ, 0x10721C70
.global CheadkenZ
.set CheadkenZ, 0x10721C70
.global end_CheadkenZ
.set end_CheadkenZ, 0x107221C0
.global CheadleeZ
.set CheadleeZ, 0x107221C0
.global end_CheadleeZ
.set end_CheadleeZ, 0x10722740
.global CheadmandyZ
.set CheadmandyZ, 0x10722740
.global end_CheadmandyZ
.set end_CheadmandyZ, 0x10722B30
.global CheadmarionZ
.set CheadmarionZ, 0x10722B30
.global end_CheadmarionZ
.set end_CheadmarionZ, 0x10722F40
.global CheadmarkZ
.set CheadmarkZ, 0x10722F40
.global end_CheadmarkZ
.set end_CheadmarkZ, 0x10723470
.global CheadmartinZ
.set CheadmartinZ, 0x10723470
.global end_CheadmartinZ
.set end_CheadmartinZ, 0x107239D0
.global CheadmishkinZ
.set CheadmishkinZ, 0x107239D0
.global end_CheadmishkinZ
.set end_CheadmishkinZ, 0x10723F30
.global CheadneilZ
.set CheadneilZ, 0x10723F30
.global end_CheadneilZ
.set end_CheadneilZ, 0x10724450
.global CheadpeteZ
.set CheadpeteZ, 0x10724450
.global end_CheadpeteZ
.set end_CheadpeteZ, 0x107249E0
.global CheadrobinZ
.set CheadrobinZ, 0x107249E0
.global end_CheadrobinZ
.set end_CheadrobinZ, 0x10724EF0
.global CheadsallyZ
.set CheadsallyZ, 0x10724EF0
.global end_CheadsallyZ
.set end_CheadsallyZ, 0x107252F0
.global CheadscottZ
.set CheadscottZ, 0x107252F0
.global end_CheadscottZ
.set end_CheadscottZ, 0x10725870
.global CheadshaunZ
.set CheadshaunZ, 0x10725870
.global end_CheadshaunZ
.set end_CheadshaunZ, 0x10725E50
.global CheadsteveeZ
.set CheadsteveeZ, 0x10725E50
.global end_CheadsteveeZ
.set end_CheadsteveeZ, 0x107263A0
.global CheadstevehZ
.set CheadstevehZ, 0x107263A0
.global end_CheadstevehZ
.set end_CheadstevehZ, 0x107268F0
.global CheadvivienZ
.set CheadvivienZ, 0x107268F0
.global end_CheadvivienZ
.set end_CheadvivienZ, 0x10726D80
.global CjawsZ
.set CjawsZ, 0x10726D80
.global end_CjawsZ
.set end_CjawsZ, 0x107299C0
.global CjeanwomanZ
.set CjeanwomanZ, 0x107299C0
.global end_CjeanwomanZ
.set end_CjeanwomanZ, 0x1072B9D0
.global CmaydayZ
.set CmaydayZ, 0x1072B9D0
.global end_CmaydayZ
.set end_CmaydayZ, 0x1072E570
.global CmoonfemaleZ
.set CmoonfemaleZ, 0x1072E570
.global end_CmoonfemaleZ
.set end_CmoonfemaleZ, 0x107306C0
.global CmoonguardZ
.set CmoonguardZ, 0x107306C0
.global end_CmoonguardZ
.set end_CmoonguardZ, 0x10732CB0
.global CnatalyaZ
.set CnatalyaZ, 0x10732CB0
.global end_CnatalyaZ
.set end_CnatalyaZ, 0x10736570
.global CnavyguardZ
.set CnavyguardZ, 0x10736570
.global end_CnavyguardZ
.set end_CnavyguardZ, 0x10738C50
.global CoddjobZ
.set CoddjobZ, 0x10738C50
.global end_CoddjobZ
.set end_CoddjobZ, 0x1073BD80
.global ColiveguardZ
.set ColiveguardZ, 0x1073BD80
.global end_ColiveguardZ
.set end_ColiveguardZ, 0x1073E3D0
.global CorumovZ
.set CorumovZ, 0x1073E3D0
.global end_CorumovZ
.set end_CorumovZ, 0x10741800
.global CpilotZ
.set CpilotZ, 0x10741800
.global end_CpilotZ
.set end_CpilotZ, 0x10744880
.global CredmanZ
.set CredmanZ, 0x10744880
.global end_CredmanZ
.set end_CredmanZ, 0x10746FB0
.global CrusguardZ
.set CrusguardZ, 0x10746FB0
.global end_CrusguardZ
.set end_CrusguardZ, 0x10748BE0
.global CsnowbondZ
.set CsnowbondZ, 0x10748BE0
.global end_CsnowbondZ
.set end_CsnowbondZ, 0x1074BF10
.global CsnowguardZ
.set CsnowguardZ, 0x1074BF10
.global end_CsnowguardZ
.set end_CsnowguardZ, 0x1074EB90
.global CspicebondZ
.set CspicebondZ, 0x1074EB90
.global end_CspicebondZ
.set end_CspicebondZ, 0x107524B0
.global Csuit_lf_handZ
.set Csuit_lf_handZ, 0x107524B0
.global end_Csuit_lf_handZ
.set end_Csuit_lf_handZ, 0x107556D0
.global CsuitbondZ
.set CsuitbondZ, 0x107556D0
.global end_CsuitbondZ
.set end_CsuitbondZ, 0x10758460
.global CtechmanZ
.set CtechmanZ, 0x10758460
.global end_CtechmanZ
.set end_CtechmanZ, 0x1075AB10
.global CtechwomanZ
.set CtechwomanZ, 0x1075AB10
.global end_CtechwomanZ
.set end_CtechwomanZ, 0x1075CB00
.global CtimberbondZ
.set CtimberbondZ, 0x1075CB00
.global end_CtimberbondZ
.set end_CtimberbondZ, 0x1075F830
.global CtrevelyanZ
.set CtrevelyanZ, 0x1075F830
.global end_CtrevelyanZ
.set end_CtrevelyanZ, 0x10763000
.global CtrevguardZ
.set CtrevguardZ, 0x10763000
.global end_CtrevguardZ
.set end_CtrevguardZ, 0x10765610
.global CvalentinZ
.set CvalentinZ, 0x10765610
.global end_CvalentinZ
.set end_CvalentinZ, 0x10768580
.global CxeniaZ
.set CxeniaZ, 0x10768580
.global end_CxeniaZ
.set end_CxeniaZ, 0x1076BF70
.global Gak47Z
.set Gak47Z, 0x1076BF70
.global end_Gak47Z
.set end_Gak47Z, 0x1076C980
.global GaudiotapeZ
.set GaudiotapeZ, 0x1076C980
.global end_GaudiotapeZ
.set end_GaudiotapeZ, 0x1076CD10
.global GautoshotZ
.set GautoshotZ, 0x1076CD10
.global end_GautoshotZ
.set end_GautoshotZ, 0x1076E520
.global GblackboxZ
.set GblackboxZ, 0x1076E520
.global end_GblackboxZ
.set end_GblackboxZ, 0x1076EB20
.global GblueprintsZ
.set GblueprintsZ, 0x1076EB20
.global end_GblueprintsZ
.set end_GblueprintsZ, 0x1076EC20
.global GbombcaseZ
.set GbombcaseZ, 0x1076EC20
.global end_GbombcaseZ
.set end_GbombcaseZ, 0x1076F3B0
.global GbombdefuserZ
.set GbombdefuserZ, 0x1076F3B0
.global end_GbombdefuserZ
.set end_GbombdefuserZ, 0x1076F9A0
.global GbriefcaseZ
.set GbriefcaseZ, 0x1076F9A0
.global end_GbriefcaseZ
.set end_GbriefcaseZ, 0x10770130
.global GbugZ
.set GbugZ, 0x10770130
.global end_GbugZ
.set end_GbugZ, 0x10770AA0
.global GbugdetectorZ
.set GbugdetectorZ, 0x10770AA0
.global end_GbugdetectorZ
.set end_GbugdetectorZ, 0x10770DF0
.global GbungeeZ
.set GbungeeZ, 0x10770DF0
.global end_GbungeeZ
.set end_GbungeeZ, 0x10771140
.global GcameraZ
.set GcameraZ, 0x10771140
.global end_GcameraZ
.set end_GcameraZ, 0x107715C0
.global GcartblueZ
.set GcartblueZ, 0x107715C0
.global end_GcartblueZ
.set end_GcartblueZ, 0x10771820
.global GcartridgeZ
.set GcartridgeZ, 0x10771820
.global end_GcartridgeZ
.set end_GcartridgeZ, 0x10771950
.global GcartrifleZ
.set GcartrifleZ, 0x10771950
.global end_GcartrifleZ
.set end_GcartrifleZ, 0x10771B60
.global GcartshellZ
.set GcartshellZ, 0x10771B60
.global end_GcartshellZ
.set end_GcartshellZ, 0x10771D60
.global GcircuitboardZ
.set GcircuitboardZ, 0x10771D60
.global end_GcircuitboardZ
.set end_GcircuitboardZ, 0x10771EA0
.global GclipboardZ
.set GclipboardZ, 0x10771EA0
.global end_GclipboardZ
.set end_GclipboardZ, 0x10772090
.global GcreditcardZ
.set GcreditcardZ, 0x10772090
.global end_GcreditcardZ
.set end_GcreditcardZ, 0x107723E0
.global GdarkglassesZ
.set GdarkglassesZ, 0x107723E0
.global end_GdarkglassesZ
.set end_GdarkglassesZ, 0x10772730
.global GdatathiefZ
.set GdatathiefZ, 0x10772730
.global end_GdatathiefZ
.set end_GdatathiefZ, 0x10772870
.global GdattapeZ
.set GdattapeZ, 0x10772870
.global end_GdattapeZ
.set end_GdattapeZ, 0x107729E0
.global GdoordecoderZ
.set GdoordecoderZ, 0x107729E0
.global end_GdoordecoderZ
.set end_GdoordecoderZ, 0x10772F60
.global GdoorexploderZ
.set GdoorexploderZ, 0x10772F60
.global end_GdoorexploderZ
.set end_GdoorexploderZ, 0x107732B0
.global GdossierredZ
.set GdossierredZ, 0x107732B0
.global end_GdossierredZ
.set end_GdossierredZ, 0x10773610
.global GdynamiteZ
.set GdynamiteZ, 0x10773610
.global end_GdynamiteZ
.set end_GdynamiteZ, 0x10773960
.global GexplosivefloppyZ
.set GexplosivefloppyZ, 0x10773960
.global end_GexplosivefloppyZ
.set end_GexplosivefloppyZ, 0x10773BB0
.global GexplosivepenZ
.set GexplosivepenZ, 0x10773BB0
.global end_GexplosivepenZ
.set end_GexplosivepenZ, 0x10773F00
.global GextinguisherZ
.set GextinguisherZ, 0x10773F00
.global end_GextinguisherZ
.set end_GextinguisherZ, 0x107746F0
.global GfingergunZ
.set GfingergunZ, 0x107746F0
.global end_GfingergunZ
.set end_GfingergunZ, 0x10774A40
.global GfistZ
.set GfistZ, 0x10774A40
.global end_GfistZ
.set end_GfistZ, 0x10776140
.global GflarepistolZ
.set GflarepistolZ, 0x10776140
.global end_GflarepistolZ
.set end_GflarepistolZ, 0x10776490
.global Gfnp90Z
.set Gfnp90Z, 0x10776490
.global end_Gfnp90Z
.set end_Gfnp90Z, 0x10777130
.global GgaskeyringZ
.set GgaskeyringZ, 0x10777130
.global end_GgaskeyringZ
.set end_GgaskeyringZ, 0x10777B60
.global GgoldbarZ
.set GgoldbarZ, 0x10777B60
.global end_GgoldbarZ
.set end_GgoldbarZ, 0x10777EB0
.global GgoldeneyekeyZ
.set GgoldeneyekeyZ, 0x10777EB0
.global end_GgoldeneyekeyZ
.set end_GgoldeneyekeyZ, 0x10778860
.global GgoldengunZ
.set GgoldengunZ, 0x10778860
.global end_GgoldengunZ
.set end_GgoldengunZ, 0x1077A040
.global GgoldwppkZ
.set GgoldwppkZ, 0x1077A040
.global end_GgoldwppkZ
.set end_GgoldwppkZ, 0x1077B9A0
.global GgrenadeZ
.set GgrenadeZ, 0x1077B9A0
.global end_GgrenadeZ
.set end_GgrenadeZ, 0x1077C3D0
.global GgrenadelaunchZ
.set GgrenadelaunchZ, 0x1077C3D0
.global end_GgrenadelaunchZ
.set end_GgrenadelaunchZ, 0x1077D450
.global GheroinZ
.set GheroinZ, 0x1077D450
.global end_GheroinZ
.set end_GheroinZ, 0x1077D7A0
.global GjoypadZ
.set GjoypadZ, 0x1077D7A0
.global end_GjoypadZ
.set end_GjoypadZ, 0x1077F650
.global GkeyanalysercaseZ
.set GkeyanalysercaseZ, 0x1077F650
.global end_GkeyanalysercaseZ
.set end_GkeyanalysercaseZ, 0x1077FDE0
.global GkeyboltZ
.set GkeyboltZ, 0x1077FDE0
.global end_GkeyboltZ
.set end_GkeyboltZ, 0x107807D0
.global GkeycardZ
.set GkeycardZ, 0x107807D0
.global end_GkeycardZ
.set end_GkeycardZ, 0x10780900
.global GkeyyaleZ
.set GkeyyaleZ, 0x10780900
.global end_GkeyyaleZ
.set end_GkeyyaleZ, 0x10781650
.global GknifeZ
.set GknifeZ, 0x10781650
.global end_GknifeZ
.set end_GknifeZ, 0x10783120
.global GlaserZ
.set GlaserZ, 0x10783120
.global end_GlaserZ
.set end_GlaserZ, 0x10783F10
.global GlectreZ
.set GlectreZ, 0x10783F10
.global end_GlectreZ
.set end_GlectreZ, 0x10784260
.global GlockexploderZ
.set GlockexploderZ, 0x10784260
.global end_GlockexploderZ
.set end_GlockexploderZ, 0x107845B0
.global Gm16Z
.set Gm16Z, 0x107845B0
.global end_Gm16Z
.set end_Gm16Z, 0x10784FD0
.global GmapZ
.set GmapZ, 0x10784FD0
.global end_GmapZ
.set end_GmapZ, 0x107850C0
.global GmicrocameraZ
.set GmicrocameraZ, 0x107850C0
.global end_GmicrocameraZ
.set end_GmicrocameraZ, 0x10785700
.global GmicrocodeZ
.set GmicrocodeZ, 0x10785700
.global end_GmicrocodeZ
.set end_GmicrocodeZ, 0x10785A50
.global GmicrofilmZ
.set GmicrofilmZ, 0x10785A50
.global end_GmicrofilmZ
.set end_GmicrofilmZ, 0x10785DA0
.global GmoneyZ
.set GmoneyZ, 0x10785DA0
.global end_GmoneyZ
.set end_GmoneyZ, 0x107860F0
.global Gmp5kZ
.set Gmp5kZ, 0x107860F0
.global end_Gmp5kZ
.set end_Gmp5kZ, 0x10786CD0
.global Gmp5ksilZ
.set Gmp5ksilZ, 0x10786CD0
.global end_Gmp5ksilZ
.set end_Gmp5ksilZ, 0x107879D0
.global GpitongunZ
.set GpitongunZ, 0x107879D0
.global end_GpitongunZ
.set end_GpitongunZ, 0x10787D20
.global GplansZ
.set GplansZ, 0x10787D20
.global end_GplansZ
.set end_GplansZ, 0x10787EF0
.global GplastiqueZ
.set GplastiqueZ, 0x10787EF0
.global end_GplastiqueZ
.set end_GplastiqueZ, 0x10788240
.global GpolarizedglassesZ
.set GpolarizedglassesZ, 0x10788240
.global end_GpolarizedglassesZ
.set end_GpolarizedglassesZ, 0x107887A0
.global GproximitymineZ
.set GproximitymineZ, 0x107887A0
.global end_GproximitymineZ
.set end_GproximitymineZ, 0x10788F90
.global GremotemineZ
.set GremotemineZ, 0x10788F90
.global end_GremotemineZ
.set end_GremotemineZ, 0x10789950
.global GrocketlaunchZ
.set GrocketlaunchZ, 0x10789950
.global end_GrocketlaunchZ
.set end_GrocketlaunchZ, 0x1078AB70
.global GrugerZ
.set GrugerZ, 0x1078AB70
.global end_GrugerZ
.set end_GrugerZ, 0x1078C900
.global GsafecrackercaseZ
.set GsafecrackercaseZ, 0x1078C900
.global end_GsafecrackercaseZ
.set end_GsafecrackercaseZ, 0x1078D090
.global GshotgunZ
.set GshotgunZ, 0x1078D090
.global end_GshotgunZ
.set end_GshotgunZ, 0x1078DF70
.global GsilverwppkZ
.set GsilverwppkZ, 0x1078DF70
.global end_GsilverwppkZ
.set end_GsilverwppkZ, 0x1078F8D0
.global GskorpionZ
.set GskorpionZ, 0x1078F8D0
.global end_GskorpionZ
.set end_GskorpionZ, 0x10790AD0
.global GsniperrifleZ
.set GsniperrifleZ, 0x10790AD0
.global end_GsniperrifleZ
.set end_GsniperrifleZ, 0x10791B40
.global GspectreZ
.set GspectreZ, 0x10791B40
.global end_GspectreZ
.set end_GspectreZ, 0x107927C0
.global GspooltapeZ
.set GspooltapeZ, 0x107927C0
.global end_GspooltapeZ
.set end_GspooltapeZ, 0x10792B10
.global GspyfileZ
.set GspyfileZ, 0x10792B10
.global end_GspyfileZ
.set end_GspyfileZ, 0x10792E60
.global GstafflistZ
.set GstafflistZ, 0x10792E60
.global end_GstafflistZ
.set end_GstafflistZ, 0x10793000
.global GtaserZ
.set GtaserZ, 0x10793000
.global end_GtaserZ
.set end_GtaserZ, 0x10794E60
.global GthrowknifeZ
.set GthrowknifeZ, 0x10794E60
.global end_GthrowknifeZ
.set end_GthrowknifeZ, 0x10796950
.global GtimedmineZ
.set GtimedmineZ, 0x10796950
.global end_GtimedmineZ
.set end_GtimedmineZ, 0x10797410
.global GtriggerZ
.set GtriggerZ, 0x10797410
.global end_GtriggerZ
.set end_GtriggerZ, 0x1079A810
.global Gtt33Z
.set Gtt33Z, 0x1079A810
.global end_Gtt33Z
.set end_Gtt33Z, 0x1079C330
.global GuziZ
.set GuziZ, 0x1079C330
.global end_GuziZ
.set end_GuziZ, 0x1079CC40
.global GvideotapeZ
.set GvideotapeZ, 0x1079CC40
.global end_GvideotapeZ
.set end_GvideotapeZ, 0x1079CE50
.global GwatchcommunicatorZ
.set GwatchcommunicatorZ, 0x1079CE50
.global end_GwatchcommunicatorZ
.set end_GwatchcommunicatorZ, 0x1079E2B0
.global GwatchgeigercounterZ
.set GwatchgeigercounterZ, 0x1079E2B0
.global end_GwatchgeigercounterZ
.set end_GwatchgeigercounterZ, 0x1079F710
.global GwatchidentifierZ
.set GwatchidentifierZ, 0x1079F710
.global end_GwatchidentifierZ
.set end_GwatchidentifierZ, 0x107A0B70
.global GwatchlaserZ
.set GwatchlaserZ, 0x107A0B70
.global end_GwatchlaserZ
.set end_GwatchlaserZ, 0x107A3F70
.global GwatchmagnetattractZ
.set GwatchmagnetattractZ, 0x107A3F70
.global end_GwatchmagnetattractZ
.set end_GwatchmagnetattractZ, 0x107A53C0
.global GwatchmagnetrepelZ
.set GwatchmagnetrepelZ, 0x107A53C0
.global end_GwatchmagnetrepelZ
.set end_GwatchmagnetrepelZ, 0x107A6820
.global GweaponcaseZ
.set GweaponcaseZ, 0x107A6820
.global end_GweaponcaseZ
.set end_GweaponcaseZ, 0x107A6FB0
.global GwppkZ
.set GwppkZ, 0x107A6FB0
.global end_GwppkZ
.set end_GwppkZ, 0x107A8C40
.global GwppksilZ
.set GwppksilZ, 0x107A8C40
.global end_GwppksilZ
.set end_GwppksilZ, 0x107AA980
.global GwristdartZ
.set GwristdartZ, 0x107AA980
.global end_GwristdartZ
.set end_GwristdartZ, 0x107AACD0
.global PICBMZ
.set PICBMZ, 0x107AACD0
.global end_PICBMZ
.set end_PICBMZ, 0x107AD250
.global PICBM_noseZ
.set PICBM_noseZ, 0x107AD250
.global end_PICBM_noseZ
.set end_PICBM_noseZ, 0x107ADA00
.global Pak47magZ
.set Pak47magZ, 0x107ADA00
.global end_Pak47magZ
.set end_Pak47magZ, 0x107ADBE0
.global Palarm1Z
.set Palarm1Z, 0x107ADBE0
.global end_Palarm1Z
.set end_Palarm1Z, 0x107ADD40
.global Palarm2Z
.set Palarm2Z, 0x107ADD40
.global end_Palarm2Z
.set end_Palarm2Z, 0x107ADEE0
.global Pammo_crate1Z
.set Pammo_crate1Z, 0x107ADEE0
.global end_Pammo_crate1Z
.set end_Pammo_crate1Z, 0x107AE120
.global Pammo_crate2Z
.set Pammo_crate2Z, 0x107AE120
.global end_Pammo_crate2Z
.set end_Pammo_crate2Z, 0x107AE360
.global Pammo_crate3Z
.set Pammo_crate3Z, 0x107AE360
.global end_Pammo_crate3Z
.set end_Pammo_crate3Z, 0x107AE5B0
.global Pammo_crate4Z
.set Pammo_crate4Z, 0x107AE5B0
.global end_Pammo_crate4Z
.set end_Pammo_crate4Z, 0x107AE820
.global Pammo_crate5Z
.set Pammo_crate5Z, 0x107AE820
.global end_Pammo_crate5Z
.set end_Pammo_crate5Z, 0x107AEAE0
.global PapcZ
.set PapcZ, 0x107AEAE0
.global end_PapcZ
.set end_PapcZ, 0x107B0740
.global Parchsecdoor1Z
.set Parchsecdoor1Z, 0x107B0740
.global end_Parchsecdoor1Z
.set end_Parchsecdoor1Z, 0x107B0920
.global Parchsecdoor2Z
.set Parchsecdoor2Z, 0x107B0920
.global end_Parchsecdoor2Z
.set end_Parchsecdoor2Z, 0x107B0AF0
.global ParticZ
.set ParticZ, 0x107B0AF0
.global end_ParticZ
.set end_ParticZ, 0x107B18F0
.global PartictrailerZ
.set PartictrailerZ, 0x107B18F0
.global end_PartictrailerZ
.set end_PartictrailerZ, 0x107B2200
.global PbarricadeZ
.set PbarricadeZ, 0x107B2200
.global end_PbarricadeZ
.set end_PbarricadeZ, 0x107B2440
.global Pbin1Z
.set Pbin1Z, 0x107B2440
.global end_Pbin1Z
.set end_Pbin1Z, 0x107B2790
.global Pblotter1Z
.set Pblotter1Z, 0x107B2790
.global end_Pblotter1Z
.set end_Pblotter1Z, 0x107B2870
.global PbodyarmourZ
.set PbodyarmourZ, 0x107B2870
.global end_PbodyarmourZ
.set end_PbodyarmourZ, 0x107B2D10
.global PbodyarmourvestZ
.set PbodyarmourvestZ, 0x107B2D10
.global end_PbodyarmourvestZ
.set end_PbodyarmourvestZ, 0x107B3130
.global PbollardZ
.set PbollardZ, 0x107B3130
.global end_PbollardZ
.set end_PbollardZ, 0x107B3330
.global PbombZ
.set PbombZ, 0x107B3330
.global end_PbombZ
.set end_PbombZ, 0x107B34A0
.global Pbook1Z
.set Pbook1Z, 0x107B34A0
.global end_Pbook1Z
.set end_Pbook1Z, 0x107B3630
.global Pbookshelf1Z
.set Pbookshelf1Z, 0x107B3630
.global end_Pbookshelf1Z
.set end_Pbookshelf1Z, 0x107B3D20
.global Pborg_crateZ
.set Pborg_crateZ, 0x107B3D20
.global end_Pborg_crateZ
.set end_Pborg_crateZ, 0x107B3E90
.global PboxcartridgesZ
.set PboxcartridgesZ, 0x107B3E90
.global end_PboxcartridgesZ
.set end_PboxcartridgesZ, 0x107B4090
.global Pboxes2x4Z
.set Pboxes2x4Z, 0x107B4090
.global end_Pboxes2x4Z
.set end_Pboxes2x4Z, 0x107B44C0
.global Pboxes3x4Z
.set Pboxes3x4Z, 0x107B44C0
.global end_Pboxes3x4Z
.set end_Pboxes3x4Z, 0x107B4900
.global Pboxes4x4Z
.set Pboxes4x4Z, 0x107B4900
.global end_Pboxes4x4Z
.set end_Pboxes4x4Z, 0x107B4F60
.global PbrakeunitZ
.set PbrakeunitZ, 0x107B4F60
.global end_PbrakeunitZ
.set end_PbrakeunitZ, 0x107B52D0
.global Pbridge_console1aZ
.set Pbridge_console1aZ, 0x107B52D0
.global end_Pbridge_console1aZ
.set end_Pbridge_console1aZ, 0x107B5850
.global Pbridge_console1bZ
.set Pbridge_console1bZ, 0x107B5850
.global end_Pbridge_console1bZ
.set end_Pbridge_console1bZ, 0x107B5DB0
.global Pbridge_console2aZ
.set Pbridge_console2aZ, 0x107B5DB0
.global end_Pbridge_console2aZ
.set end_Pbridge_console2aZ, 0x107B6330
.global Pbridge_console2bZ
.set Pbridge_console2bZ, 0x107B6330
.global end_Pbridge_console2bZ
.set end_Pbridge_console2bZ, 0x107B6820
.global Pbridge_console3aZ
.set Pbridge_console3aZ, 0x107B6820
.global end_Pbridge_console3aZ
.set end_Pbridge_console3aZ, 0x107B6D70
.global Pbridge_console3bZ
.set Pbridge_console3bZ, 0x107B6D70
.global end_Pbridge_console3bZ
.set end_Pbridge_console3bZ, 0x107B7300
.global PcarbmwZ
.set PcarbmwZ, 0x107B7300
.global end_PcarbmwZ
.set end_PcarbmwZ, 0x107B7FE0
.global Pcard_box1Z
.set Pcard_box1Z, 0x107B7FE0
.global end_Pcard_box1Z
.set end_Pcard_box1Z, 0x107B81E0
.global Pcard_box2Z
.set Pcard_box2Z, 0x107B81E0
.global end_Pcard_box2Z
.set end_Pcard_box2Z, 0x107B8420
.global Pcard_box3Z
.set Pcard_box3Z, 0x107B8420
.global end_Pcard_box3Z
.set end_Pcard_box3Z, 0x107B8610
.global Pcard_box4_lgZ
.set Pcard_box4_lgZ, 0x107B8610
.global end_Pcard_box4_lgZ
.set end_Pcard_box4_lgZ, 0x107B87C0
.global Pcard_box5_lgZ
.set Pcard_box5_lgZ, 0x107B87C0
.global end_Pcard_box5_lgZ
.set end_Pcard_box5_lgZ, 0x107B89C0
.global Pcard_box6_lgZ
.set Pcard_box6_lgZ, 0x107B89C0
.global end_Pcard_box6_lgZ
.set end_Pcard_box6_lgZ, 0x107B8BB0
.global PcarescortZ
.set PcarescortZ, 0x107B8BB0
.global end_PcarescortZ
.set end_PcarescortZ, 0x107B97B0
.global PcargolfZ
.set PcargolfZ, 0x107B97B0
.global end_PcargolfZ
.set end_PcargolfZ, 0x107BA3E0
.global PcarweirdZ
.set PcarweirdZ, 0x107BA3E0
.global end_PcarweirdZ
.set end_PcarweirdZ, 0x107BB520
.global PcarzilZ
.set PcarzilZ, 0x107BB520
.global end_PcarzilZ
.set end_PcarzilZ, 0x107BCB20
.global PcctvZ
.set PcctvZ, 0x107BCB20
.global end_PcctvZ
.set end_PcctvZ, 0x107BCEA0
.global PchraudiotapeZ
.set PchraudiotapeZ, 0x107BCEA0
.global end_PchraudiotapeZ
.set end_PchraudiotapeZ, 0x107BD400
.global PchrautoshotZ
.set PchrautoshotZ, 0x107BD400
.global end_PchrautoshotZ
.set end_PchrautoshotZ, 0x107BD760
.global PchrblackboxZ
.set PchrblackboxZ, 0x107BD760
.global end_PchrblackboxZ
.set end_PchrblackboxZ, 0x107BDFE0
.global PchrblueprintsZ
.set PchrblueprintsZ, 0x107BDFE0
.global end_PchrblueprintsZ
.set end_PchrblueprintsZ, 0x107BE130
.global PchrbombcaseZ
.set PchrbombcaseZ, 0x107BE130
.global end_PchrbombcaseZ
.set end_PchrbombcaseZ, 0x107BE320
.global PchrbombdefuserZ
.set PchrbombdefuserZ, 0x107BE320
.global end_PchrbombdefuserZ
.set end_PchrbombdefuserZ, 0x107BEC00
.global PchrbriefcaseZ
.set PchrbriefcaseZ, 0x107BEC00
.global end_PchrbriefcaseZ
.set end_PchrbriefcaseZ, 0x107BED90
.global PchrbugZ
.set PchrbugZ, 0x107BED90
.global end_PchrbugZ
.set end_PchrbugZ, 0x107BFB40
.global PchrbugdetectorZ
.set PchrbugdetectorZ, 0x107BFB40
.global end_PchrbugdetectorZ
.set end_PchrbugdetectorZ, 0x107BFCB0
.global PchrbungeeZ
.set PchrbungeeZ, 0x107BFCB0
.global end_PchrbungeeZ
.set end_PchrbungeeZ, 0x107BFE20
.global PchrcameraZ
.set PchrcameraZ, 0x107BFE20
.global end_PchrcameraZ
.set end_PchrcameraZ, 0x107C04B0
.global PchrcircuitboardZ
.set PchrcircuitboardZ, 0x107C04B0
.global end_PchrcircuitboardZ
.set end_PchrcircuitboardZ, 0x107C0650
.global PchrclipboardZ
.set PchrclipboardZ, 0x107C0650
.global end_PchrclipboardZ
.set end_PchrclipboardZ, 0x107C08D0
.global PchrcreditcardZ
.set PchrcreditcardZ, 0x107C08D0
.global end_PchrcreditcardZ
.set end_PchrcreditcardZ, 0x107C0A40
.global PchrdarkglassesZ
.set PchrdarkglassesZ, 0x107C0A40
.global end_PchrdarkglassesZ
.set end_PchrdarkglassesZ, 0x107C0BB0
.global PchrdatathiefZ
.set PchrdatathiefZ, 0x107C0BB0
.global end_PchrdatathiefZ
.set end_PchrdatathiefZ, 0x107C0D50
.global PchrdattapeZ
.set PchrdattapeZ, 0x107C0D50
.global end_PchrdattapeZ
.set end_PchrdattapeZ, 0x107C0F40
.global PchrdoordecoderZ
.set PchrdoordecoderZ, 0x107C0F40
.global end_PchrdoordecoderZ
.set end_PchrdoordecoderZ, 0x107C17A0
.global PchrdoorexploderZ
.set PchrdoorexploderZ, 0x107C17A0
.global end_PchrdoorexploderZ
.set end_PchrdoorexploderZ, 0x107C1910
.global PchrdossierredZ
.set PchrdossierredZ, 0x107C1910
.global end_PchrdossierredZ
.set end_PchrdossierredZ, 0x107C1DE0
.global PchrdynamiteZ
.set PchrdynamiteZ, 0x107C1DE0
.global end_PchrdynamiteZ
.set end_PchrdynamiteZ, 0x107C1F50
.global PchrexplosivepenZ
.set PchrexplosivepenZ, 0x107C1F50
.global end_PchrexplosivepenZ
.set end_PchrexplosivepenZ, 0x107C20C0
.global PchrextinguisherZ
.set PchrextinguisherZ, 0x107C20C0
.global end_PchrextinguisherZ
.set end_PchrextinguisherZ, 0x107C25C0
.global PchrfingergunZ
.set PchrfingergunZ, 0x107C25C0
.global end_PchrfingergunZ
.set end_PchrfingergunZ, 0x107C2730
.global PchrflarepistolZ
.set PchrflarepistolZ, 0x107C2730
.global end_PchrflarepistolZ
.set end_PchrflarepistolZ, 0x107C28A0
.global Pchrfnp90Z
.set Pchrfnp90Z, 0x107C28A0
.global end_Pchrfnp90Z
.set end_Pchrfnp90Z, 0x107C2D00
.global PchrgaskeyringZ
.set PchrgaskeyringZ, 0x107C2D00
.global end_PchrgaskeyringZ
.set end_PchrgaskeyringZ, 0x107C3C10
.global PchrgoldbarZ
.set PchrgoldbarZ, 0x107C3C10
.global end_PchrgoldbarZ
.set end_PchrgoldbarZ, 0x107C3D80
.global PchrgoldenZ
.set PchrgoldenZ, 0x107C3D80
.global end_PchrgoldenZ
.set end_PchrgoldenZ, 0x107C3FF0
.global PchrgoldeneyekeyZ
.set PchrgoldeneyekeyZ, 0x107C3FF0
.global end_PchrgoldeneyekeyZ
.set end_PchrgoldeneyekeyZ, 0x107C4E90
.global PchrgoldwppkZ
.set PchrgoldwppkZ, 0x107C4E90
.global end_PchrgoldwppkZ
.set end_PchrgoldwppkZ, 0x107C5000
.global PchrgrenadeZ
.set PchrgrenadeZ, 0x107C5000
.global end_PchrgrenadeZ
.set end_PchrgrenadeZ, 0x107C5370
.global PchrgrenadelaunchZ
.set PchrgrenadelaunchZ, 0x107C5370
.global end_PchrgrenadelaunchZ
.set end_PchrgrenadelaunchZ, 0x107C5700
.global PchrgrenaderoundZ
.set PchrgrenaderoundZ, 0x107C5700
.global end_PchrgrenaderoundZ
.set end_PchrgrenaderoundZ, 0x107C5970
.global PchrheroinZ
.set PchrheroinZ, 0x107C5970
.global end_PchrheroinZ
.set end_PchrheroinZ, 0x107C5AE0
.global PchrkalashZ
.set PchrkalashZ, 0x107C5AE0
.global end_PchrkalashZ
.set end_PchrkalashZ, 0x107C5ED0
.global PchrkeyanalysercaseZ
.set PchrkeyanalysercaseZ, 0x107C5ED0
.global end_PchrkeyanalysercaseZ
.set end_PchrkeyanalysercaseZ, 0x107C60C0
.global PchrkeyboltZ
.set PchrkeyboltZ, 0x107C60C0
.global end_PchrkeyboltZ
.set end_PchrkeyboltZ, 0x107C6F60
.global PchrkeyyaleZ
.set PchrkeyyaleZ, 0x107C6F60
.global end_PchrkeyyaleZ
.set end_PchrkeyyaleZ, 0x107C83C0
.global PchrknifeZ
.set PchrknifeZ, 0x107C83C0
.global end_PchrknifeZ
.set end_PchrknifeZ, 0x107C85C0
.global PchrlaserZ
.set PchrlaserZ, 0x107C85C0
.global end_PchrlaserZ
.set end_PchrlaserZ, 0x107C8980
.global PchrlectreZ
.set PchrlectreZ, 0x107C8980
.global end_PchrlectreZ
.set end_PchrlectreZ, 0x107C8AF0
.global PchrlockexploderZ
.set PchrlockexploderZ, 0x107C8AF0
.global end_PchrlockexploderZ
.set end_PchrlockexploderZ, 0x107C8C60
.global Pchrm16Z
.set Pchrm16Z, 0x107C8C60
.global end_Pchrm16Z
.set end_Pchrm16Z, 0x107C9030
.global PchrmapZ
.set PchrmapZ, 0x107C9030
.global end_PchrmapZ
.set end_PchrmapZ, 0x107C9180
.global PchrmicrocameraZ
.set PchrmicrocameraZ, 0x107C9180
.global end_PchrmicrocameraZ
.set end_PchrmicrocameraZ, 0x107C9A70
.global PchrmicrocodeZ
.set PchrmicrocodeZ, 0x107C9A70
.global end_PchrmicrocodeZ
.set end_PchrmicrocodeZ, 0x107C9BE0
.global PchrmicrofilmZ
.set PchrmicrofilmZ, 0x107C9BE0
.global end_PchrmicrofilmZ
.set end_PchrmicrofilmZ, 0x107C9D50
.global PchrmoneyZ
.set PchrmoneyZ, 0x107C9D50
.global end_PchrmoneyZ
.set end_PchrmoneyZ, 0x107C9EC0
.global Pchrmp5kZ
.set Pchrmp5kZ, 0x107C9EC0
.global end_Pchrmp5kZ
.set end_Pchrmp5kZ, 0x107CA240
.global Pchrmp5ksilZ
.set Pchrmp5ksilZ, 0x107CA240
.global end_Pchrmp5ksilZ
.set end_Pchrmp5ksilZ, 0x107CA650
.global PchrpitongunZ
.set PchrpitongunZ, 0x107CA650
.global end_PchrpitongunZ
.set end_PchrpitongunZ, 0x107CA7C0
.global PchrplansZ
.set PchrplansZ, 0x107CA7C0
.global end_PchrplansZ
.set end_PchrplansZ, 0x107CAA50
.global PchrplastiqueZ
.set PchrplastiqueZ, 0x107CAA50
.global end_PchrplastiqueZ
.set end_PchrplastiqueZ, 0x107CAEB0
.global PchrpolarizedglassesZ
.set PchrpolarizedglassesZ, 0x107CAEB0
.global end_PchrpolarizedglassesZ
.set end_PchrpolarizedglassesZ, 0x107CB770
.global PchrproximitymineZ
.set PchrproximitymineZ, 0x107CB770
.global end_PchrproximitymineZ
.set end_PchrproximitymineZ, 0x107CBBD0
.global PchrremotemineZ
.set PchrremotemineZ, 0x107CBBD0
.global end_PchrremotemineZ
.set end_PchrremotemineZ, 0x107CC030
.global PchrrocketZ
.set PchrrocketZ, 0x107CC030
.global end_PchrrocketZ
.set end_PchrrocketZ, 0x107CC5E0
.global PchrrocketlaunchZ
.set PchrrocketlaunchZ, 0x107CC5E0
.global end_PchrrocketlaunchZ
.set end_PchrrocketlaunchZ, 0x107CC9C0
.global PchrrugerZ
.set PchrrugerZ, 0x107CC9C0
.global end_PchrrugerZ
.set end_PchrrugerZ, 0x107CCDA0
.global PchrsafecrackercaseZ
.set PchrsafecrackercaseZ, 0x107CCDA0
.global end_PchrsafecrackercaseZ
.set end_PchrsafecrackercaseZ, 0x107CCF90
.global PchrshotgunZ
.set PchrshotgunZ, 0x107CCF90
.global end_PchrshotgunZ
.set end_PchrshotgunZ, 0x107CD2E0
.global PchrsilverwppkZ
.set PchrsilverwppkZ, 0x107CD2E0
.global end_PchrsilverwppkZ
.set end_PchrsilverwppkZ, 0x107CD450
.global PchrskorpionZ
.set PchrskorpionZ, 0x107CD450
.global end_PchrskorpionZ
.set end_PchrskorpionZ, 0x107CD7D0
.global PchrsniperrifleZ
.set PchrsniperrifleZ, 0x107CD7D0
.global end_PchrsniperrifleZ
.set end_PchrsniperrifleZ, 0x107CDB60
.global PchrspectreZ
.set PchrspectreZ, 0x107CDB60
.global end_PchrspectreZ
.set end_PchrspectreZ, 0x107CDED0
.global PchrspooltapeZ
.set PchrspooltapeZ, 0x107CDED0
.global end_PchrspooltapeZ
.set end_PchrspooltapeZ, 0x107CE040
.global PchrspyfileZ
.set PchrspyfileZ, 0x107CE040
.global end_PchrspyfileZ
.set end_PchrspyfileZ, 0x107CE1B0
.global PchrstafflistZ
.set PchrstafflistZ, 0x107CE1B0
.global end_PchrstafflistZ
.set end_PchrstafflistZ, 0x107CE3D0
.global PchrtesttubeZ
.set PchrtesttubeZ, 0x107CE3D0
.global end_PchrtesttubeZ
.set end_PchrtesttubeZ, 0x107CE590
.global PchrthrowknifeZ
.set PchrthrowknifeZ, 0x107CE590
.global end_PchrthrowknifeZ
.set end_PchrthrowknifeZ, 0x107CE7B0
.global PchrtimedmineZ
.set PchrtimedmineZ, 0x107CE7B0
.global end_PchrtimedmineZ
.set end_PchrtimedmineZ, 0x107CECE0
.global Pchrtt33Z
.set Pchrtt33Z, 0x107CECE0
.global end_Pchrtt33Z
.set end_Pchrtt33Z, 0x107CEF70
.global PchruziZ
.set PchruziZ, 0x107CEF70
.global end_PchruziZ
.set end_PchruziZ, 0x107CF240
.global PchrvideotapeZ
.set PchrvideotapeZ, 0x107CF240
.global end_PchrvideotapeZ
.set end_PchrvideotapeZ, 0x107CF510
.global PchrweaponcaseZ
.set PchrweaponcaseZ, 0x107CF510
.global end_PchrweaponcaseZ
.set end_PchrweaponcaseZ, 0x107CF710
.global PchrwppkZ
.set PchrwppkZ, 0x107CF710
.global end_PchrwppkZ
.set end_PchrwppkZ, 0x107CF950
.global PchrwppksilZ
.set PchrwppksilZ, 0x107CF950
.global end_PchrwppksilZ
.set end_PchrwppksilZ, 0x107CFC30
.global PchrwristdartZ
.set PchrwristdartZ, 0x107CFC30
.global end_PchrwristdartZ
.set end_PchrwristdartZ, 0x107CFDA0
.global Pconsole1Z
.set Pconsole1Z, 0x107CFDA0
.global end_Pconsole1Z
.set end_Pconsole1Z, 0x107D0420
.global Pconsole2Z
.set Pconsole2Z, 0x107D0420
.global end_Pconsole2Z
.set end_Pconsole2Z, 0x107D0AA0
.global Pconsole3Z
.set Pconsole3Z, 0x107D0AA0
.global end_Pconsole3Z
.set end_Pconsole3Z, 0x107D1130
.global Pconsole_sev2aZ
.set Pconsole_sev2aZ, 0x107D1130
.global end_Pconsole_sev2aZ
.set end_Pconsole_sev2aZ, 0x107D1550
.global Pconsole_sev2bZ
.set Pconsole_sev2bZ, 0x107D1550
.global end_Pconsole_sev2bZ
.set end_Pconsole_sev2bZ, 0x107D1A10
.global Pconsole_sev2cZ
.set Pconsole_sev2cZ, 0x107D1A10
.global end_Pconsole_sev2cZ
.set end_Pconsole_sev2cZ, 0x107D1E50
.global Pconsole_sev2dZ
.set Pconsole_sev2dZ, 0x107D1E50
.global end_Pconsole_sev2dZ
.set end_Pconsole_sev2dZ, 0x107D2280
.global Pconsole_sev_GEaZ
.set Pconsole_sev_GEaZ, 0x107D2280
.global end_Pconsole_sev_GEaZ
.set end_Pconsole_sev_GEaZ, 0x107D26B0
.global Pconsole_sev_GEbZ
.set Pconsole_sev_GEbZ, 0x107D26B0
.global end_Pconsole_sev_GEbZ
.set end_Pconsole_sev_GEbZ, 0x107D2AE0
.global Pconsole_sevaZ
.set Pconsole_sevaZ, 0x107D2AE0
.global end_Pconsole_sevaZ
.set end_Pconsole_sevaZ, 0x107D2F60
.global Pconsole_sevbZ
.set Pconsole_sevbZ, 0x107D2F60
.global end_Pconsole_sevbZ
.set end_Pconsole_sevbZ, 0x107D33D0
.global Pconsole_sevcZ
.set Pconsole_sevcZ, 0x107D33D0
.global end_Pconsole_sevcZ
.set end_Pconsole_sevcZ, 0x107D3800
.global Pconsole_sevdZ
.set Pconsole_sevdZ, 0x107D3800
.global end_Pconsole_sevdZ
.set end_Pconsole_sevdZ, 0x107D3C30
.global Pcryptdoor1aZ
.set Pcryptdoor1aZ, 0x107D3C30
.global end_Pcryptdoor1aZ
.set end_Pcryptdoor1aZ, 0x107D3DC0
.global Pcryptdoor1bZ
.set Pcryptdoor1bZ, 0x107D3DC0
.global end_Pcryptdoor1bZ
.set end_Pcryptdoor1bZ, 0x107D3F50
.global Pcryptdoor2aZ
.set Pcryptdoor2aZ, 0x107D3F50
.global end_Pcryptdoor2aZ
.set end_Pcryptdoor2aZ, 0x107D40E0
.global Pcryptdoor2bZ
.set Pcryptdoor2bZ, 0x107D40E0
.global end_Pcryptdoor2bZ
.set end_Pcryptdoor2bZ, 0x107D4270
.global Pcryptdoor3Z
.set Pcryptdoor3Z, 0x107D4270
.global end_Pcryptdoor3Z
.set end_Pcryptdoor3Z, 0x107D44E0
.global Pcryptdoor4Z
.set Pcryptdoor4Z, 0x107D44E0
.global end_Pcryptdoor4Z
.set end_Pcryptdoor4Z, 0x107D4660
.global PdamchaindoorZ
.set PdamchaindoorZ, 0x107D4660
.global end_PdamchaindoorZ
.set end_PdamchaindoorZ, 0x107D48E0
.global PdamgatedoorZ
.set PdamgatedoorZ, 0x107D48E0
.global end_PdamgatedoorZ
.set end_PdamgatedoorZ, 0x107D4B00
.global PdamtundoorZ
.set PdamtundoorZ, 0x107D4B00
.global end_PdamtundoorZ
.set end_PdamtundoorZ, 0x107D4E70
.global Pdepot_door_steelZ
.set Pdepot_door_steelZ, 0x107D4E70
.global end_Pdepot_door_steelZ
.set end_Pdepot_door_steelZ, 0x107D5010
.global Pdepot_gate_entryZ
.set Pdepot_gate_entryZ, 0x107D5010
.global end_Pdepot_gate_entryZ
.set end_Pdepot_gate_entryZ, 0x107D5250
.global Pdesk1Z
.set Pdesk1Z, 0x107D5250
.global end_Pdesk1Z
.set end_Pdesk1Z, 0x107D53D0
.global Pdesk2Z
.set Pdesk2Z, 0x107D53D0
.global end_Pdesk2Z
.set end_Pdesk2Z, 0x107D5550
.global Pdesk_arecibo1Z
.set Pdesk_arecibo1Z, 0x107D5550
.global end_Pdesk_arecibo1Z
.set end_Pdesk_arecibo1Z, 0x107D5790
.global Pdesk_lamp2Z
.set Pdesk_lamp2Z, 0x107D5790
.global end_Pdesk_lamp2Z
.set end_Pdesk_lamp2Z, 0x107D5A90
.global Pdest_engineZ
.set Pdest_engineZ, 0x107D5A90
.global end_Pdest_engineZ
.set end_Pdest_engineZ, 0x107D7380
.global Pdest_exocetZ
.set Pdest_exocetZ, 0x107D7380
.global end_Pdest_exocetZ
.set end_Pdest_exocetZ, 0x107D79E0
.global Pdest_gunZ
.set Pdest_gunZ, 0x107D79E0
.global end_Pdest_gunZ
.set end_Pdest_gunZ, 0x107D8050
.global Pdest_harpoonZ
.set Pdest_harpoonZ, 0x107D8050
.global end_Pdest_harpoonZ
.set end_Pdest_harpoonZ, 0x107D88F0
.global Pdest_seawolfZ
.set Pdest_seawolfZ, 0x107D88F0
.global end_Pdest_seawolfZ
.set end_Pdest_seawolfZ, 0x107D98A0
.global Pdisc_readerZ
.set Pdisc_readerZ, 0x107D98A0
.global end_Pdisc_readerZ
.set end_Pdisc_readerZ, 0x107D9A60
.global Pdisk_drive1Z
.set Pdisk_drive1Z, 0x107D9A60
.global end_Pdisk_drive1Z
.set end_Pdisk_drive1Z, 0x107D9BF0
.global Pdoor_azt_chairZ
.set Pdoor_azt_chairZ, 0x107D9BF0
.global end_Pdoor_azt_chairZ
.set end_Pdoor_azt_chairZ, 0x107D9D70
.global Pdoor_azt_deskZ
.set Pdoor_azt_deskZ, 0x107D9D70
.global end_Pdoor_azt_deskZ
.set end_Pdoor_azt_deskZ, 0x107DA1B0
.global Pdoor_azt_desk_topZ
.set Pdoor_azt_desk_topZ, 0x107DA1B0
.global end_Pdoor_azt_desk_topZ
.set end_Pdoor_azt_desk_topZ, 0x107DA540
.global Pdoor_aztecZ
.set Pdoor_aztecZ, 0x107DA540
.global end_Pdoor_aztecZ
.set end_Pdoor_aztecZ, 0x107DA770
.global Pdoor_dest1Z
.set Pdoor_dest1Z, 0x107DA770
.global end_Pdoor_dest1Z
.set end_Pdoor_dest1Z, 0x107DAA70
.global Pdoor_dest2Z
.set Pdoor_dest2Z, 0x107DAA70
.global end_Pdoor_dest2Z
.set end_Pdoor_dest2Z, 0x107DAE30
.global Pdoor_eyelidZ
.set Pdoor_eyelidZ, 0x107DAE30
.global end_Pdoor_eyelidZ
.set end_Pdoor_eyelidZ, 0x107DB390
.global Pdoor_irisZ
.set Pdoor_irisZ, 0x107DB390
.global end_Pdoor_irisZ
.set end_Pdoor_irisZ, 0x107DBDE0
.global Pdoor_mfZ
.set Pdoor_mfZ, 0x107DBDE0
.global end_Pdoor_mfZ
.set end_Pdoor_mfZ, 0x107DC0D0
.global Pdoor_roller1Z
.set Pdoor_roller1Z, 0x107DC0D0
.global end_Pdoor_roller1Z
.set end_Pdoor_roller1Z, 0x107DC440
.global Pdoor_roller2Z
.set Pdoor_roller2Z, 0x107DC440
.global end_Pdoor_roller2Z
.set end_Pdoor_roller2Z, 0x107DC680
.global Pdoor_roller3Z
.set Pdoor_roller3Z, 0x107DC680
.global end_Pdoor_roller3Z
.set end_Pdoor_roller3Z, 0x107DC8C0
.global Pdoor_roller4Z
.set Pdoor_roller4Z, 0x107DC8C0
.global end_Pdoor_roller4Z
.set end_Pdoor_roller4Z, 0x107DCB20
.global Pdoor_rollertrainZ
.set Pdoor_rollertrainZ, 0x107DCB20
.global end_Pdoor_rollertrainZ
.set end_Pdoor_rollertrainZ, 0x107DCC50
.global Pdoor_st_arec1Z
.set Pdoor_st_arec1Z, 0x107DCC50
.global end_Pdoor_st_arec1Z
.set end_Pdoor_st_arec1Z, 0x107DCEB0
.global Pdoor_st_arec2Z
.set Pdoor_st_arec2Z, 0x107DCEB0
.global end_Pdoor_st_arec2Z
.set end_Pdoor_st_arec2Z, 0x107DD190
.global Pdoor_winZ
.set Pdoor_winZ, 0x107DD190
.global end_Pdoor_winZ
.set end_Pdoor_winZ, 0x107DD330
.global PdoorconsoleZ
.set PdoorconsoleZ, 0x107DD330
.global end_PdoorconsoleZ
.set end_PdoorconsoleZ, 0x107DD7A0
.global PdoorpanelZ
.set PdoorpanelZ, 0x107DD7A0
.global end_PdoorpanelZ
.set end_PdoorpanelZ, 0x107DDB10
.global Pdoorprison1Z
.set Pdoorprison1Z, 0x107DDB10
.global end_Pdoorprison1Z
.set end_Pdoorprison1Z, 0x107DDC60
.global PdoorstatgateZ
.set PdoorstatgateZ, 0x107DDC60
.global end_PdoorstatgateZ
.set end_PdoorstatgateZ, 0x107DDE60
.global PexplosionbitZ
.set PexplosionbitZ, 0x107DDE60
.global end_PexplosionbitZ
.set end_PexplosionbitZ, 0x107DDF80
.global Pfiling_cabinet1Z
.set Pfiling_cabinet1Z, 0x107DDF80
.global end_Pfiling_cabinet1Z
.set end_Pfiling_cabinet1Z, 0x107DE100
.global PflagZ
.set PflagZ, 0x107DE100
.global end_PflagZ
.set end_PflagZ, 0x107DE230
.global PfloppyZ
.set PfloppyZ, 0x107DE230
.global end_PfloppyZ
.set end_PfloppyZ, 0x107DE550
.global Pfnp90magZ
.set Pfnp90magZ, 0x107DE550
.global end_Pfnp90magZ
.set end_Pfnp90magZ, 0x107DE6F0
.global Pgas_plant_met1_do1Z
.set Pgas_plant_met1_do1Z, 0x107DE6F0
.global end_Pgas_plant_met1_do1Z
.set end_Pgas_plant_met1_do1Z, 0x107DEA70
.global Pgas_plant_sw2_do1Z
.set Pgas_plant_sw2_do1Z, 0x107DEA70
.global end_Pgas_plant_sw2_do1Z
.set end_Pgas_plant_sw2_do1Z, 0x107DEC50
.global Pgas_plant_sw3_do1Z
.set Pgas_plant_sw3_do1Z, 0x107DEC50
.global end_Pgas_plant_sw3_do1Z
.set end_Pgas_plant_sw3_do1Z, 0x107DEE50
.global Pgas_plant_sw4_do1Z
.set Pgas_plant_sw4_do1Z, 0x107DEE50
.global end_Pgas_plant_sw4_do1Z
.set end_Pgas_plant_sw4_do1Z, 0x107DEFB0
.global Pgas_plant_sw_do1Z
.set Pgas_plant_sw_do1Z, 0x107DEFB0
.global end_Pgas_plant_sw_do1Z
.set end_Pgas_plant_sw_do1Z, 0x107DF240
.global Pgas_plant_wc_cub1Z
.set Pgas_plant_wc_cub1Z, 0x107DF240
.global end_Pgas_plant_wc_cub1Z
.set end_Pgas_plant_wc_cub1Z, 0x107DF450
.global PgasbarrelZ
.set PgasbarrelZ, 0x107DF450
.global end_PgasbarrelZ
.set end_PgasbarrelZ, 0x107DF660
.global PgasbarrelsZ
.set PgasbarrelsZ, 0x107DF660
.global end_PgasbarrelsZ
.set end_PgasbarrelsZ, 0x107DFBA0
.global Pgasplant_clear_doorZ
.set Pgasplant_clear_doorZ, 0x107DFBA0
.global end_Pgasplant_clear_doorZ
.set end_Pgasplant_clear_doorZ, 0x107E0100
.global PgastankZ
.set PgastankZ, 0x107E0100
.global end_PgastankZ
.set end_PgastankZ, 0x107E06B0
.global Pglassware1Z
.set Pglassware1Z, 0x107E06B0
.global end_Pglassware1Z
.set end_Pglassware1Z, 0x107E0810
.global Pglassware2Z
.set Pglassware2Z, 0x107E0810
.global end_Pglassware2Z
.set end_Pglassware2Z, 0x107E0AA0
.global Pglassware3Z
.set Pglassware3Z, 0x107E0AA0
.global end_Pglassware3Z
.set end_Pglassware3Z, 0x107E0CB0
.global Pglassware4Z
.set Pglassware4Z, 0x107E0CB0
.global end_Pglassware4Z
.set end_Pglassware4Z, 0x107E1230
.global PgoldeneyelogoZ
.set PgoldeneyelogoZ, 0x107E1230
.global end_PgoldeneyelogoZ
.set end_PgoldeneyelogoZ, 0x107E20E0
.global PgoldenshellsZ
.set PgoldenshellsZ, 0x107E20E0
.global end_PgoldenshellsZ
.set end_PgoldenshellsZ, 0x107E22E0
.global PgroundgunZ
.set PgroundgunZ, 0x107E22E0
.global end_PgroundgunZ
.set end_PgroundgunZ, 0x107E2AB0
.global Pgun_runway1Z
.set Pgun_runway1Z, 0x107E2AB0
.global end_Pgun_runway1Z
.set end_Pgun_runway1Z, 0x107E31F0
.global PhatberetZ
.set PhatberetZ, 0x107E31F0
.global end_PhatberetZ
.set end_PhatberetZ, 0x107E3490
.global PhatberetblueZ
.set PhatberetblueZ, 0x107E3490
.global end_PhatberetblueZ
.set end_PhatberetblueZ, 0x107E3760
.global PhatberetredZ
.set PhatberetredZ, 0x107E3760
.global end_PhatberetredZ
.set end_PhatberetredZ, 0x107E3A40
.global PhatchboltZ
.set PhatchboltZ, 0x107E3A40
.global end_PhatchboltZ
.set end_PhatchboltZ, 0x107E3B10
.global PhatchdoorZ
.set PhatchdoorZ, 0x107E3B10
.global end_PhatchdoorZ
.set end_PhatchdoorZ, 0x107E3D30
.global PhatchsevxZ
.set PhatchsevxZ, 0x107E3D30
.global end_PhatchsevxZ
.set end_PhatchsevxZ, 0x107E3EA0
.global PhatfurryZ
.set PhatfurryZ, 0x107E3EA0
.global end_PhatfurryZ
.set end_PhatfurryZ, 0x107E40D0
.global PhatfurryblackZ
.set PhatfurryblackZ, 0x107E40D0
.global end_PhatfurryblackZ
.set end_PhatfurryblackZ, 0x107E42F0
.global PhatfurrybrownZ
.set PhatfurrybrownZ, 0x107E42F0
.global end_PhatfurrybrownZ
.set end_PhatfurrybrownZ, 0x107E4500
.global PhathelmetZ
.set PhathelmetZ, 0x107E4500
.global end_PhathelmetZ
.set end_PhathelmetZ, 0x107E4730
.global PhathelmetgreyZ
.set PhathelmetgreyZ, 0x107E4730
.global end_PhathelmetgreyZ
.set end_PhathelmetgreyZ, 0x107E4960
.global PhatmoonZ
.set PhatmoonZ, 0x107E4960
.global end_PhatmoonZ
.set end_PhatmoonZ, 0x107E4D40
.global PhatpeakedZ
.set PhatpeakedZ, 0x107E4D40
.global end_PhatpeakedZ
.set end_PhatpeakedZ, 0x107E5050
.global PhattbirdZ
.set PhattbirdZ, 0x107E5050
.global end_PhattbirdZ
.set end_PhattbirdZ, 0x107E52A0
.global PhattbirdbrownZ
.set PhattbirdbrownZ, 0x107E52A0
.global end_PhattbirdbrownZ
.set end_PhattbirdbrownZ, 0x107E5510
.global PhelicopterZ
.set PhelicopterZ, 0x107E5510
.global end_PhelicopterZ
.set end_PhelicopterZ, 0x107E9730
.global PhindZ
.set PhindZ, 0x107E9730
.global end_PhindZ
.set end_PhindZ, 0x107EAEA0
.global PjeepZ
.set PjeepZ, 0x107EAEA0
.global end_PjeepZ
.set end_PjeepZ, 0x107EC000
.global Pjerry_can1Z
.set Pjerry_can1Z, 0x107EC000
.global end_Pjerry_can1Z
.set end_Pjerry_can1Z, 0x107EC260
.global Pjungle3_treeZ
.set Pjungle3_treeZ, 0x107EC260
.global end_Pjungle3_treeZ
.set end_Pjungle3_treeZ, 0x107EC9E0
.global Pjungle5_treeZ
.set Pjungle5_treeZ, 0x107EC9E0
.global end_Pjungle5_treeZ
.set end_Pjungle5_treeZ, 0x107ECF10
.global Pkey_holderZ
.set Pkey_holderZ, 0x107ECF10
.global end_Pkey_holderZ
.set end_Pkey_holderZ, 0x107ED260
.global Pkeyboard1Z
.set Pkeyboard1Z, 0x107ED260
.global end_Pkeyboard1Z
.set end_Pkeyboard1Z, 0x107ED3D0
.global Pkit_units1Z
.set Pkit_units1Z, 0x107ED3D0
.global end_Pkit_units1Z
.set end_Pkit_units1Z, 0x107ED670
.global PlabbenchZ
.set PlabbenchZ, 0x107ED670
.global end_PlabbenchZ
.set end_PlabbenchZ, 0x107EDA40
.global PlandmineZ
.set PlandmineZ, 0x107EDA40
.global end_PlandmineZ
.set end_PlandmineZ, 0x107EDCB0
.global PlegalpageZ
.set PlegalpageZ, 0x107EDCB0
.global end_PlegalpageZ
.set end_PlegalpageZ, 0x107EEC70
.global Pletter_tray1Z
.set Pletter_tray1Z, 0x107EEC70
.global end_Pletter_tray1Z
.set end_Pletter_tray1Z, 0x107EEDD0
.global Plocker3Z
.set Plocker3Z, 0x107EEDD0
.global end_Plocker3Z
.set end_Plocker3Z, 0x107EEF60
.global Plocker4Z
.set Plocker4Z, 0x107EEF60
.global end_Plocker4Z
.set end_Plocker4Z, 0x107EF0F0
.global Pm16magZ
.set Pm16magZ, 0x107EF0F0
.global end_Pm16magZ
.set end_Pm16magZ, 0x107EF230
.global PmagnumshellsZ
.set PmagnumshellsZ, 0x107EF230
.global end_PmagnumshellsZ
.set end_PmagnumshellsZ, 0x107EF430
.global Pmainframe1Z
.set Pmainframe1Z, 0x107EF430
.global end_Pmainframe1Z
.set end_Pmainframe1Z, 0x107EF730
.global Pmainframe2Z
.set Pmainframe2Z, 0x107EF730
.global end_Pmainframe2Z
.set end_Pmainframe2Z, 0x107EFA00
.global Pmetal_chair1Z
.set Pmetal_chair1Z, 0x107EFA00
.global end_Pmetal_chair1Z
.set end_Pmetal_chair1Z, 0x107EFD40
.global Pmetal_crate1Z
.set Pmetal_crate1Z, 0x107EFD40
.global end_Pmetal_crate1Z
.set end_Pmetal_crate1Z, 0x107EFF00
.global Pmetal_crate2Z
.set Pmetal_crate2Z, 0x107EFF00
.global end_Pmetal_crate2Z
.set end_Pmetal_crate2Z, 0x107F00C0
.global Pmetal_crate3Z
.set Pmetal_crate3Z, 0x107F00C0
.global end_Pmetal_crate3Z
.set end_Pmetal_crate3Z, 0x107F0280
.global Pmetal_crate4Z
.set Pmetal_crate4Z, 0x107F0280
.global end_Pmetal_crate4Z
.set end_Pmetal_crate4Z, 0x107F0440
.global PmilcopterZ
.set PmilcopterZ, 0x107F0440
.global end_PmilcopterZ
.set end_PmilcopterZ, 0x107F1D20
.global PmiltruckZ
.set PmiltruckZ, 0x107F1D20
.global end_PmiltruckZ
.set end_PmiltruckZ, 0x107F4020
.global Pmissile_rack2Z
.set Pmissile_rack2Z, 0x107F4020
.global end_Pmissile_rack2Z
.set end_Pmissile_rack2Z, 0x107F4A30
.global Pmissile_rackZ
.set Pmissile_rackZ, 0x107F4A30
.global end_Pmissile_rackZ
.set end_Pmissile_rackZ, 0x107F4E10
.global PmodemboxZ
.set PmodemboxZ, 0x107F4E10
.global end_PmodemboxZ
.set end_PmodemboxZ, 0x107F5150
.global PmotorbikeZ
.set PmotorbikeZ, 0x107F5150
.global end_PmotorbikeZ
.set end_PmotorbikeZ, 0x107F6010
.global Pmp5kmagZ
.set Pmp5kmagZ, 0x107F6010
.global end_Pmp5kmagZ
.set end_Pmp5kmagZ, 0x107F6160
.global PnintendologoZ
.set PnintendologoZ, 0x107F6160
.global end_PnintendologoZ
.set end_PnintendologoZ, 0x107F8C40
.global Poil_drum1Z
.set Poil_drum1Z, 0x107F8C40
.global end_Poil_drum1Z
.set end_Poil_drum1Z, 0x107F8EB0
.global Poil_drum2Z
.set Poil_drum2Z, 0x107F8EB0
.global end_Poil_drum2Z
.set end_Poil_drum2Z, 0x107F91A0
.global Poil_drum3Z
.set Poil_drum3Z, 0x107F91A0
.global end_Poil_drum3Z
.set end_Poil_drum3Z, 0x107F9490
.global Poil_drum5Z
.set Poil_drum5Z, 0x107F9490
.global end_Poil_drum5Z
.set end_Poil_drum5Z, 0x107F9780
.global Poil_drum6Z
.set Poil_drum6Z, 0x107F9780
.global end_Poil_drum6Z
.set end_Poil_drum6Z, 0x107F9A90
.global Poil_drum7Z
.set Poil_drum7Z, 0x107F9A90
.global end_Poil_drum7Z
.set end_Poil_drum7Z, 0x107F9D90
.global PpadlockZ
.set PpadlockZ, 0x107F9D90
.global end_PpadlockZ
.set end_PpadlockZ, 0x107FA7E0
.global PpalmZ
.set PpalmZ, 0x107FA7E0
.global end_PpalmZ
.set end_PpalmZ, 0x107FAC30
.global PpalmtreeZ
.set PpalmtreeZ, 0x107FAC30
.global end_PpalmtreeZ
.set end_PpalmtreeZ, 0x107FB100
.global Pphone1Z
.set Pphone1Z, 0x107FB100
.global end_Pphone1Z
.set end_Pphone1Z, 0x107FB240
.global PplaneZ
.set PplaneZ, 0x107FB240
.global end_PplaneZ
.set end_PplaneZ, 0x107FD820
.global Pplant11Z
.set Pplant11Z, 0x107FD820
.global end_Pplant11Z
.set end_Pplant11Z, 0x107FDBE0
.global Pplant1Z
.set Pplant1Z, 0x107FDBE0
.global end_Pplant1Z
.set end_Pplant1Z, 0x107FDF70
.global Pplant2Z
.set Pplant2Z, 0x107FDF70
.global end_Pplant2Z
.set end_Pplant2Z, 0x107FE2D0
.global Pplant2bZ
.set Pplant2bZ, 0x107FE2D0
.global end_Pplant2bZ
.set end_Pplant2bZ, 0x107FE6E0
.global Pplant3Z
.set Pplant3Z, 0x107FE6E0
.global end_Pplant3Z
.set end_Pplant3Z, 0x107FEB30
.global Pradio_unit1Z
.set Pradio_unit1Z, 0x107FEB30
.global end_Pradio_unit1Z
.set end_Pradio_unit1Z, 0x107FECE0
.global Pradio_unit2Z
.set Pradio_unit2Z, 0x107FECE0
.global end_Pradio_unit2Z
.set end_Pradio_unit2Z, 0x107FEEA0
.global Pradio_unit3Z
.set Pradio_unit3Z, 0x107FEEA0
.global end_Pradio_unit3Z
.set end_Pradio_unit3Z, 0x107FF060
.global Pradio_unit4Z
.set Pradio_unit4Z, 0x107FF060
.global end_Pradio_unit4Z
.set end_Pradio_unit4Z, 0x107FF220
.global ProofgunZ
.set ProofgunZ, 0x107FF220
.global end_ProofgunZ
.set end_ProofgunZ, 0x107FF880
.global PsafeZ
.set PsafeZ, 0x107FF880
.global end_PsafeZ
.set end_PsafeZ, 0x107FFBD0
.global PsafedoorZ
.set PsafedoorZ, 0x107FFBD0
.global end_PsafedoorZ
.set end_PsafedoorZ, 0x108000C0
.global Psat1_reflectZ
.set Psat1_reflectZ, 0x108000C0
.global end_Psat1_reflectZ
.set end_Psat1_reflectZ, 0x10801630
.global PsatboxZ
.set PsatboxZ, 0x10801630
.global end_PsatboxZ
.set end_PsatboxZ, 0x10801750
.global PsatdishZ
.set PsatdishZ, 0x10801750
.global end_PsatdishZ
.set end_PsatdishZ, 0x10801BB0
.global Psec_panelZ
.set Psec_panelZ, 0x10801BB0
.global end_Psec_panelZ
.set end_Psec_panelZ, 0x10801D50
.global Psev_door3Z
.set Psev_door3Z, 0x10801D50
.global end_Psev_door3Z
.set end_Psev_door3Z, 0x10801FE0
.global Psev_door3_windZ
.set Psev_door3_windZ, 0x10801FE0
.global end_Psev_door3_windZ
.set end_Psev_door3_windZ, 0x10802370
.global Psev_door4_windZ
.set Psev_door4_windZ, 0x10802370
.global end_Psev_door4_windZ
.set end_Psev_door4_windZ, 0x10802750
.global Psev_doorZ
.set Psev_doorZ, 0x10802750
.global end_Psev_doorZ
.set end_Psev_doorZ, 0x10802AA0
.global Psev_door_v1Z
.set Psev_door_v1Z, 0x10802AA0
.global end_Psev_door_v1Z
.set end_Psev_door_v1Z, 0x10802DD0
.global Psev_trislideZ
.set Psev_trislideZ, 0x10802DD0
.global end_Psev_trislideZ
.set end_Psev_trislideZ, 0x10803180
.global PsevdishZ
.set PsevdishZ, 0x10803180
.global end_PsevdishZ
.set end_PsevdishZ, 0x108040A0
.global PsevdoormetslideZ
.set PsevdoormetslideZ, 0x108040A0
.global end_PsevdoormetslideZ
.set end_PsevdoormetslideZ, 0x10804380
.global PsevdoornowindZ
.set PsevdoornowindZ, 0x10804380
.global end_PsevdoornowindZ
.set end_PsevdoornowindZ, 0x108044F0
.global PsevdoorwindZ
.set PsevdoorwindZ, 0x108044F0
.global end_PsevdoorwindZ
.set end_PsevdoorwindZ, 0x10804920
.global PsevdoorwoodZ
.set PsevdoorwoodZ, 0x10804920
.global end_PsevdoorwoodZ
.set end_PsevdoorwoodZ, 0x10804CD0
.global PshuttleZ
.set PshuttleZ, 0x10804CD0
.global end_PshuttleZ
.set end_PshuttleZ, 0x108076D0
.global Pshuttle_door_lZ
.set Pshuttle_door_lZ, 0x108076D0
.global end_Pshuttle_door_lZ
.set end_Pshuttle_door_lZ, 0x10808300
.global Pshuttle_door_rZ
.set Pshuttle_door_rZ, 0x10808300
.global end_Pshuttle_door_rZ
.set end_Pshuttle_door_rZ, 0x10809000
.global PsilencerZ
.set PsilencerZ, 0x10809000
.global end_PsilencerZ
.set end_PsilencerZ, 0x108091A0
.global Psilo_lift_doorZ
.set Psilo_lift_doorZ, 0x108091A0
.global end_Psilo_lift_doorZ
.set end_Psilo_lift_doorZ, 0x108093E0
.global PsilotopdoorZ
.set PsilotopdoorZ, 0x108093E0
.global end_PsilotopdoorZ
.set end_PsilotopdoorZ, 0x108096D0
.global PskorpionmagZ
.set PskorpionmagZ, 0x108096D0
.global end_PskorpionmagZ
.set end_PskorpionmagZ, 0x10809830
.global PspectremagZ
.set PspectremagZ, 0x10809830
.global end_PspectremagZ
.set end_PspectremagZ, 0x108099A0
.global PspeedboatZ
.set PspeedboatZ, 0x108099A0
.global end_PspeedboatZ
.set end_PspeedboatZ, 0x1080A6E0
.global Pst_pete_room_1iZ
.set Pst_pete_room_1iZ, 0x1080A6E0
.global end_Pst_pete_room_1iZ
.set end_Pst_pete_room_1iZ, 0x1080D820
.global Pst_pete_room_2iZ
.set Pst_pete_room_2iZ, 0x1080D820
.global end_Pst_pete_room_2iZ
.set end_Pst_pete_room_2iZ, 0x10810A00
.global Pst_pete_room_3tZ
.set Pst_pete_room_3tZ, 0x10810A00
.global end_Pst_pete_room_3tZ
.set end_Pst_pete_room_3tZ, 0x10813940
.global Pst_pete_room_5cZ
.set Pst_pete_room_5cZ, 0x10813940
.global end_Pst_pete_room_5cZ
.set end_Pst_pete_room_5cZ, 0x10816ED0
.global Pst_pete_room_6cZ
.set Pst_pete_room_6cZ, 0x10816ED0
.global end_Pst_pete_room_6cZ
.set end_Pst_pete_room_6cZ, 0x1081A2E0
.global Psteel_door1Z
.set Psteel_door1Z, 0x1081A2E0
.global end_Psteel_door1Z
.set end_Psteel_door1Z, 0x1081A550
.global Psteel_door2Z
.set Psteel_door2Z, 0x1081A550
.global end_Psteel_door2Z
.set end_Psteel_door2Z, 0x1081A800
.global Psteel_door2bZ
.set Psteel_door2bZ, 0x1081A800
.global end_Psteel_door2bZ
.set end_Psteel_door2bZ, 0x1081AAD0
.global Psteel_door3Z
.set Psteel_door3Z, 0x1081AAD0
.global end_Psteel_door3Z
.set end_Psteel_door3Z, 0x1081ADA0
.global Pstool1Z
.set Pstool1Z, 0x1081ADA0
.global end_Pstool1Z
.set end_Pstool1Z, 0x1081B060
.global Pswipe_card2Z
.set Pswipe_card2Z, 0x1081B060
.global end_Pswipe_card2Z
.set end_Pswipe_card2Z, 0x1081B1F0
.global Pswivel_chair1Z
.set Pswivel_chair1Z, 0x1081B1F0
.global end_Pswivel_chair1Z
.set end_Pswivel_chair1Z, 0x1081B480
.global PtankZ
.set PtankZ, 0x1081B480
.global end_PtankZ
.set end_PtankZ, 0x1081CF20
.global PtigerZ
.set PtigerZ, 0x1081CF20
.global end_PtigerZ
.set end_PtigerZ, 0x1081EDB0
.global Ptorpedo_rackZ
.set Ptorpedo_rackZ, 0x1081EDB0
.global end_Ptorpedo_rackZ
.set end_Ptorpedo_rackZ, 0x1081F630
.global Ptrain_door2Z
.set Ptrain_door2Z, 0x1081F630
.global end_Ptrain_door2Z
.set end_Ptrain_door2Z, 0x1081FA00
.global Ptrain_door3Z
.set Ptrain_door3Z, 0x1081FA00
.global end_Ptrain_door3Z
.set end_Ptrain_door3Z, 0x1081FE20
.global Ptrain_doorZ
.set Ptrain_doorZ, 0x1081FE20
.global end_Ptrain_doorZ
.set end_Ptrain_doorZ, 0x10820090
.global PtrainextdoorZ
.set PtrainextdoorZ, 0x10820090
.global end_PtrainextdoorZ
.set end_PtrainextdoorZ, 0x108203D0
.global Ptt33magZ
.set Ptt33magZ, 0x108203D0
.global end_Ptt33magZ
.set end_Ptt33magZ, 0x10820510
.global Ptuning_console1Z
.set Ptuning_console1Z, 0x10820510
.global end_Ptuning_console1Z
.set end_Ptuning_console1Z, 0x10820A30
.global Ptv1Z
.set Ptv1Z, 0x10820A30
.global end_Ptv1Z
.set end_Ptv1Z, 0x10820C00
.global Ptv4screenZ
.set Ptv4screenZ, 0x10820C00
.global end_Ptv4screenZ
.set end_Ptv4screenZ, 0x10820DA0
.global Ptv_holderZ
.set Ptv_holderZ, 0x10820DA0
.global end_Ptv_holderZ
.set end_Ptv_holderZ, 0x10821470
.global PtvscreenZ
.set PtvscreenZ, 0x10821470
.global end_PtvscreenZ
.set end_PtvscreenZ, 0x10821540
.global PuzimagZ
.set PuzimagZ, 0x10821540
.global end_PuzimagZ
.set end_PuzimagZ, 0x10821680
.global PvertdoorZ
.set PvertdoorZ, 0x10821680
.global end_PvertdoorZ
.set end_PvertdoorZ, 0x10821C90
.global PwalletbondZ
.set PwalletbondZ, 0x10821C90
.global end_PwalletbondZ
.set end_PwalletbondZ, 0x10823240
.global PwindowZ
.set PwindowZ, 0x10823240
.global end_PwindowZ
.set end_PwindowZ, 0x10823330
.global Pwindow_cor11Z
.set Pwindow_cor11Z, 0x10823330
.global end_Pwindow_cor11Z
.set end_Pwindow_cor11Z, 0x10823410
.global Pwindow_lib_lg1Z
.set Pwindow_lib_lg1Z, 0x10823410
.global end_Pwindow_lib_lg1Z
.set end_Pwindow_lib_lg1Z, 0x108234F0
.global Pwindow_lib_sm1Z
.set Pwindow_lib_sm1Z, 0x108234F0
.global end_Pwindow_lib_sm1Z
.set end_Pwindow_lib_sm1Z, 0x108235E0
.global Pwood_lg_crate1Z
.set Pwood_lg_crate1Z, 0x108235E0
.global end_Pwood_lg_crate1Z
.set end_Pwood_lg_crate1Z, 0x10823860
.global Pwood_lg_crate2Z
.set Pwood_lg_crate2Z, 0x10823860
.global end_Pwood_lg_crate2Z
.set end_Pwood_lg_crate2Z, 0x10823A80
.global Pwood_md_crate3Z
.set Pwood_md_crate3Z, 0x10823A80
.global end_Pwood_md_crate3Z
.set end_Pwood_md_crate3Z, 0x10823CA0
.global Pwood_sm_crate4Z
.set Pwood_sm_crate4Z, 0x10823CA0
.global end_Pwood_sm_crate4Z
.set end_Pwood_sm_crate4Z, 0x10823F00
.global Pwood_sm_crate5Z
.set Pwood_sm_crate5Z, 0x10823F00
.global end_Pwood_sm_crate5Z
.set end_Pwood_sm_crate5Z, 0x10824160
.global Pwood_sm_crate6Z
.set Pwood_sm_crate6Z, 0x10824160
.global end_Pwood_sm_crate6Z
.set end_Pwood_sm_crate6Z, 0x10824380
.global Pwooden_table1Z
.set Pwooden_table1Z, 0x10824380
.global end_Pwooden_table1Z
.set end_Pwooden_table1Z, 0x108246F0
.global PwppkmagZ
.set PwppkmagZ, 0x108246F0
.global end_PwppkmagZ
.set end_PwppkmagZ, 0x10824830
.global Tbg_ame_all_p_stanZ
.set Tbg_ame_all_p_stanZ, 0x10824830
.global end_Tbg_ame_all_p_stanZ
.set end_Tbg_ame_all_p_stanZ, 0x10826160
.global Tbg_arch_all_p_stanZ
.set Tbg_arch_all_p_stanZ, 0x10826160
.global end_Tbg_arch_all_p_stanZ
.set end_Tbg_arch_all_p_stanZ, 0x1082BE50
.global Tbg_arec_all_p_stanZ
.set Tbg_arec_all_p_stanZ, 0x1082BE50
.global end_Tbg_arec_all_p_stanZ
.set end_Tbg_arec_all_p_stanZ, 0x108341A0
.global Tbg_ark_all_p_stanZ
.set Tbg_ark_all_p_stanZ, 0x108341A0
.global end_Tbg_ark_all_p_stanZ
.set end_Tbg_ark_all_p_stanZ, 0x1083D160
.global Tbg_ash_all_p_stanZ
.set Tbg_ash_all_p_stanZ, 0x1083D160
.global end_Tbg_ash_all_p_stanZ
.set end_Tbg_ash_all_p_stanZ, 0x1083EA90
.global Tbg_azt_all_p_stanZ
.set Tbg_azt_all_p_stanZ, 0x1083EA90
.global end_Tbg_azt_all_p_stanZ
.set end_Tbg_azt_all_p_stanZ, 0x10844010
.global Tbg_cat_all_p_stanZ
.set Tbg_cat_all_p_stanZ, 0x10844010
.global end_Tbg_cat_all_p_stanZ
.set end_Tbg_cat_all_p_stanZ, 0x10846740
.global Tbg_cave_all_p_stanZ
.set Tbg_cave_all_p_stanZ, 0x10846740
.global end_Tbg_cave_all_p_stanZ
.set end_Tbg_cave_all_p_stanZ, 0x1084B630
.global Tbg_crad_all_p_stanZ
.set Tbg_crad_all_p_stanZ, 0x1084B630
.global end_Tbg_crad_all_p_stanZ
.set end_Tbg_crad_all_p_stanZ, 0x1084DF40
.global Tbg_cryp_all_p_stanZ
.set Tbg_cryp_all_p_stanZ, 0x1084DF40
.global end_Tbg_cryp_all_p_stanZ
.set end_Tbg_cryp_all_p_stanZ, 0x10850FB0
.global Tbg_dam_all_p_stanZ
.set Tbg_dam_all_p_stanZ, 0x10850FB0
.global end_Tbg_dam_all_p_stanZ
.set end_Tbg_dam_all_p_stanZ, 0x1085B390
.global Tbg_depo_all_p_stanZ
.set Tbg_depo_all_p_stanZ, 0x1085B390
.global end_Tbg_depo_all_p_stanZ
.set end_Tbg_depo_all_p_stanZ, 0x108622D0
.global Tbg_dest_all_p_stanZ
.set Tbg_dest_all_p_stanZ, 0x108622D0
.global end_Tbg_dest_all_p_stanZ
.set end_Tbg_dest_all_p_stanZ, 0x10868BC0
.global Tbg_dish_all_p_stanZ
.set Tbg_dish_all_p_stanZ, 0x10868BC0
.global end_Tbg_dish_all_p_stanZ
.set end_Tbg_dish_all_p_stanZ, 0x108696D0
.global Tbg_imp_all_p_stanZ
.set Tbg_imp_all_p_stanZ, 0x108696D0
.global end_Tbg_imp_all_p_stanZ
.set end_Tbg_imp_all_p_stanZ, 0x1086B000
.global Tbg_jun_all_p_stanZ
.set Tbg_jun_all_p_stanZ, 0x1086B000
.global end_Tbg_jun_all_p_stanZ
.set end_Tbg_jun_all_p_stanZ, 0x10872150
.global Tbg_len_all_p_stanZ
.set Tbg_len_all_p_stanZ, 0x10872150
.global end_Tbg_len_all_p_stanZ
.set end_Tbg_len_all_p_stanZ, 0x10872C10
.global Tbg_oat_all_p_stanZ
.set Tbg_oat_all_p_stanZ, 0x10872C10
.global end_Tbg_oat_all_p_stanZ
.set end_Tbg_oat_all_p_stanZ, 0x10874510
.global Tbg_pete_all_p_stanZ
.set Tbg_pete_all_p_stanZ, 0x10874510
.global end_Tbg_pete_all_p_stanZ
.set end_Tbg_pete_all_p_stanZ, 0x10878BA0
.global Tbg_ref_all_p_stanZ
.set Tbg_ref_all_p_stanZ, 0x10878BA0
.global end_Tbg_ref_all_p_stanZ
.set end_Tbg_ref_all_p_stanZ, 0x1087A970
.global Tbg_run_all_p_stanZ
.set Tbg_run_all_p_stanZ, 0x1087A970
.global end_Tbg_run_all_p_stanZ
.set end_Tbg_run_all_p_stanZ, 0x1087C3F0
.global Tbg_sev_all_p_stanZ
.set Tbg_sev_all_p_stanZ, 0x1087C3F0
.global end_Tbg_sev_all_p_stanZ
.set end_Tbg_sev_all_p_stanZ, 0x108801C0
.global Tbg_sevb_all_p_stanZ
.set Tbg_sevb_all_p_stanZ, 0x108801C0
.global end_Tbg_sevb_all_p_stanZ
.set end_Tbg_sevb_all_p_stanZ, 0x10885100
.global Tbg_sevx_all_p_stanZ
.set Tbg_sevx_all_p_stanZ, 0x10885100
.global end_Tbg_sevx_all_p_stanZ
.set end_Tbg_sevx_all_p_stanZ, 0x1088E430
.global Tbg_silo_all_p_stanZ
.set Tbg_silo_all_p_stanZ, 0x1088E430
.global end_Tbg_silo_all_p_stanZ
.set end_Tbg_silo_all_p_stanZ, 0x108974D0
.global Tbg_stat_all_p_stanZ
.set Tbg_stat_all_p_stanZ, 0x108974D0
.global end_Tbg_stat_all_p_stanZ
.set end_Tbg_stat_all_p_stanZ, 0x1089C390
.global Tbg_tra_all_p_stanZ
.set Tbg_tra_all_p_stanZ, 0x1089C390
.global end_Tbg_tra_all_p_stanZ
.set end_Tbg_tra_all_p_stanZ, 0x1089E760
.global UbriefarchZ
.set UbriefarchZ, 0x1089E760
.global end_UbriefarchZ
.set end_UbriefarchZ, 0x1089E780
.global UbriefarkZ
.set UbriefarkZ, 0x1089E780
.global end_UbriefarkZ
.set end_UbriefarkZ, 0x1089E7A0
.global UbriefaztZ
.set UbriefaztZ, 0x1089E7A0
.global end_UbriefaztZ
.set end_UbriefaztZ, 0x1089E7C0
.global UbriefcaveZ
.set UbriefcaveZ, 0x1089E7C0
.global end_UbriefcaveZ
.set end_UbriefcaveZ, 0x1089E7E0
.global UbriefcontrolZ
.set UbriefcontrolZ, 0x1089E7E0
.global end_UbriefcontrolZ
.set end_UbriefcontrolZ, 0x1089E800
.global UbriefcradZ
.set UbriefcradZ, 0x1089E800
.global end_UbriefcradZ
.set end_UbriefcradZ, 0x1089E820
.global UbriefcrypZ
.set UbriefcrypZ, 0x1089E820
.global end_UbriefcrypZ
.set end_UbriefcrypZ, 0x1089E840
.global UbriefdamZ
.set UbriefdamZ, 0x1089E840
.global end_UbriefdamZ
.set end_UbriefdamZ, 0x1089E860
.global UbriefdepoZ
.set UbriefdepoZ, 0x1089E860
.global end_UbriefdepoZ
.set end_UbriefdepoZ, 0x1089E880
.global UbriefdestZ
.set UbriefdestZ, 0x1089E880
.global end_UbriefdestZ
.set end_UbriefdestZ, 0x1089E8A0
.global UbriefjunZ
.set UbriefjunZ, 0x1089E8A0
.global end_UbriefjunZ
.set end_UbriefjunZ, 0x1089E8C0
.global UbriefpeteZ
.set UbriefpeteZ, 0x1089E8C0
.global end_UbriefpeteZ
.set end_UbriefpeteZ, 0x1089E8E0
.global UbriefrunZ
.set UbriefrunZ, 0x1089E8E0
.global end_UbriefrunZ
.set end_UbriefrunZ, 0x1089E900
.global UbriefsevbZ
.set UbriefsevbZ, 0x1089E900
.global end_UbriefsevbZ
.set end_UbriefsevbZ, 0x1089E920
.global UbriefsevbunkerZ
.set UbriefsevbunkerZ, 0x1089E920
.global end_UbriefsevbunkerZ
.set end_UbriefsevbunkerZ, 0x1089E940
.global UbriefsevxZ
.set UbriefsevxZ, 0x1089E940
.global end_UbriefsevxZ
.set end_UbriefsevxZ, 0x1089E960
.global UbriefsevxbZ
.set UbriefsevxbZ, 0x1089E960
.global end_UbriefsevxbZ
.set end_UbriefsevxbZ, 0x1089E980
.global UbriefsiloZ
.set UbriefsiloZ, 0x1089E980
.global end_UbriefsiloZ
.set end_UbriefsiloZ, 0x1089E9A0
.global UbriefstatueZ
.set UbriefstatueZ, 0x1089E9A0
.global end_UbriefstatueZ
.set end_UbriefstatueZ, 0x1089E9C0
.global UbrieftraZ
.set UbrieftraZ, 0x1089E9C0
.global end_UbrieftraZ
.set end_UbrieftraZ, 0x1089E9E0
.global Ump_setupameZ
.set Ump_setupameZ, 0x1089E9E0
.global end_Ump_setupameZ
.set end_Ump_setupameZ, 0x1089F100
.global Ump_setuparchZ
.set Ump_setuparchZ, 0x1089F100
.global end_Ump_setuparchZ
.set end_Ump_setuparchZ, 0x108A1EA0
.global Ump_setuparkZ
.set Ump_setuparkZ, 0x108A1EA0
.global end_Ump_setuparkZ
.set end_Ump_setuparkZ, 0x108A3BE0
.global Ump_setupashZ
.set Ump_setupashZ, 0x108A3BE0
.global end_Ump_setupashZ
.set end_Ump_setupashZ, 0x108A42D0
.global Ump_setupcaveZ
.set Ump_setupcaveZ, 0x108A42D0
.global end_Ump_setupcaveZ
.set end_Ump_setupcaveZ, 0x108A6830
.global Ump_setupcradZ
.set Ump_setupcradZ, 0x108A6830
.global end_Ump_setupcradZ
.set end_Ump_setupcradZ, 0x108A7190
.global Ump_setupcrypZ
.set Ump_setupcrypZ, 0x108A7190
.global end_Ump_setupcrypZ
.set end_Ump_setupcrypZ, 0x108A7EF0
.global Ump_setupdishZ
.set Ump_setupdishZ, 0x108A7EF0
.global end_Ump_setupdishZ
.set end_Ump_setupdishZ, 0x108A82E0
.global Ump_setupimpZ
.set Ump_setupimpZ, 0x108A82E0
.global end_Ump_setupimpZ
.set end_Ump_setupimpZ, 0x108A8920
.global Ump_setupoatZ
.set Ump_setupoatZ, 0x108A8920
.global end_Ump_setupoatZ
.set end_Ump_setupoatZ, 0x108A8C70
.global Ump_setuprefZ
.set Ump_setuprefZ, 0x108A8C70
.global end_Ump_setuprefZ
.set end_Ump_setuprefZ, 0x108A9080
.global Ump_setupsevbZ
.set Ump_setupsevbZ, 0x108A9080
.global end_Ump_setupsevbZ
.set end_Ump_setupsevbZ, 0x108AA390
.global Ump_setupstatueZ
.set Ump_setupstatueZ, 0x108AA390
.global end_Ump_setupstatueZ
.set end_Ump_setupstatueZ, 0x108AB210
.global UsetuparchZ
.set UsetuparchZ, 0x108AB210
.global end_UsetuparchZ
.set end_UsetuparchZ, 0x108AF820
.global UsetuparkZ
.set UsetuparkZ, 0x108AF820
.global end_UsetuparkZ
.set end_UsetuparkZ, 0x108B33B0
.global UsetupaztZ
.set UsetupaztZ, 0x108B33B0
.global end_UsetupaztZ
.set end_UsetupaztZ, 0x108B5CB0
.global UsetupcaveZ
.set UsetupcaveZ, 0x108B5CB0
.global end_UsetupcaveZ
.set end_UsetupcaveZ, 0x108B9B10
.global UsetupcontrolZ
.set UsetupcontrolZ, 0x108B9B10
.global end_UsetupcontrolZ
.set end_UsetupcontrolZ, 0x108BD610
.global UsetupcradZ
.set UsetupcradZ, 0x108BD610
.global end_UsetupcradZ
.set end_UsetupcradZ, 0x108BF240
.global UsetupcrypZ
.set UsetupcrypZ, 0x108BF240
.global end_UsetupcrypZ
.set end_UsetupcrypZ, 0x108C10D0
.global UsetupdamZ
.set UsetupdamZ, 0x108C10D0
.global end_UsetupdamZ
.set end_UsetupdamZ, 0x108C53A0
.global UsetupdepoZ
.set UsetupdepoZ, 0x108C53A0
.global end_UsetupdepoZ
.set end_UsetupdepoZ, 0x108C8330
.global UsetupdestZ
.set UsetupdestZ, 0x108C8330
.global end_UsetupdestZ
.set end_UsetupdestZ, 0x108CA680
.global UsetupjunZ
.set UsetupjunZ, 0x108CA680
.global end_UsetupjunZ
.set end_UsetupjunZ, 0x108CDD80
.global UsetuplenZ
.set UsetuplenZ, 0x108CDD80
.global end_UsetuplenZ
.set end_UsetuplenZ, 0x108CE350
.global UsetuppeteZ
.set UsetuppeteZ, 0x108CE350
.global end_UsetuppeteZ
.set end_UsetuppeteZ, 0x108D12D0
.global UsetuprunZ
.set UsetuprunZ, 0x108D12D0
.global end_UsetuprunZ
.set end_UsetuprunZ, 0x108D2B30
.global UsetupsevbZ
.set UsetupsevbZ, 0x108D2B30
.global end_UsetupsevbZ
.set end_UsetupsevbZ, 0x108D5190
.global UsetupsevbunkerZ
.set UsetupsevbunkerZ, 0x108D5190
.global end_UsetupsevbunkerZ
.set end_UsetupsevbunkerZ, 0x108D6BC0
.global UsetupsevxZ
.set UsetupsevxZ, 0x108D6BC0
.global end_UsetupsevxZ
.set end_UsetupsevxZ, 0x108DAED0
.global UsetupsevxbZ
.set UsetupsevxbZ, 0x108DAED0
.global end_UsetupsevxbZ
.set end_UsetupsevxbZ, 0x108DEFC0
.global UsetupsiloZ
.set UsetupsiloZ, 0x108DEFC0
.global end_UsetupsiloZ
.set end_UsetupsiloZ, 0x108E1A10
.global UsetupstatueZ
.set UsetupstatueZ, 0x108E1A10
.global end_UsetupstatueZ
.set end_UsetupstatueZ, 0x108E41E0
.global UsetuptraZ
.set UsetuptraZ, 0x108E41E0
.global end_UsetuptraZ
.set end_UsetuptraZ, 0x108E7410
.global LameE
.set LameE, 0x108E7410
.global end_LameE
.set end_LameE, 0x108E7420
.global LameJ
.set LameJ, 0x108E7420
.global end_LameJ
.set end_LameJ, 0x108E7430
.global LarchE
.set LarchE, 0x108E7430
.global end_LarchE
.set end_LarchE, 0x108E7A60
.global LarchJ
.set LarchJ, 0x108E7A60
.global end_LarchJ
.set end_LarchJ, 0x108E80C0
.global LarecE
.set LarecE, 0x108E80C0
.global end_LarecE
.set end_LarecE, 0x108E8690
.global LarecJ
.set LarecJ, 0x108E8690
.global end_LarecJ
.set end_LarecJ, 0x108E8C20
.global LarkE
.set LarkE, 0x108E8C20
.global end_LarkE
.set end_LarkE, 0x108E92C0
.global LarkJ
.set LarkJ, 0x108E92C0
.global end_LarkJ
.set end_LarkJ, 0x108E9970
.global LashE
.set LashE, 0x108E9970
.global end_LashE
.set end_LashE, 0x108E9980
.global LashJ
.set LashJ, 0x108E9980
.global end_LashJ
.set end_LashJ, 0x108E9990
.global LaztE
.set LaztE, 0x108E9990
.global end_LaztE
.set end_LaztE, 0x108E9DD0
.global LaztJ
.set LaztJ, 0x108E9DD0
.global end_LaztJ
.set end_LaztJ, 0x108EA280
.global LcatE
.set LcatE, 0x108EA280
.global end_LcatE
.set end_LcatE, 0x108EA290
.global LcatJ
.set LcatJ, 0x108EA290
.global end_LcatJ
.set end_LcatJ, 0x108EA2A0
.global LcaveE
.set LcaveE, 0x108EA2A0
.global end_LcaveE
.set end_LcaveE, 0x108EA6A0
.global LcaveJ
.set LcaveJ, 0x108EA6A0
.global end_LcaveJ
.set end_LcaveJ, 0x108EAB00
.global LcradE
.set LcradE, 0x108EAB00
.global end_LcradE
.set end_LcradE, 0x108EAFD0
.global LcradJ
.set LcradJ, 0x108EAFD0
.global end_LcradJ
.set end_LcradJ, 0x108EB480
.global LcrypE
.set LcrypE, 0x108EB480
.global end_LcrypE
.set end_LcrypE, 0x108EB6D0
.global LcrypJ
.set LcrypJ, 0x108EB6D0
.global end_LcrypJ
.set end_LcrypJ, 0x108EB990
.global LdamE
.set LdamE, 0x108EB990
.global end_LdamE
.set end_LdamE, 0x108EBDE0
.global LdamJ
.set LdamJ, 0x108EBDE0
.global end_LdamJ
.set end_LdamJ, 0x108EC250
.global LdepoE
.set LdepoE, 0x108EC250
.global end_LdepoE
.set end_LdepoE, 0x108EC5C0
.global LdepoJ
.set LdepoJ, 0x108EC5C0
.global end_LdepoJ
.set end_LdepoJ, 0x108EC900
.global LdestE
.set LdestE, 0x108EC900
.global end_LdestE
.set end_LdestE, 0x108ECD90
.global LdestJ
.set LdestJ, 0x108ECD90
.global end_LdestJ
.set end_LdestJ, 0x108ED1F0
.global LdishE
.set LdishE, 0x108ED1F0
.global end_LdishE
.set end_LdishE, 0x108ED200
.global LdishJ
.set LdishJ, 0x108ED200
.global end_LdishJ
.set end_LdishJ, 0x108ED210
.global LearE
.set LearE, 0x108ED210
.global end_LearE
.set end_LearE, 0x108ED220
.global LearJ
.set LearJ, 0x108ED220
.global end_LearJ
.set end_LearJ, 0x108ED230
.global LeldE
.set LeldE, 0x108ED230
.global end_LeldE
.set end_LeldE, 0x108ED240
.global LeldJ
.set LeldJ, 0x108ED240
.global end_LeldJ
.set end_LeldJ, 0x108ED250
.global LgunE
.set LgunE, 0x108ED250
.global end_LgunE
.set end_LgunE, 0x108ED970
.global LgunJ
.set LgunJ, 0x108ED970
.global end_LgunJ
.set end_LgunJ, 0x108EE0C0
.global LimpE
.set LimpE, 0x108EE0C0
.global end_LimpE
.set end_LimpE, 0x108EE0D0
.global LimpJ
.set LimpJ, 0x108EE0D0
.global end_LimpJ
.set end_LimpJ, 0x108EE0E0
.global LjunE
.set LjunE, 0x108EE0E0
.global end_LjunE
.set end_LjunE, 0x108EE600
.global LjunJ
.set LjunJ, 0x108EE600
.global end_LjunJ
.set end_LjunJ, 0x108EEB40
.global LleeE
.set LleeE, 0x108EEB40
.global end_LleeE
.set end_LleeE, 0x108EEB50
.global LleeJ
.set LleeJ, 0x108EEB50
.global end_LleeJ
.set end_LleeJ, 0x108EEB60
.global LlenE
.set LlenE, 0x108EEB60
.global end_LlenE
.set end_LlenE, 0x108EF1A0
.global LlenJ
.set LlenJ, 0x108EF1A0
.global end_LlenJ
.set end_LlenJ, 0x108EF450
.global LlipE
.set LlipE, 0x108EF450
.global end_LlipE
.set end_LlipE, 0x108EF460
.global LlipJ
.set LlipJ, 0x108EF460
.global end_LlipJ
.set end_LlipJ, 0x108EF470
.global LlueE
.set LlueE, 0x108EF470
.global end_LlueE
.set end_LlueE, 0x108EF480
.global LlueJ
.set LlueJ, 0x108EF480
.global end_LlueJ
.set end_LlueJ, 0x108EF490
.global LmiscE
.set LmiscE, 0x108EF490
.global end_LmiscE
.set end_LmiscE, 0x108EF730
.global LmiscJ
.set LmiscJ, 0x108EF730
.global end_LmiscJ
.set end_LmiscJ, 0x108EFA10
.global LmpmenuE
.set LmpmenuE, 0x108EFA10
.global end_LmpmenuE
.set end_LmpmenuE, 0x108EFBB0
.global LmpmenuJ
.set LmpmenuJ, 0x108EFBB0
.global end_LmpmenuJ
.set end_LmpmenuJ, 0x108EFD40
.global LmpweaponsE
.set LmpweaponsE, 0x108EFD40
.global end_LmpweaponsE
.set end_LmpweaponsE, 0x108EFE00
.global LmpweaponsJ
.set LmpweaponsJ, 0x108EFE00
.global end_LmpweaponsJ
.set end_LmpweaponsJ, 0x108EFEE0
.global LoatE
.set LoatE, 0x108EFEE0
.global end_LoatE
.set end_LoatE, 0x108EFEF0
.global LoatJ
.set LoatJ, 0x108EFEF0
.global end_LoatJ
.set end_LoatJ, 0x108EFF00
.global LoptionsE
.set LoptionsE, 0x108EFF00
.global end_LoptionsE
.set end_LoptionsE, 0x108F0130
.global LoptionsJ
.set LoptionsJ, 0x108F0130
.global end_LoptionsJ
.set end_LoptionsJ, 0x108F0380
.global LpamE
.set LpamE, 0x108F0380
.global end_LpamE
.set end_LpamE, 0x108F0390
.global LpamJ
.set LpamJ, 0x108F0390
.global end_LpamJ
.set end_LpamJ, 0x108F03A0
.global LpeteE
.set LpeteE, 0x108F03A0
.global end_LpeteE
.set end_LpeteE, 0x108F0820
.global LpeteJ
.set LpeteJ, 0x108F0820
.global end_LpeteJ
.set end_LpeteJ, 0x108F0C90
.global LpropobjE
.set LpropobjE, 0x108F0C90
.global end_LpropobjE
.set end_LpropobjE, 0x108F0F30
.global LpropobjJ
.set LpropobjJ, 0x108F0F30
.global end_LpropobjJ
.set end_LpropobjJ, 0x108F11F0
.global LrefE
.set LrefE, 0x108F11F0
.global end_LrefE
.set end_LrefE, 0x108F1200
.global LrefJ
.set LrefJ, 0x108F1200
.global end_LrefJ
.set end_LrefJ, 0x108F1210
.global LritE
.set LritE, 0x108F1210
.global end_LritE
.set end_LritE, 0x108F1220
.global LritJ
.set LritJ, 0x108F1220
.global end_LritJ
.set end_LritJ, 0x108F1230
.global LrunE
.set LrunE, 0x108F1230
.global end_LrunE
.set end_LrunE, 0x108F14A0
.global LrunJ
.set LrunJ, 0x108F14A0
.global end_LrunJ
.set end_LrunJ, 0x108F1730
.global LsevE
.set LsevE, 0x108F1730
.global end_LsevE
.set end_LsevE, 0x108F1C90
.global LsevJ
.set LsevJ, 0x108F1C90
.global end_LsevJ
.set end_LsevJ, 0x108F21A0
.global LsevbE
.set LsevbE, 0x108F21A0
.global end_LsevbE
.set end_LsevbE, 0x108F28F0
.global LsevbJ
.set LsevbJ, 0x108F28F0
.global end_LsevbJ
.set end_LsevbJ, 0x108F30E0
.global LsevxE
.set LsevxE, 0x108F30E0
.global end_LsevxE
.set end_LsevxE, 0x108F3540
.global LsevxJ
.set LsevxJ, 0x108F3540
.global end_LsevxJ
.set end_LsevxJ, 0x108F3900
.global LsevxbE
.set LsevxbE, 0x108F3900
.global end_LsevxbE
.set end_LsevxbE, 0x108F3D90
.global LsevxbJ
.set LsevxbJ, 0x108F3D90
.global end_LsevxbJ
.set end_LsevxbJ, 0x108F41E0
.global LshoE
.set LshoE, 0x108F41E0
.global end_LshoE
.set end_LshoE, 0x108F41F0
.global LshoJ
.set LshoJ, 0x108F41F0
.global end_LshoJ
.set end_LshoJ, 0x108F4200
.global LsiloE
.set LsiloE, 0x108F4200
.global end_LsiloE
.set end_LsiloE, 0x108F47B0
.global LsiloJ
.set LsiloJ, 0x108F47B0
.global end_LsiloJ
.set end_LsiloJ, 0x108F4D90
.global LstatE
.set LstatE, 0x108F4D90
.global end_LstatE
.set end_LstatE, 0x108F56B0
.global LstatJ
.set LstatJ, 0x108F56B0
.global end_LstatJ
.set end_LstatJ, 0x108F5F20
.global LtitleE
.set LtitleE, 0x108F5F20
.global end_LtitleE
.set end_LtitleE, 0x108F69E0
.global LtitleJ
.set LtitleJ, 0x108F69E0
.global end_LtitleJ
.set end_LtitleJ, 0x108F7570
.global LtraE
.set LtraE, 0x108F7570
.global end_LtraE
.set end_LtraE, 0x108F79A0
.global LtraJ
.set LtraJ, 0x108F79A0
.global end_LtraJ
.set end_LtraJ, 0x108F7DC0
.global LwaxE
.set LwaxE, 0x108F7DC0
.global end_LwaxE
.set end_LwaxE, 0x108F7DD0
.global LwaxJ
.set LwaxJ, 0x108F7DD0
.global end_LwaxJ
.set end_LwaxJ, 0x108F7DE0
.global ob__ob_end_seg
.set ob__ob_end_seg, 0x108F7DE0
.global end_ob__ob_end_seg
.set end_ob__ob_end_seg, 0x108F7DF0

/* --- assets/ramrom (demo replays) ---------------------------- */
.global ramrom_Dam_1
.set ramrom_Dam_1, 0x102BF2D0
.global ramrom_Dam_1_end
.set ramrom_Dam_1_end, 0x102C44D0
.global ramrom_Dam_2
.set ramrom_Dam_2, 0x102C44D0
.global ramrom_Dam_2_end
.set ramrom_Dam_2_end, 0x102C64A0
.global ramrom_Facility_1
.set ramrom_Facility_1, 0x102C64A0
.global ramrom_Facility_1_end
.set ramrom_Facility_1_end, 0x102C7F50
.global ramrom_Facility_2
.set ramrom_Facility_2, 0x102C7F50
.global ramrom_Facility_2_end
.set ramrom_Facility_2_end, 0x102CA330
.global ramrom_Facility_3
.set ramrom_Facility_3, 0x102CA330
.global ramrom_Facility_3_end
.set ramrom_Facility_3_end, 0x102CBFA0
.global ramrom_Runway_1
.set ramrom_Runway_1, 0x102CBFA0
.global ramrom_Runway_1_end
.set ramrom_Runway_1_end, 0x102CE6F0
.global ramrom_Runway_2
.set ramrom_Runway_2, 0x102CE6F0
.global ramrom_Runway_2_end
.set ramrom_Runway_2_end, 0x102D1000
.global ramrom_BunkerI_1
.set ramrom_BunkerI_1, 0x102D1000
.global ramrom_BunkerI_1_end
.set ramrom_BunkerI_1_end, 0x102D4390
.global ramrom_BunkerI_2
.set ramrom_BunkerI_2, 0x102D4390
.global ramrom_BunkerI_2_end
.set ramrom_BunkerI_2_end, 0x102D9610
.global ramrom_Silo_1
.set ramrom_Silo_1, 0x102D9610
.global ramrom_Silo_1_end
.set ramrom_Silo_1_end, 0x102DB7A0
.global ramrom_Silo_2
.set ramrom_Silo_2, 0x102DB7A0
.global ramrom_Silo_2_end
.set ramrom_Silo_2_end, 0x102DD770
.global ramrom_Frigate_1
.set ramrom_Frigate_1, 0x102DD770
.global ramrom_Frigate_1_end
.set ramrom_Frigate_1_end, 0x102DF120
.global ramrom_Frigate_2
.set ramrom_Frigate_2, 0x102DF120
.global ramrom_Frigate_2_end
.set ramrom_Frigate_2_end, 0x102E2600
.global ramrom_Train
.set ramrom_Train, 0x102E2600
.global ramrom_Train_end
.set ramrom_Train_end, 0x102E63F0
.global _ramromDam1SegmentRomStart
.set _ramromDam1SegmentRomStart, 0x102BF2D0

/* --- assets/music ------------------------------------------------ */
.global _musicsampletblSegmentRomStart
.set _musicsampletblSegmentRomStart, 0x10419790
.global number_music_samples
.set number_music_samples, 0x10419790
.global number_music_samples_end
.set number_music_samples_end, 0x10419794
.global table_music_data
.set table_music_data, 0x10419794
.global _musicsampletblSegmentRomEnd
.set _musicsampletblSegmentRomEnd, 0x1041998C
.global table_music_data_end
.set table_music_data_end, 0x1041998C
.global _sfxctlSegmentRomStart
.set _sfxctlSegmentRomStart, 0x102EBDE0
.global _sfxctlSegmentRomEnd
.set _sfxctlSegmentRomEnd, 0x102F19A0
.global _sfxtblSegmentRomStart
.set _sfxtblSegmentRomStart, 0x102F19A0
.global _sfxtblSegmentRomEnd
.set _sfxtblSegmentRomEnd, 0x103B4450
.global _instrumentsctlSegmentRomStart
.set _instrumentsctlSegmentRomStart, 0x103B4450
.global _instrumentsctlSegmentRomEnd
.set _instrumentsctlSegmentRomEnd, 0x103B87F0
.global _instrumentstblSegmentRomStart
.set _instrumentstblSegmentRomStart, 0x103B87F0
.global _instrumentstblSegmentRomEnd
.set _instrumentstblSegmentRomEnd, 0x10419790
.global Mno_music
.set Mno_music, 0x1041998C
.global end_Mno_music
.set end_Mno_music, 0x104199B6
.global Msolo_death_abrev
.set Msolo_death_abrev, 0x104199B6
.global end_Msolo_death_abrev
.set end_Msolo_death_abrev, 0x10419B8C
.global Mintro_eye
.set Mintro_eye, 0x10419B8C
.global end_Mintro_eye
.set end_Mintro_eye, 0x1041A43A
.global Mtrain
.set Mtrain, 0x1041A43A
.global end_Mtrain
.set end_Mtrain, 0x1041B024
.global Mdepot
.set Mdepot, 0x1041B024
.global end_Mdepot
.set end_Mdepot, 0x1041BDC4
.global Mjungle_unused
.set Mjungle_unused, 0x1041BDC4
.global end_Mjungle_unused
.set end_Mjungle_unused, 0x1041CB5C
.global Mcitadel
.set Mcitadel, 0x1041CB5C
.global end_Mcitadel
.set end_Mcitadel, 0x1041D91C
.global Mfacility
.set Mfacility, 0x1041D91C
.global end_Mfacility
.set end_Mfacility, 0x1041E3EA
.global Mcontrol
.set Mcontrol, 0x1041E3EA
.global end_Mcontrol
.set end_Mcontrol, 0x1041EF48
.global Mdam
.set Mdam, 0x1041EF48
.global end_Mdam
.set end_Mdam, 0x1041FD4C
.global Mfrigate
.set Mfrigate, 0x1041FD4C
.global end_Mfrigate
.set end_Mfrigate, 0x10420B2C
.global Marchives
.set Marchives, 0x10420B2C
.global end_Marchives
.set end_Marchives, 0x10421480
.global Msilo
.set Msilo, 0x10421480
.global end_Msilo
.set end_Msilo, 0x104222F0
.global Mjungle_perimeter_unused
.set Mjungle_perimeter_unused, 0x104222F0
.global end_Mjungle_perimeter_unused
.set end_Mjungle_perimeter_unused, 0x1042325C
.global Mstreets
.set Mstreets, 0x1042325C
.global end_Mstreets
.set end_Mstreets, 0x10423F5E
.global Mbunker1
.set Mbunker1, 0x10423F5E
.global end_Mbunker1
.set end_Mbunker1, 0x104245D0
.global Mbunker2
.set Mbunker2, 0x104245D0
.global end_Mbunker2
.set end_Mbunker2, 0x10424C50
.global Mstatue
.set Mstatue, 0x10424C50
.global end_Mstatue
.set end_Mstatue, 0x104255E8
.global Melevator_control
.set Melevator_control, 0x104255E8
.global end_Melevator_control
.set end_Melevator_control, 0x10425FC2
.global Mcradle
.set Mcradle, 0x10425FC2
.global end_Mcradle
.set end_Mcradle, 0x10426D22
.global Mnull1
.set Mnull1, 0x10426D22
.global end_Mnull1
.set end_Mnull1, 0x10426D4C
.global Melevator_wc
.set Melevator_wc, 0x10426D4C
.global end_Melevator_wc
.set end_Melevator_wc, 0x10427392
.global Megyptian
.set Megyptian, 0x10427392
.global end_Megyptian
.set end_Megyptian, 0x1042812C
.global Mfolders
.set Mfolders, 0x1042812C
.global end_Mfolders
.set end_Mfolders, 0x1042850E
.global Mwatchmusic
.set Mwatchmusic, 0x1042850E
.global end_Mwatchmusic
.set end_Mwatchmusic, 0x10428700
.global Maztec
.set Maztec, 0x10428700
.global end_Maztec
.set end_Maztec, 0x10429372
.global Mwatercaverns
.set Mwatercaverns, 0x10429372
.global end_Mwatercaverns
.set end_Mwatercaverns, 0x1042A19E
.global Mdeathsolo
.set Mdeathsolo, 0x1042A19E
.global end_Mdeathsolo
.set end_Mdeathsolo, 0x1042A504
.global Msurface2
.set Msurface2, 0x1042A504
.global end_Msurface2
.set end_Msurface2, 0x1042B2BA
.global Mtrainx
.set Mtrainx, 0x1042B2BA
.global end_Mtrainx
.set end_Mtrainx, 0x1042BB5A
.global Mnull2
.set Mnull2, 0x1042BB5A
.global end_Mnull2
.set end_Mnull2, 0x1042BB84
.global Mfacilityx
.set Mfacilityx, 0x1042BB84
.global end_Mfacilityx
.set end_Mfacilityx, 0x1042C4DC
.global Mdepotx
.set Mdepotx, 0x1042C4DC
.global end_Mdepotx
.set end_Mdepotx, 0x1042CC98
.global Mcontrolx
.set Mcontrolx, 0x1042CC98
.global end_Mcontrolx
.set end_Mcontrolx, 0x1042D1E0
.global Mwatercavernsx
.set Mwatercavernsx, 0x1042D1E0
.global end_Mwatercavernsx
.set end_Mwatercavernsx, 0x1042D934
.global Mdamx
.set Mdamx, 0x1042D934
.global end_Mdamx
.set end_Mdamx, 0x1042DE54
.global Mfrigatex
.set Mfrigatex, 0x1042DE54
.global end_Mfrigatex
.set end_Mfrigatex, 0x1042E416
.global Marchivesx
.set Marchivesx, 0x1042E416
.global end_Marchivesx
.set end_Marchivesx, 0x1042EB3A
.global Msilox
.set Msilox, 0x1042EB3A
.global end_Msilox
.set end_Msilox, 0x1042F42E
.global Mnull3
.set Mnull3, 0x1042F42E
.global end_Mnull3
.set end_Mnull3, 0x1042F458
.global Mstreetsx
.set Mstreetsx, 0x1042F458
.global end_Mstreetsx
.set end_Mstreetsx, 0x1042FAC4
.global Mbunker1x
.set Mbunker1x, 0x1042FAC4
.global end_Mbunker1x
.set end_Mbunker1x, 0x1043026A
.global Mbunker2x
.set Mbunker2x, 0x1043026A
.global end_Mbunker2x
.set end_Mbunker2x, 0x104308B8
.global Mjunglex
.set Mjunglex, 0x104308B8
.global end_Mjunglex
.set end_Mjunglex, 0x104310CE
.global Mnint_rare_logo
.set Mnint_rare_logo, 0x104310CE
.global end_Mnint_rare_logo
.set end_Mnint_rare_logo, 0x10431500
.global Mstatuex
.set Mstatuex, 0x10431500
.global end_Mstatuex
.set end_Mstatuex, 0x10431BB8
.global Maztecx
.set Maztecx, 0x10431BB8
.global end_Maztecx
.set end_Maztecx, 0x1043248E
.global Megyptianx
.set Megyptianx, 0x1043248E
.global end_Megyptianx
.set end_Megyptianx, 0x10432D3E
.global Mcradlex
.set Mcradlex, 0x10432D3E
.global end_Mcradlex
.set end_Mcradlex, 0x10433408
.global Mcuba
.set Mcuba, 0x10433408
.global end_Mcuba
.set end_Mcuba, 0x10433C52
.global Mrunway
.set Mrunway, 0x10433C52
.global end_Mrunway
.set end_Mrunway, 0x10434970
.global Mrunway_plane
.set Mrunway_plane, 0x10434970
.global end_Mrunway_plane
.set end_Mrunway_plane, 0x10434C4A
.global Msurface2x
.set Msurface2x, 0x10434C4A
.global end_Msurface2x
.set end_Msurface2x, 0x10435372
.global Mwindblowing
.set Mwindblowing, 0x10435372
.global end_Mwindblowing
.set end_Mwindblowing, 0x10435894
.global Mmultideath_alt
.set Mmultideath_alt, 0x10435894
.global end_Mmultideath_alt
.set end_Mmultideath_alt, 0x10435AA0
.global Mjungle
.set Mjungle, 0x10435AA0
.global end_Mjungle
.set end_Mjungle, 0x10436228
.global Mrunwayx
.set Mrunwayx, 0x10436228
.global end_Mrunwayx
.set end_Mrunwayx, 0x1043684A
.global Msurface1
.set Msurface1, 0x1043684A
.global end_Msurface1
.set end_Msurface1, 0x104375B2
.global Mmultiplayerdeath
.set Mmultiplayerdeath, 0x104375B2
.global end_Mmultiplayerdeath
.set end_Mmultiplayerdeath, 0x1043787A
.global Msurface1x
.set Msurface1x, 0x1043787A
.global end_Msurface1x
.set end_Msurface1x, 0x10437FA2
.global Msurface2_ending
.set Msurface2_ending, 0x10437FA2
.global end_Msurface2_ending
.set end_Msurface2_ending, 0x1043823E
.global Mstatue_ending
.set Mstatue_ending, 0x1043823E
.global end_Mstatue_ending
.set end_Mstatue_ending, 0x104383A4
.global Mfrigate_outro
.set Mfrigate_outro, 0x104383A4
.global end_Mfrigate_outro
.set end_Mfrigate_outro, 0x10438660

/* --- assets/romfiles2.s -------------------------------------- */
.global unknown2
.set unknown2, 0x102A4D50
.global unknown2_end
.set unknown2_end, 0x102BF2D0

/* --- ge007.ld segment markers ------------------------------------ */
/* RomStart/RomEnd are exact for asset segments; Start/End mirror them
/* (game code only ever uses End-Start size differences for these).
/* Code segments are approximate (see generator header comment). */
.global _headerSegmentRomStart
.set _headerSegmentRomStart, 0x10000000
.global _headerSegmentRomEnd
.set _headerSegmentRomEnd, 0x10000040
.global _headerSegmentStart
.set _headerSegmentStart, 0x10000000
.global _headerSegmentEnd
.set _headerSegmentEnd, 0x10000040  /* approximate */
.global _bootSegmentRomStart
.set _bootSegmentRomStart, 0x10000040
.global _bootSegmentRomEnd
.set _bootSegmentRomEnd, 0x10001000
.global _bootSegmentStart
.set _bootSegmentStart, 0x10000040
.global _bootSegmentEnd
.set _bootSegmentEnd, 0x10001000  /* approximate */
.global _startSegmentRomStart
.set _startSegmentRomStart, 0x10001000
.global _startSegmentRomEnd
.set _startSegmentRomEnd, 0x10001050
.global _startSegmentStart
.set _startSegmentStart, 0x10001000
.global _startSegmentEnd
.set _startSegmentEnd, 0x10001050  /* approximate */
.global _codeSegmentRomStart
.set _codeSegmentRomStart, 0x10001050
.global _codeSegmentRomEnd
.set _codeSegmentRomEnd, 0x10021990
.global _codeSegmentStart
.set _codeSegmentStart, 0x10001050
.global _codeSegmentEnd
.set _codeSegmentEnd, 0x10021990  /* approximate */
.global _cdataSegmentRomStart
.set _cdataSegmentRomStart, 0x10021990
.global _cdataSegmentRomEnd
.set _cdataSegmentRomEnd, 0x10032172
.global _cdataSegmentStart
.set _cdataSegmentStart, 0x10021990
.global _cdataSegmentEnd
.set _cdataSegmentEnd, 0x10032172  /* approximate */
.global _inflateSegmentRomStart
.set _inflateSegmentRomStart, 0x10032172
.global _inflateSegmentRomEnd
.set _inflateSegmentRomEnd, 0x10034B2F
.global _inflateSegmentStart
.set _inflateSegmentStart, 0x10032172
.global _inflateSegmentEnd
.set _inflateSegmentEnd, 0x10034B2F  /* approximate */
.global _gameSegmentRomStart
.set _gameSegmentRomStart, 0x10034B2F
.global _gameSegmentRomEnd
.set _gameSegmentRomEnd, 0x10117880
.global _gameSegmentStart
.set _gameSegmentStart, 0x10034B2F
.global _gameSegmentEnd
.set _gameSegmentEnd, 0x10117880  /* approximate */
.global _fontdlSegmentRomStart
.set _fontdlSegmentRomStart, 0x10117880
.global _fontdlSegmentRomEnd
.set _fontdlSegmentRomEnd, 0x10117940
.global _fontdlSegmentStart
.set _fontdlSegmentStart, 0x10117880
.global _fontdlSegmentEnd
.set _fontdlSegmentEnd, 0x10117940
.global _jfontchardataSegmentRomStart
.set _jfontchardataSegmentRomStart, 0x10117940
.global _jfontchardataSegmentRomEnd
.set _jfontchardataSegmentRomEnd, 0x10123040
.global _jfontchardataSegmentStart
.set _jfontchardataSegmentStart, 0x10117940
.global _jfontchardataSegmentEnd
.set _jfontchardataSegmentEnd, 0x10123040
.global _efontchardataSegmentRomStart
.set _efontchardataSegmentRomStart, 0x10123040
.global _efontchardataSegmentRomEnd
.set _efontchardataSegmentRomEnd, 0x10124AC0
.global _efontchardataSegmentStart
.set _efontchardataSegmentStart, 0x10123040
.global _efontchardataSegmentEnd
.set _efontchardataSegmentEnd, 0x10124AC0
.global _animation_entriesSegmentRomStart
.set _animation_entriesSegmentRomStart, 0x10124AC0
.global _animation_entriesSegmentRomEnd
.set _animation_entriesSegmentRomEnd, 0x1028E980
.global _animation_entriesSegmentStart
.set _animation_entriesSegmentStart, 0x10124AC0
.global _animation_entriesSegmentEnd
.set _animation_entriesSegmentEnd, 0x1028E980
.global _animation_dataSegmentRomStart
.set _animation_dataSegmentRomStart, 0x1028E980
.global _animation_dataSegmentRomEnd
.set _animation_dataSegmentRomEnd, 0x1029D160
.global _animation_dataSegmentStart
.set _animation_dataSegmentStart, 0x1028E980
.global _animation_dataSegmentEnd
.set _animation_dataSegmentEnd, 0x1029D160
.global _GlobalimagetableSegmentRomStart
.set _GlobalimagetableSegmentRomStart, 0x1029D160
.global _GlobalimagetableSegmentRomEnd
.set _GlobalimagetableSegmentRomEnd, 0x1029DC28
.global _GlobalimagetableSegmentStart
.set _GlobalimagetableSegmentStart, 0x1029D160
.global _GlobalimagetableSegmentEnd
.set _GlobalimagetableSegmentEnd, 0x1029DC28
.global _rarewarelogoSegmentRomStart
.set _rarewarelogoSegmentRomStart, 0x1029E560
.global _rarewarelogoSegmentRomEnd
.set _rarewarelogoSegmentRomEnd, 0x102A4D50
.global _rarewarelogoSegmentStart
.set _rarewarelogoSegmentStart, 0x1029E560
.global _rarewarelogoSegmentEnd
.set _rarewarelogoSegmentEnd, 0x102A4D50
.global _romfiles2SegmentRomStart
.set _romfiles2SegmentRomStart, 0x102A4D50
.global _romfiles2SegmentRomEnd
.set _romfiles2SegmentRomEnd, 0x102BF2D0
.global _romfiles2SegmentStart
.set _romfiles2SegmentStart, 0x102A4D50
.global _romfiles2SegmentEnd
.set _romfiles2SegmentEnd, 0x102BF2D0
.global _ramromfilesSegmentRomStart
.set _ramromfilesSegmentRomStart, 0x102BF2D0
.global _ramromfilesSegmentRomEnd
.set _ramromfilesSegmentRomEnd, 0x102E63F0
.global _ramromfilesSegmentStart
.set _ramromfilesSegmentStart, 0x102BF2D0
.global _ramromfilesSegmentEnd
.set _ramromfilesSegmentEnd, 0x102E63F0
.global _fontbankgothicSegmentRomStart
.set _fontbankgothicSegmentRomStart, 0x102E63F0
.global _fontbankgothicSegmentRomEnd
.set _fontbankgothicSegmentRomEnd, 0x102E88A0
.global _fontbankgothicSegmentStart
.set _fontbankgothicSegmentStart, 0x102E63F0
.global _fontbankgothicSegmentEnd
.set _fontbankgothicSegmentEnd, 0x102E88A0
.global _fontzurichboldSegmentRomStart
.set _fontzurichboldSegmentRomStart, 0x102E88A0
.global _fontzurichboldSegmentRomEnd
.set _fontzurichboldSegmentRomEnd, 0x102EBDE0
.global _fontzurichboldSegmentStart
.set _fontzurichboldSegmentStart, 0x102E88A0
.global _fontzurichboldSegmentEnd
.set _fontzurichboldSegmentEnd, 0x102EBDE0
.global _musicfilesSegmentRomStart
.set _musicfilesSegmentRomStart, 0x102EBDE0
.global _musicfilesSegmentRomEnd
.set _musicfilesSegmentRomEnd, 0x10438660
.global _musicfilesSegmentStart
.set _musicfilesSegmentStart, 0x102EBDE0
.global _musicfilesSegmentEnd
.set _musicfilesSegmentEnd, 0x10438660
.global _obsegSegmentRomStart
.set _obsegSegmentRomStart, 0x10438660
.global _obsegSegmentRomEnd
.set _obsegSegmentRomEnd, 0x108F7DF0
.global _obsegSegmentStart
.set _obsegSegmentStart, 0x10438660
.global _obsegSegmentEnd
.set _obsegSegmentEnd, 0x108F7DF0
.global _imagesSegmentRomStart
.set _imagesSegmentRomStart, 0x108F7DF0
.global _imagesSegmentRomEnd
.set _imagesSegmentRomEnd, 0x10C00000
.global _imagesSegmentStart
.set _imagesSegmentStart, 0x108F7DF0
.global _imagesSegmentEnd
.set _imagesSegmentEnd, 0x10C00000
.global _alt_startSegmentRomStart
.set _alt_startSegmentRomStart, 0x10101000
.global _alt_startSegmentStart
.set _alt_startSegmentStart, 0x10101000
