/*
 * ROM loading: reads the .z64 and maps it at the N64 cart address 0x10000000.
 *
 * Why the fixed address: every ROM asset symbol in the PC build is an ABSOLUTE
 * cart address (port/src/romassets_<region>.s, generated by
 * scripts/gen_romassets.py from ge007.ld + scripts/filelist.<r>.csv). Game
 * code takes `&symbol` and DMAs via romCopy()/osPiStartDma() exactly as on
 * hardware. If the ROM image is mapped at 0x10000000, those addresses are
 * live host pointers: PI reads become plain memcpys (see libultra.c) and
 * direct-read assets (fonts, image display lists) work unmodified.
 *
 * The N64 ROM header is GE-specific (src/rom_header.s): magic 0x80371240 at
 * 0x00, ROM name "GOLDENEYE" at 0x20, cartridge ID "GE" at 0x3C, country byte
 * at 0x3E ('E' US / 'P' EU / 'J' JP).
 *
 * STATUS: Phase 1 — load + validate + map. No segment patching needed: the
 * generated symbols already carry the layout.
 */

#include <stdlib.h>
#include <string.h>

#include "platform.h"

#if defined(PLATFORM_WINDOWS)
  #ifndef WIN32_LEAN_AND_MEAN
    #define WIN32_LEAN_AND_MEAN
  #endif
  #include <windows.h>
#endif

#include "system.h"
#include "fs.h"
#include "romdata.h"

#define CART_BASE   0x10000000u

static u8  *rom = NULL;        /* heap copy (fallback path) */
static u32  romSize = 0;
static int  mappedAtCartBase = 0;

/* Candidate ROM file names, in priority order. The decomp repo ships the
 * base ROM at the repo root (baserom.<r>.z64); a user-supplied final ROM in
 * data/ takes precedence. */
static const char *romFileCandidates(void)
{
#if GE007_IS_PAL
    return "ge007.pal-final.z64|baserom.e.z64";
#else
    return "ge007.ntsc-final.z64|baserom.u.z64";
#endif
}

static int romHeaderValid(const u8 *h, char *err, size_t errsz)
{
    static const u8 magic[4] = { 0x80, 0x37, 0x12, 0x40 };
#if GE007_IS_PAL
    const char country = 'P';
#else
    const char country = 'E';
#endif

    if (memcmp(h, magic, 4) != 0) {
        snprintf(err, errsz, "bad N64 magic at 0x00 (got %02x%02x%02x%02x)",
                 h[0], h[1], h[2], h[3]);
        return 0;
    }
    if (memcmp(h + 0x20, "GOLDENEYE", 9) != 0) {
        snprintf(err, errsz, "ROM name at 0x20 is not GOLDENEYE");
        return 0;
    }
    if (h[0x3C] != 'G' || h[0x3D] != 'E') {
        snprintf(err, errsz, "cartridge ID at 0x3C is not GE");
        return 0;
    }
    if (h[0x3E] != country) {
        snprintf(err, errsz, "country byte at 0x3E is %c, expected %c",
                 h[0x3E], country);
        return 0;
    }
    return 1;
}

int romdataInit(void)
{
    char err[128] = "";
    const char *list = romFileCandidates();
    char listBuf[512];
    strcpy(listBuf, list);

    /* Try each candidate in the data dir, next to the exe, and in the CWD
     * (the decomp repo ships baserom.<r>.z64 at the repo root). */
    for (char *tok = strtok(listBuf, "|"); tok;
         tok = strtok(NULL, "|")) {
        static const char *locs[3] = { "$S/", "$E/", "./" };
        int li;
        FSFile *f = NULL;

        for (li = 0; li < 3 && !f; li++) {
            char pathbuf[1024];
            snprintf(pathbuf, sizeof(pathbuf), "%s%s", locs[li], tok);
            f = fsOpen(sysResolvePath(pathbuf), "rb");
        }
        if (!f)
            continue;

        romSize = (u32)fsSize(f);
        u8 *img = (u8 *)malloc(romSize ? romSize : 1);
        int ok = img && fsRead(f, img, romSize) == (int32_t)romSize;
        fsClose(f);
        if (!ok) {
            free(img);
            continue;
        }

        if (romSize < 0x40 || !romHeaderValid(img, err, sizeof(err))) {
            sysLogPrintf(LOG_WARNING, "romdataInit: %s rejected: %s",
                         tok, err);
            free(img);
            continue;
        }

        /* Map at the cart address so absolute asset symbols are live. */
#if defined(PLATFORM_WINDOWS)
        void *at = VirtualAlloc((LPVOID)CART_BASE, romSize,
                                MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE);
        if (at == (void *)(uintptr_t)CART_BASE) {
            memcpy(at, img, romSize);
            free(img);
            mappedAtCartBase = 1;
            sysLogPrintf(LOG_INFO, "romdataInit: %s (%u bytes) mapped at "
                         "0x%08X (cart base)", tok, romSize, CART_BASE);
            return 0;
        }
        if (at)
            VirtualFree(at, 0, MEM_RELEASE);
        sysLogPrintf(LOG_WARNING, "romdataInit: could not reserve 0x%08X; "
                     "using heap copy — direct ROM reads will fail",
                     CART_BASE);
#else
        /* Best effort: fixed-hint mmap. If the hint is refused we fall back
         * to a heap copy (same limitation as above). */
        sysLogPrintf(LOG_WARNING, "romdataInit: fixed-address mapping not "
                     "implemented on this platform; using heap copy");
#endif

        rom = img;
        return 0;
    }

    sysLogPrintf(LOG_ERROR, "romdataInit: no ROM found (tried %s in data/ "
                 "and exe dir)", list);
    return -1;
}

void romdataDestroy(void)
{
#if defined(PLATFORM_WINDOWS)
    if (mappedAtCartBase) {
        VirtualFree((LPVOID)CART_BASE, 0, MEM_RELEASE);
        mappedAtCartBase = 0;
    }
#endif
    free(rom);
    rom = NULL;
    romSize = 0;
}

const u8 *romdataGetRom(void)
{
    if (mappedAtCartBase)
        return (const u8 *)(uintptr_t)CART_BASE;
    return rom;
}
u32       romdataGetRomSize(void) { return romSize; }

/*
 * Is this cart address inside the mapped ROM? Used by the PI shims to bounds-
 * check DMA before touching host memory.
 */
int romdataCartAddrValid(u32 addr, u32 size)
{
    if (!mappedAtCartBase || !romSize)
        return 0;
    if (addr < CART_BASE)
        return 0;
    u32 off = addr - CART_BASE;
    return off + size <= romSize;
}

const void *romdataMapVa(u32 va)
{
    /* N64 RDRAM VAs (0x80000000+/0xA0000000+) have no PC meaning; only cart
     * addresses are mapped. Kept for API parity with the PD port. */
    (void)va;
    return NULL;
}
